### ISSUE TITLE
Give attributes to writeGlobalFile's return value

### ISSUE THREAD

**Issue by arkal** [BD2KGenomics/toil#1014]
Start with size. So we can use it in promise lambdas

**Comment by hannes-ucsc** [comment]
This needs some explanation. Why are we pursuing this?

**Comment by arkal** [comment]
I wanted to see if this works before I added a bunch of documentation to it. I don't want to bake the size of files into my pipelines (i.e. saying run_bwa returns a tuple of (fsID of bam file, fsID of bai file, size of bam file). instead, in the lambdas we can just do `disk=PromisedRequirement(lambda x: x.size+30000, A.rv())`
