### ISSUE TITLE
Non-cached file read with mutable=True sometimes non-mutable

### ISSUE THREAD

**Issue by adderan** [BD2KGenomics/toil#1033]
The recursive call to readGlobalFile (at this line: https://github.com/BD2KGenomics/toil/blob/3974681ac5b903c967ca31b59d6890e20761859d/src/toil/job.py#L1171) doesn't include the mutable argument, so the file gets read as non-mutable regardless of what the outer readGlobalFile was called with.

**Comment by hannes-ucsc** [comment]
You probably want the link to refer to a specific commit, otherwise it's gonna go stale in no time.

**Comment by arkal** [comment]
good catch! I'll fix that

**Comment by arkal** [comment]
uhhh..... maybe i'll do it after the filestore refactor

**Comment by arkal** [comment]
Is this blocking you on anything @adderan ?

**Comment by adderan** [comment]
I have it fixed in my fork, so there's no problem for me.

**Comment by arkal** [comment]
(y) I'll fix it in my next PR
