### ISSUE TITLE
Move logging message for internal Toil job operations to DEBUG

### ISSUE THREAD

**Issue by chapmanb** [BD2KGenomics/toil#1061]
cc @arkal @hannes-ucsc 

This PR is spun out of the discussion in #1048. In CWL runs we see a large number of logging messages devoted to internal Toil processes output to INFO:

```
Got message from job at time 07-13-2016 10:15:21: Successfully deleted local copies of file with ID 'h/y/tmpMJXEcB.tmp'.
Got message from job at time 07-13-2016 10:15:21: Successfully deleted local copies of file with ID 'j/W/tmp2cwAzR.tmp'.
Got message from job at time 07-13-2016 10:15:21: Successfully deleted local copies of file with ID 'G/2/tmpGT1jJU.tmp'.
```

From the discussion, the work plan is to only report these messages in INFO if called through the Toil API, and if called from internal Toil (or Toil/CWL) processes report them as DEBUG.

**Comment by hannes-ucsc** [comment]
Proposed solutions:

* add `=quiet=False` kwarg to the fileStore methods (@arkal)
* add wrappers, e.g. `deleteGlobalFile()` makes the log entry and calls `_quietDeleteGlobalFile()` which does the real work but doesn't log (@hannes_ucsc)
* add wrappers dynamically with magic methods (@hannes_ucsc)
* add command line flag, e.g. --fileStoreLogLevel (@arkal)
* use `inspect` to determine whether calling frame belongs to Toil (@hannes_ucsc)
* use a counter to track entering/leaving Toil code, change log verbosity accordingly (@hannes_ucsc)

**Comment by chapmanb** [comment]
Hannes, Christopher and all;
I wanted to follow up on this discussion now that we've gotten CWL up to date with Toil. I'm doing testing on real runs and still struggle with keeping track of pipeline progress at a high level. For a cwltoil job run, the logging around an operation looks like:
```
kunkel 2016-12-23 11:57:04,043 MainThread INFO toil.leader: Starting the main loop
kunkel 2016-12-23 11:57:05,555 Thread-42 INFO toil.statsAndLogging: Got message from job at time 12-23-2016 11:57:05: Job 'CWLWorkflow' J/8/job1rtEsQ used 0.00% (0.0 B [0B] used, 2.0 GB [2147483648B] requested) at the end of its run.
kunkel 2016-12-23 11:57:07,069 Thread-42 INFO toil.statsAndLogging: Got message from job at time 12-23-2016 11:57:07: Job 'CWLScatter' e/p/jobFqHxl3 used 0.00% (0.0 B [0B] used, 2.0 GB [2147483648B] requested) at the end of its run.
kunkel 2016-12-23 11:57:07,071 Thread-42 INFO toil.statsAndLogging: Got message from job at time 12-23-2016 11:57:07: Job 'CWLScatter' Z/b/jobRxjcX2 used 0.00% (0.0 B [0B] used, 2.0 GB [2147483648B] requested) at the end of its run.
kunkel 2016-12-23 11:57:16,687 Thread-42 INFO toil.statsAndLogging: Got message from job at time 12-23-2016 11:57:16: Job 'file:///home/chapmanb/drive/work/cwl/test_bcbio_cwl/run_info-cwl-workflow/steps/prep_samples.cwl' bcbio_nextgen.py runfn prep_samples cwl L/N/jobjopV6K used 0.00% (104.0 KB [106496B] used, 2.0 GB [2147483648B] requested) at the end of its run.
kunkel 2016-12-23 11:57:16,687 Thread-42 INFO toil.statsAndLogging: Got message from job at time 12-23-2016 11:57:16: Successfully deleted local copies of file with ID 'q/F/tmpIRJx_G.tmp'.
kunkel 2016-12-23 11:57:16,687 Thread-42 INFO toil.statsAndLogging: Got message from job at time 12-23-2016 11:57:16: Successfully deleted local copies of file with ID 't/U/tmpUHV6fy.tmp'.
kunkel 2016-12-23 11:57:16,687 Thread-42 INFO toil.statsAndLogging: Got message from job at time 12-23-2016 11:57:16: Successfully deleted local copies of file with ID 'i/5/tmpItZXEN.tmp'.
kunkel 2016-12-23 11:57:16,687 Thread-42 INFO toil.statsAndLogging: Got message from job at time 12-23-2016 11:57:16: Successfully deleted local copies of file with ID '9/V/tmpI2FCLB.tmp'.
kunkel 2016-12-23 11:57:16,688 Thread-42 INFO toil.statsAndLogging: Got message from job at time 12-23-2016 11:57:16: Successfully deleted local copies of file with ID 'P/l/tmpQ2aA5b.tmp'.
kunkel 2016-12-23 11:57:16,688 Thread-42 INFO toil.statsAndLogging: Got message from job at time 12-23-2016 11:57:16: Successfully deleted local copies of file with ID 'z/c/tmpPTk5Bb.tmp'.
kunkel 2016-12-23 11:57:16,688 Thread-42 INFO toil.statsAndLogging: Got message from job at time 12-23-2016 11:57:16: Successfully deleted local copies of file with ID 'U/U/tmpokIXW4.tmp'.
```
So there are two kinds of non-helpful messages. The first are internal CWL calls:
```
kunkel 2016-12-23 11:57:05,555 Thread-42 INFO toil.statsAndLogging: Got message from job at time 12-23-2016 11:57:05: Job 'CWLWorkflow' J/8/job1rtEsQ used 0.00% (0.0 B [0B] used, 2.0 GB 
```
the second are deletion messages:
```
kunkel 2016-12-23 11:57:16,688 Thread-42 INFO toil.statsAndLogging: Got message from job at time 12-23-2016 11:57:16: Successfully deleted local copies of file with ID 'U/U/tmpokIXW4.tmp'.
```
What I'd like to do is remove these so we only see the one informative line about `prep_samples` finishing. Ideally we'd also have a logging message when this job starts.

Do you have tips/clues about how best to dig into this? I'm happy to work on but welcome suggestions about how best to do it the preferred Toil way so I can working within your plans. Thanks much.

**Comment by cket** [comment]
@chapmanb I'm in favor of moving the two non-helpful log statements to DEBUG as long as we get a WARNING level message when a job uses over 100% of the disk for the first message.

It actually might be difficult to log every time a job starts just because of Toil's logging mechanisms. The job is run on the worker & logs are usually only propagated when it finishes. The logToMaster mechanism is likely more what we would want, but I think that would be racy since it is independent from the way a job's success/failure is reported to the leader. We might end up with messages indicating failure before we get the message saying it has failed.

**Comment by chapmanb** [comment]
Thanks much for the thoughts and suggestions. I submitted a PR for this which moves the extra messages I'm seeing during my CWL runs to DEBUG. This makes following the progress much cleaner, thanks for working with me on this.

I would still like to be able to understand what jobs are currently ongoing. Right now it's easy to track the progress via the finished messages but hard to answer the question: "What is Toil running right now?" which would be useful for debugging stuck/long-running processes. If you have any suggestions about that happy to take a stab at improving it. Thanks again for the help with this.
