### ISSUE TITLE
Add back ability to disable caching

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#1072]
Create a second FileStore implementation that can fill in for the current caching one. Add `--disableCaching` and mention it in the error message that is raised when a BS is used that doesn't support the caching FileStore.

**Comment by hannes-ucsc** [comment]
Arjun volunteered! Due to his time constraints, we'll leave testing out of it for now if @chapmanb is willing to test it manually. Ultimately, it would be nice if we could run some tests agains both FileStore implementations.

**Comment by chapmanb** [comment]
Arjun and Hannes -- this is awesome, thanks so much for helping to put this in place. I'm happy to help with testing and anything else needed once you have an opportunity to look it.

**Comment by hannes-ucsc** [comment]
@cket , this is the ticket I've been talking about in today's scrum. @arkal and I looked at the code and determined that the most difficult aspect of this is how worker and FileStore interact for the asynchronous aka background writing of local files to the job store. The new non-caching FileStore implementation should not do background writing so you only need to study that interaction up to the point of being able to stub it out with something that "does nothing" or "immediately returns" or "does it immediately instead of in the background" if YKWIM. The less code you change in worker, the better.

Part two of this is testing. Think about a way of how the new FileStore can be covered by  the existing tests, e.g. by running a test with and without `--disableCaching`.
