### ISSUE TITLE
Consider auto-scaling the auto-scaling interval

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#1073]
It should be short initially to allow for the cluster to quickly grow to a decent size, from 0 mind you. It could be a function of the amount of recent activity. Or a function of the cluster size. Discuss with @benedictpaten.

**Comment by hannes-ucsc** [comment]
After discussing with @benedictpaten, we decided to keep constant for now, but change default to the 10s that have been working for me during the tests.

We'll need to gather more data before we can make a decision on this.

**Comment by cket** [comment]
Resolved by #1338
