### ISSUE TITLE
Missing documentation on ReadTheDocs

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#1076]
toil.fileStore, job, jobWrapper, resource, toilState and version modules appear on ReadTheDocs as titles with no content. 
http://toil.readthedocs.io/en/latest/generated_rst/toil.html#module-toil.fileStore
The other modules are visible down the linked page

**Comment by cket** [comment]
This problem is caused by sphinx api-doc not being able to generate documentation for classes- it only works at a module level. Everything under file:///Users/cj/toil/docs/_build/html/generated_rst/modules.html has the same problem. We could try find a new tool to generate better documentation here or we could drop this section. Since the relevant classes are already documented in http://toil.readthedocs.io/en/releases-3.3.x/toilAPI.html# I'm in favor of removing these links from the documentation. @hannes-ucsc what do you think?

Also, http://toil.readthedocs.io/en/releases-3.3.x/toilAPI.html#job-filestore is currently empty, I will fix that as part of this ticket.

**Comment by hannes-ucsc** [comment]
> sphinx api-doc not being able to generate documentation

Are you sure? Is that a documented inability?

**Comment by cket** [comment]
The documentation is sparse but theres no mention of being able to generate the autoclass directives that I think are needed. I'd be more confident if this was explicitly addressed in either api-doc or in the automodule directive documentation but I'm still pretty sure api-doc won't do class level documentation.

**Comment by hannes-ucsc** [comment]
Looking at boto as an example. If I'm right, this .rst document

https://raw.githubusercontent.com/boto/boto/develop/docs/source/ref/dynamodb2.rst

is used to produce  this page:

http://docs.pythonboto.org/en/latest/ref/dynamodb2.html

I do see classes in the latter even though they are not explicitly mentioned in the former.

**Comment by hannes-ucsc** [comment]
It wouldn't be the end of the world if we didn't automatically generate the per-module `.rst` files and committed them to the source tree instead.

**Comment by cket** [comment]
Thanks for the boto reference, that narrowed the problem down to our configuration! Out conf.py was set up to skip classes. I'm not sure why it was set up like that but removing it fixes the issue. 

It does introduce new problems though, there are now 160 warnings thrown vs. the 20 thrown before.

**Comment by hannes-ucsc** [comment]
> 160 warnings

Fix or suppress at your discretion.
