### ISSUE TITLE
Log level is permanently set at INFO

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#1077]
Adjusting `--logLevel` had no effect. When I looked closer, it appears that the `--logLevel` flag has been removed completely. 

Adjusting the log level within a toil script by manually setting `options.logLevel`  still works.

**Comment by hannes-ucsc** [comment]
`--logDebug` still works for me

**Comment by cket** [comment]
You're right, my mistake - the script I was trying to run used getDefaultOptions, which doesn't actually do any parsing from the command line.
