### ISSUE TITLE
toil-sort-example broken

### ISSUE THREAD

**Issue by joelarmstrong** [BD2KGenomics/toil#1080]
I see that the typo in toil-sort-example in the docs (running.rst in the docs) was fixed in #1075, but there are several other issues, mostly related to caching, that cause it to be completely broken. This caused some confusion last week when someone from our group was trying to use the docs to learn Toil.

The first error is due to expecting the CWD to be same on the worker as it is on the leader:

```
Traceback (most recent call last):
  File "toil-sort-example-still-broken.py", line 169, in <module>
    main()
  File "toil-sort-example-still-broken.py", line 162, in main
    make_file_to_sort(file_name='file_to_sort.txt', lines=options.num_lines, line_length=options.line_length)
  File "toil-sort-example-still-broken.py", line 140, in make_file_to_sort
    with open(file_name, 'w') as fileHandle:
IOError: [Errno 13] Permission denied: 'file_to_sort.txt'
```
but even after fixing that one, there are a few other problems. I'll file a PR with my fixed version.

Is there a way to convert the examples in the docs to unit tests?

**Comment by hannes-ucsc** [comment]
How embarrassing. Yes, Sphinx or docrunner should be able to run the examples but I've never used it. We have #525 open on that.

**Comment by hannes-ucsc** [comment]
And by "it" I mean that feature of Sphinx.
