### ISSUE TITLE
Add monitoring web application

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#1089]
Feature ideas:
- browse job store
- display a history of jobs run on a worker with duration and outcome
- display autoscaling statistics
- display all failed jobs with logs
- link to Mesos web app

**Comment by Jeltje** [comment]
Toil workflows should have an occasional check to see if any `runtime errors` happened in the jobs and exit prematurely if any are found. 

In the current setup, an early job failure will result in the program exiting with an error many hours later. This slows down debugging and burns through compute time unnecessarily.

**Comment by jvivian** [comment]
That's by design — If you're running multiple samples and one fails, you'd want the rest to finish. If one component of a workflow fails, the rest of the jobs will finish with the idea that you can restart the pipeline and finish the one failed job quickly.

**Comment by hannes-ucsc** [comment]
I could imagine scenarios where there is a systematic problem that would eventually cause all samples to fail. At the first sign of such a failure you might want to abort the run by hitting Ctrl-C. But right now the error scrolls past very quickly so its easy to miss. You can probably fix this with a clever arrangement of `tee` and `grep ERROR` but the monitoring web app should also expose failed jobs to make this easier.

**Comment by DailyDreaming** [comment]
Toil now uses Grafana.
