### ISSUE TITLE
CWL test_run_conformance connection time out

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#1098]
http://jenkins.cgcloud.info/job/toil-pull-requests/1701/testReport/junit/src.toil.test.cwl.cwlTest/CWLTest/test_run_conformance/

I reran the test suite with no changes and everything passed the second time. It looks like the problem was just a failure trying to clone CWL.

INFO:toil.test:Setting up toil.test.cwl.cwlTest.CWLTest.test_run_conformance ...
Cloning into '/mnt/ephemeral/workspace/toil-pull-requests/src/toil/test/cwl/spec'...
fatal: unable to access 'https://github.com/common-workflow-language/common-workflow-language.git/': Failed to connect to github.com port 443: Connection timed out
INFO:toil.test:Tore down toil.test.cwl.cwlTest.CWLTest.test_run_conformance

**Comment by hannes-ucsc** [comment]
I don't think there's anything we can do. Feel free to reopen, if you disagree, @cket.
