### ISSUE TITLE
JobStore problem when using GridEngine batch system

### ISSUE THREAD

**Issue by zichner** [BD2KGenomics/toil#1108]
Using the latest git version of Toil (last commit: 2ad4bad) with a gridengine batch system results in the following error:

```bash
> python HelloWorld.py --batchSystem gridEngine --disableCaching --logDebug file:jobStore
pc 2016-08-10 09:15:11,849 MainThread INFO toil.lib.bioio: Logging set at level: DEBUG
pc 2016-08-10 09:15:11,849 MainThread INFO toil.lib.bioio: Logging set at level: DEBUG
pc 2016-08-10 09:15:11,873 MainThread INFO toil.jobStores.fileJobStore: Path to job store directory is '/data/cwl-test/jobStore'.
pc 2016-08-10 09:15:11,901 MainThread INFO toil.jobStores.abstractJobStore: The workflow ID is: '095897de-df05-40d2-99ab-8bb5d1520d44'
pc 2016-08-10 09:15:11,920 MainThread INFO toil.common: Using the gridengine batch system
Traceback (most recent call last):
  File "HelloWorld.py", line 11, in <module>
    print Job.Runner.startToil(j, options) #Prints Hello, world!, ...
  File "/data/cwl-test/toil_git/lib/python2.7/site-packages/toil/job.py", line 542, in startToil
    return toil.start(job)
  File "/data/cwl-test/toil_git/lib/python2.7/site-packages/toil/common.py", line 550, in start
    userScript=rootJob.getUserScript())
  File "/data/cwl-test/toil_git/lib/python2.7/site-packages/toil/common.py", line 708, in createBatchSystem
    return batchSystemClass(**kwargs)
  File "/data/cwl-test/toil_git/lib/python2.7/site-packages/toil/batchSystems/gridengine.py", line 219, in __init__
    self.gridengineResultsFileHandle = open(self.gridengineResultsFile, 'w')
IOError: [Errno 2] No such file or directory: 'file:jobStore/results.txt'
```

Running the script locally (i.e., without `--batchSystem gridEngine --disableCaching`) is working without any errors.

NB: `HelloWorld.py` is taken from here: <http://toil.readthedocs.io/en/releases-3.3.x/running.html>

Thank you very much for your great work!

**Comment by hannes-ucsc** [comment]
The problem here is that the GridEngine batch system assumes that it gets a path, not a job store locator. I think this is a regression from when we started prefixing 'file:' to locators that look like file system paths for backwards compatibility. This is loosely related to #332.

**Comment by hannes-ucsc** [comment]
It should work with `./jobStore` instead of `file:jobStore` as a workaround.

**Comment by zichner** [comment]
Thank you very much for your reply! Using `./jobStore` instead of `file:jobStore` works.
Now, the pipeline is starting, but unfortunately, it is not terminating. I opened another issue regarding this: #1114
