### ISSUE TITLE
Azure Mesos template spams log about missing `preemptable` attribute

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#1126]
The Mesos batch system seems to expect its nodes to be tagged in Mesos with "preemptable" as either true or false. If not, it spams my logs with a lot of this:

```
WARNING:toil.batchSystems.mesos.batchSystem:Slave not marked as either preemptable or not. Assuming non-preemptable.
WARNING:toil.batchSystems.mesos.batchSystem:Slave not marked as either preemptable or not. Assuming non-preemptable.
WARNING:toil.batchSystems.mesos.batchSystem:Slave not marked as either preemptable or not. Assuming non-preemptable.
WARNING:toil.batchSystems.mesos.batchSystem:Slave not marked as either preemptable or not. Assuming non-preemptable.
```

1. Can it be made to be a little more quiet? I only have 4 slaves, and these messages are flooding my console output, and I don't care about them because I'm running in a cluster where nothing is ever going to be preempted by anything anyway.

2. I'm running in a cluster made with the default Azure Mesos template from the Toil repo. If Toil expects all Mesos nodes to have this info attached, Toil ought to be attaching it to all the nodes that it itself makes through its official template. It looks like maybe nobody tested the Mesos template after adding preemptability as a consideration?

**Comment by hannes-ucsc** [comment]
If you implement 2, do you still need 1?

**Comment by fnothaft** [comment]
IMO, you'd want 1 anyways for people who are running Mesos _not_ through the toil/cgcloud scripts (i.e., most of the installed Mesos userbase).

**Comment by hannes-ucsc** [comment]
I added that warning because at some time in the past I broke the code that sets up that attribute in cgcloud and didn't have any indication in Toil that I did. OTOH, I also see that the flooding is an issue.

**Comment by adamnovak** [comment]
I think https://github.com/adamnovak/toil/commit/6cbc4aac032eb577b091b7562d1842545230ecfb ought to solve point 2; it did when I ran it manually on all my worker nodes.
