### ISSUE TITLE
Promised requirement tests may not be strict enough

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#1159]
http://jenkins.cgcloud.info/job/toil-pull-requests/1814/

Despite a bug in my PR affecting resource requirements, most of the promised requirement tests still passed. All single machine tests passed but 2 mesos tests failed despite being mirrors of the single machine tests.

┆Issue Number: TOIL-110

**Comment by DailyDreaming** [comment]
Deprecated.
