### ISSUE TITLE
Toil appliance can't run other docker containers

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#1160]

**Comment by jvivian** [comment]
`-v /var/run/docker.sock:/var/run/docker.sock` allows the host Docker process to spawn the Docker containers being called within the pipeline.

The versions of Docker inside the container and on the host must be identical.

**Comment by hannes-ucsc** [comment]
Installation from statically linked binaries is documented here:

https://docs.docker.com/engine/installation/binaries/

We will need to produce one appliance image per Docker API protocol version.
