### ISSUE TITLE
Add support for PBS/Torque

### ISSUE THREAD

**Issue by alaindomissy** [BD2KGenomics/toil#1163]
It looks like we would need to make a torque version of this module: https://github.com/BD2KGenomics/toil/blob/master/src/toil/batchSystems/slurm.py 
This module includes 5 calls to slurm commands: sbatch, scancel, squeue, sinfo, sacct
which would need to be replaced with the equivalents: qsub, qdel, qstat, qstat -a, q?
A cheat sheet like this one might help: https://slurm.schedmd.com/rosetta.pdf
Also we would need to : 
- convert the command options 
- modify the processing of the outputs.... not sure how much they differ... 

There might be more ramifications... 
Comments, Thoughts ? Any one tried before ?
Thanks

**Comment by hannes-ucsc** [comment]
High-quality PRs are always welcome. So TORQUE is yet another flavor of SGE, like SLURM? The SLURM batch system implementation in Toil is an almost identical copy of the GridEngine one. I would prefer it if we could consolidate all flavors by extracting a common, abstract base class.

Keep in mind that we test on a CI cluster managed by CGCloud and Jenkins. The CGCloud role for the Jenkins slave that run the Toil unit tests would also have to be extended to install Torque.

**Comment by cjfields** [comment]
@alaindomissy I've started work on this [in a fork](https://github.com/HPCBio/toil) along with tests.  It's incomplete however, I have basic job submission but job ID checks, deleting jobs, etc. still needs to be implemented.  

What might be a better long-term option is a wrapper for DRMAA or similar that works across different schedulers.

**Comment by cjfields** [comment]
@alaindomissy Just a note, I'm working on moving the code to a branch in that fork so I can update to the latest toil.

**Comment by cjfields** [comment]
@alaindomissy see if the pull request #1195 works for you; it's passing batch system tests on our end currently.
