### ISSUE TITLE
Hot deployment localize() should catch EEXIST errors

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#1165]
Code currently catches ENOTEMPTY but EEXIST can also be raised.

**Comment by hannes-ucsc** [comment]
I think @arkal has a fix for this too in one of his PRs.

**Comment by arkal** [comment]
Are we talking about #517?

**Comment by hannes-ucsc** [comment]
> Are we talking about #517?

I don't think so. I clearly remember looking at the same line of code that's touched by @cket's 	463b84f and discussing the fact that OS X raises a different errno compared to Linux. It was either with @arkal or with @cket. It's not important, if I am right, someone will get a conflict.
