### ISSUE TITLE
Docker now required for tests?

### ISSUE THREAD

**Issue by cjfields** [BD2KGenomics/toil#1182]
I'm working on a fork that is adding PBS/Torque job manager support, and am attempting to run tests as I had in the past (and as described in the docs).  I noticed the following is now occurring:

```
(venv) -system-specific-4.1$ make test tests=src/toil/test/sort/sortTest.py::SortTest::testSort
Please set docker_registry, e.g. to quay.io/USER.
make: *** [check_docker_registry] Error 1
```

Is there any way to run tests that do not require Docker, such as standard batch system tests like SLURM, etc?  Our local HPC doesn't implement Docker for security reasons (they are looking into alternatives), so further development is kind of a non-starter for me at the moment.

**Comment by hannes-ucsc** [comment]
Right now you'd have to modify the Makefile and remove the docker-related dependencies from the `test` target.

I agree that the Toil build should function at least partially on systems without Docker installed. The easiest way is to detect if `docker` is installed and just skip things in the Makefile based on that. Docker-related tests would then also need to be made conditional with a new `@needs_docker` decorator.

**Comment by cjfields** [comment]
@hannes-ucsc thanks, just removing the Docker-specific portion for the `test` target works for now.  I agree that having docker tests run conditionally with a decorator makes sense.  

I also noticed that SGE jobs will try running on PBS/Torque (and fail), I think b/c the decorator is looking for the `qsub` executable, which PBS/Torque also has.  It might be better to use something like `qmake` for SGE and `pbsnodes` for PBS/Torque.  But I can work on that in the fork.
