### ISSUE TITLE
Job.Service needs access to the underlying job instance

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil#1191]
We're running into this in https://github.com/BD2KGenomics/toil-lib/pull/46. Specifically, if the `Job.Service.start` method invokes a Docker container via [docker_call](https://github.com/BD2KGenomics/toil-lib/blob/master/src/toil_lib/programs.py#L20) that cleans up the ghost container via a [`defer`red method](https://github.com/BD2KGenomics/toil/blob/master/src/toil/job.py#L549), we need the wrapping `ServiceJob`. To do this, we can swap out the `fileStore` parameter that is passed in the `start`/`stop` methods with the underlying job (since the fileStore can be accessed through the job).

**Comment by arkal** [comment]
+1. Can you add a service job test  in toil?
