### ISSUE TITLE
Should be able to run `make test` without building appliance docker container

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil#1193]
I frequently develop while offline or on a tether. I think it'd be nice to have a target like `test_offline` that doesn't build the Docker containers for the appliance and that skips the tests for the Docker appliance. Thoughts?

**Comment by hannes-ucsc** [comment]
See also #1182

**Comment by hannes-ucsc** [comment]
https://github.com/BD2KGenomics/toil/pull/1260/commits/c6d84854c349b1331cff78019e1d042494d61af2 resolves this but its title does not indicate that.
