### ISSUE TITLE
Retry pip installation failures in integration tests

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#1196]
http://jenkins.cgcloud.info/job/toil-pull-request-integration-tests/198/testReport/src.toil.test.provisioners.cgcloud.provisionerTest/CGCloudRestartTest/testAutoScaledCluster/

**Comment by hannes-ucsc** [comment]
Turned out to be a concurrency issue with pip: 85c71a712ae4a440bc8fe8347f44ad7356ead41e
