### ISSUE TITLE
Failures in the cluster scaler thread aren't propagated

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#1208]
If an exception is raised that kills the scaler thread Toil will try to continue running, potentially hanging until it is killed.

**Comment by hannes-ucsc** [comment]
We should probably add a hook into the scaler that attempts to join the scaler threads for a brief amount of time (join() takes a timeout). The threads are already ExceptionalThreads so any exception would be propagated through join.

**Comment by hannes-ucsc** [comment]
The hook would have to be invoked by the main loop.
