### ISSUE TITLE
Import files from FTP

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#1209]
It looks like there's a [fake JobStore that reads from http and https for file import](https://github.com/BD2KGenomics/toil/blob/master/src/toil/jobStores/abstractJobStore.py#L963) using urllib2. Since urllib2 can also do FTP, it would be easy to just add "ftp" to the list of protocols that this JobStore supports, to enable importing files from FTP.

Since many bioinformatics data sets live on FTP (like 1000 Genomes and the GRC reference assembly), it would be nice to just be able to point Toil at those URLs and have those resources available.

**Comment by hannes-ucsc** [comment]
+1

Pinging @JakeNarkizian, who's baby this is.

**Comment by adamnovak** [comment]
I've reached the point where I actually want this to work now. I guess I will try to do it.
