### ISSUE TITLE
Example in developing.rst has syntax error

### ISSUE THREAD

**Issue by cswarth** [BD2KGenomics/toil#1212]
https://github.com/BD2KGenomics/toil/blob/master/docs/developing.rst#dynamic-job-creation

The example code in the dynamic-job-creation section has a syntax error:

```
$ python --version
Python 2.7.12
$ python dynamic.py 
  File "dynamic.py", line 3
    def binaryStringFn(job, message="", depth):
SyntaxError: non-default argument follows default argument
```

**Comment by cswarth** [comment]
submitted PR #1215

**Comment by hannes-ucsc** [comment]
Usually we close issues when the corresponding PR is merged into master. In fact, GH does that automatically. I'm tempted to backport this one to 3.3.x.
