### ISSUE TITLE
All jobs should have access to the underlying fileStore

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil#1224]
From #1198, [comment](https://github.com/BD2KGenomics/toil/pull/1198#discussion_r84343466). Right now, only `ServiceJob` and `JobFunctionWrappingJob` set `self.fileStore`. We should make this consistent across jobs.

**Comment by jessebrennan** [comment]
This is actually not fixed. My original "fix" was completely wrong (see comment [here](https://github.com/BD2KGenomics/toil/pull/1337))
