### ISSUE TITLE
jobStoreTest's tearDown method not called reliably

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#123]
Our S3 console is full of test buckets from AWSjobStore, and when running fileJobStore temp files can be left behind.

**Comment by cket** [comment]
According to the documentation, the teardown method will be called even if there is an exception in the test method as long as the exception was not in the setup method. It's possible that keyboard interrupt exceptions in the setup method are causing the leftover buckets, especially since the aws setup runs for several seconds while it waits for s3 buckets and simpleDB domains

**Comment by hannes-ucsc** [comment]
Resolved by #190
