### ISSUE TITLE
Use parse_version

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#1242]

**Comment by hannes-ucsc** [comment]
@cket, do you remember what this one is about?

**Comment by cket** [comment]
We were moving to using parse_version instead of strict_version(?) and I opened this thinking it was applicable to Toil. Now that I look at it again I think it should actually be closed since we don't do any version parsing in Toil.. oops.

**Comment by hannes-ucsc** [comment]
We should use the `wontfix` label to distinguish from truly resolved issues from tickets like this one.
