### ISSUE TITLE
Expose warnings from `cwltool` in cwltoil output

### ISSUE THREAD

**Issue by cswarth** [BD2KGenomics/toil#1248]
I may be totally misunderstanding how cwltoil works, but I'm assuming it is running `cwltool` in most cases.

`cwltool` prints a warning if a config file looks like it uses javascript but does not require  `InlineJavascriptRequirement`.

```
$ cwltool  hello.cwl hello.yml 
/shared/silo_researcher/Matsen_F/MatsenGrp/working/cwarth/cft/toil/venv/bin/cwltool 1.0.20160714182449
Warning possible workflow bug: found '$(' or '${' in '$(inputs.message.replace(/\.[^/.]+$/, "") + ".sext")' but did not match valid parameter reference and InlineJavascriptRequirement not specified.
[...]
```

This warning is never surfaced to the user by `cwltoil`, and execution continues, often with completely bogus parameter references.

```
$ cwltoil  hello.cwl  hello.yml
stoat 2016-10-26 12:02:53,437 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
[...]
stoat 2016-10-26 12:02:56,860 MainThread INFO toil.common: Successfully deleted the job store
```

It would be great if `cwltoil` could expose the warning issued by `cwltool`, or generate an equally informative warning on its own.

hello.cwl:

```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: echo
inputs:
  message:
    type: string
    inputBinding:
      position: 1
outputs: 
  output:
    type: stdout
stdout: $(inputs.message.replace(/\.[^/.]+$/, "") + ".ext")
```

hello.yml:

```
message: foo.bar
```

**Comment by hannes-ucsc** [comment]
Toil suppresses the output of successful jobs unless you pass `--logDebug`. This is intentional. Consider a workflow that runs hundreds of thousands of tasks, most of them succeeding. The user is *typically* not interested in seeing the console output of that many jobs. If the console output of *every* task is important, passing `--logDebug` and parsing the leader output is certainly an option, however, this only works for small amounts of output per job, since Toil truncates worker output for efficiency. If each job produces large amount of console output, that output should be redirected to a file and stored in the job store.

Feel free to reopen if you're not satisfied with this response.

**Comment by cswarth** [comment]
Not interested in reopening, but I was presuming only warnings would be exposed in the default case.  Warnings should be in a different class of message from the tons of innocuous verbiage cwltool generates.

**Comment by hannes-ucsc** [comment]
Does passing --logDebug emit the warning?

**Comment by cswarth** [comment]
yes, --logDebug shows the warning, but it is buried in the output that is literally 10x more than the default case.

```
$ cwltoil --logDebug hello.cwl hello.yml 2>&1 | grep  Warn
R/T/jobO0I6qm    Warning possible workflow bug: found '$(' or '${' in '$(inputs.message.replace(/\.[^/.]+$/, "") + ".ext")' but did not match valid parameter reference and InlineJavascriptRequirement not specified.
R/T/jobO0I6qm    WARNING:cwltool:Warning possible workflow bug: found '$(' or '${' in '$(inputs.message.replace(/\.[^/.]+$/, "") + ".ext")' but did not match valid parameter reference and InlineJavascriptRequirement not specified.
R/T/jobO0I6qm    Warning possible workflow bug: found '$(' or '${' in '$(inputs.message.replace(/\.[^/.]+$/, "") + ".ext")' but did not match valid parameter reference and InlineJavascriptRequirement not specified.
R/T/jobO0I6qm    WARNING:cwltool:Warning possible workflow bug: found '$(' or '${' in '$(inputs.message.replace(/\.[^/.]+$/, "") + ".ext")' but did not match valid parameter reference and InlineJavascriptRequirement not specified.
```

My concern is that `cwltoil` commits a cardinal sin when it fails to carry out the user intent but provides no indication of failure.   In this example `cwltoil` succeeds but makes output files like,
```
-rw-r--r-- 1 cwarth phs_matsengrp      8 Oct 26 13:54 , "") + ".ext")
-rw-r--r-- 1 cwarth phs_matsengrp      8 Oct 26 13:54 , "") + "_2.ext")
-rw-r--r-- 1 cwarth phs_matsengrp      8 Oct 26 13:54 , "") + "_2_3.ext")
-rw-r--r-- 1 cwarth phs_matsengrp      8 Oct 26 13:54 , "") + "_2_3_4.ext")
-rw-r--r-- 1 cwarth phs_matsengrp      8 Oct 26 13:55 , "") + "_2_3_4_5.ext")
-rw-r--r-- 1 cwarth phs_matsengrp      8 Oct 26 13:59 , "") + "_2_3_4_5_6.ext")
-rw-r--r-- 1 cwarth phs_matsengrp      8 Oct 26 13:59 , "") + "_2_3_4_5_6_7.ext")
```
It's easy to overlook the need for `InlineJavascriptRequirement` because this line does NOT  require javascript,
```
stdout: $(inputs.message)
```
but this one does,
```
stdout: $(inputs.message + ".ext")
```

The cause is immediately obvious if the warning is visible and completely mysterious if it is not.
`cwltool` is telling `cwltoil` that something is wrong and `cwltoil` shouldn't deprecate that warning to a debug message.

**Comment by hannes-ucsc** [comment]
For CWL is there a way to turn warnings into errors, like gcc's `-Werror`?

**Comment by hannes-ucsc** [comment]
I recognize that this is a problem but I don't have a good grasp on what a solution might be. I have to weigh the cost of such a solution against the cost of asking users to `… --logDebug | grep -i warn`.

**Comment by cswarth** [comment]
I don't see anything like `-Werror` for the current version of `cwltool`.  
In `cwltool-1.0.20160714182449`  the warning is generated by `log.warn()`, but that same warning is entirely missing from the current version of `cwltool`

So there is no way to easily pick out the warning from cwltool output, and the warning might not even be there.  

Maybe a tighter integration with the cwltool package would help?  I don't know what you are calling cwltool for but I assume it is for expansion and validation of the cwl config file.  If there were a well defined API for what you need you could have fine-grained control over parsing, etc.

This should be closed but it's something to keep in mind.   Thanks for the discussion.

**Comment by mr-c** [comment]
@cswarth In the current `cwltool` your example now produces a `JavascriptException` and execution is halted

```
cwltool.py 1.0.20161115103846
Resolved 'hello.cwl' to 'file:///home/michael/cwltool/hello.cwl'
Got workflow error
Traceback (most recent call last):
  File "/home/michael/cwltool/cwltool/main.py", line 226, in single_job_executor
    for r in jobiter:
  File "/home/michael/cwltool/cwltool/draft2tool.py", line 296, in job
    j.stdout = builder.do_eval(self.tool["stdout"])
  File "/home/michael/cwltool/cwltool/builder.py", line 206, in do_eval
    timeout=self.timeout)
  File "/home/michael/cwltool/cwltool/expression.py", line 186, in do_eval
    jslib=jslib)
  File "/home/michael/cwltool/cwltool/expression.py", line 144, in interpolate
    timeout=timeout)
  File "/home/michael/cwltool/cwltool/expression.py", line 131, in evaluator
    raise sandboxjs.JavascriptException("Syntax error in parameter reference '%s' or used Javascript code without specifying InlineJavascriptRequirement.", ex)
JavascriptException: ("Syntax error in parameter reference '%s' or used Javascript code without specifying InlineJavascriptRequirement.", '(inputs.message.replace(/\\.[^/.]+$/, "") + ".ext")')
Workflow error, try again with --debug for more information:
  ("Syntax error in parameter reference '%s' or used Javascript code without specifying InlineJavascriptRequirement.", '(inputs.message.replace(/\\.[^/.]+$/, "") + ".ext")')
```
