### ISSUE TITLE
Change stats reporting to use JSON instead of XML, or some better binary format

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/toil#125]

**Comment by hannes-ucsc** [comment]
I'd prefer a pickled dict subclass that exposes its keys as attributes. John has used these before. This is what argparse's namespace class does. Then I can do 

config.foo

instead of 

config.attrib['foo']

**Comment by hannes-ucsc** [comment]
Sorry wrong issue.

**Comment by hannes-ucsc** [comment]
@cket, check out Expando and MagicExpando:

https://github.com/BD2KGenomics/bd2k-python-lib/blob/master/src/bd2k/util/expando.py
