### ISSUE TITLE
Use new disk-usage monitoring to adjust disk requirement on failure

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#1257]
If a job fails its disk requirement is set to a minimum of 2GB. We should instead set it to some value greater than the observed max of the failed job if that max was above the job's claimed disk requirement.

**Comment by hannes-ucsc** [comment]
I'm not a fan of the requirement bumps. I believe the memory bump was for one particular script and that use case is long gone. We always emphasize the importance of specifying accurate requirements and then we encourage sloppyness with these half-baked heuristics.

**Comment by cket** [comment]
The current 2GB bump is probably obsolete but I think this enhancement would be valuable, and is low hanging fruit now that we have both the disk usage data and the requirement bump mechanism already in place. 

IIRC most of the existing pipelines' resource requirements are heuristics and I imagine we come across edge conditions where those requirements fail. Currently, the only thing to do in those circumstances is bump the requirement for that entire class of job and restart, reducing efficiency and requiring user intervention. 

I'm proposing that we cleanly catch those problems by using the disk usage data to bump only the failing job's requirements. That mechanism is likely more accurate than a user's estimate anyway and prevents both the efficiency loss and the restart.

**Comment by hannes-ucsc** [comment]
> IIRC most of the existing pipelines' resource requirements are heuristics

That is correct. But they are supposed to be heuristics for an upper bound.

I want to give users a clear message: If your requirements are wrong, your jobs will fail. In the long run, this is more sustainable. If we patch one bad heuristic with another bad heuristic, the benefits you mention are only short term. If we encourage users to improve their heuristics we will be in a better place in the long run since more accurate requirements allow for more aggressive optimizations.

> That mechanism is likely more accurate than a user's estimate anyway

How so?

**Comment by cket** [comment]
Summarization of conversation with @arkal and @hannes-ucsc:
This should not be the default behavior. We should enable it with a command line flag
`--safeMode=scalingFactor`
(names to be decided later). The scaling factor is used to calculate the new resource requirement after a job fails in this following way:
`newRequirement = scalingFactor * diskUsageAtJobsEnd`
if and only if the final disk usage is above what the job requested. We may also want to increase the other resource requirements by the same scaling factor.
