### ISSUE TITLE
Worker fails to unpickle job if job arguments refer to user-defined types

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#1259]
A JobFunctionWrappingJob/FunctionWrappingJob instance refers to 

1) the user module
2) the user function 
3) the args and kwargs for the function invocation

While 1) and 2) are symbolic references, 3) is not. The reason they are symbolic is to allow for the instance to be unpickled without having to load the user module. Once the job instance exists, we can use 1) to load the user module and 2) to extract the user function. If, however, the object graph from 3) references any types defined in the the user script, the unpickling will fail.

Update: I can't reproduce this without encapsulated jobs, so this seems to be specific to encapsulation. Moreover, what I describe above is partially wrong: the actual user script has already been loaded when the job instance is unpickled. This is because JobFunctionWrappingJob/FunctionWrappingJob override getUserScript() to return the module that the function is defined in. This module also contains the user-defined types, allowing them to be loaded during unpickling.

**Comment by hannes-ucsc** [comment]
Work-arounds are A) to pickle the arguments explicitly or B) to use and define custom subclasses of `JobFunctionWrappingJob` or `FunctionWrappingJob` in the user script. The former will avoid embedding type references in the pickled job that point at user-defined types. The latter will cause the user script to be loaded before the instance is unpickled, thereby ensuring that user-defined types are available.

It might be possible to implement A in a generic way in Toil.

**Comment by hannes-ucsc** [comment]
@jpfeil, could you paste a backtrace so @fnothaft can compare it to his records? He may have run into it on his side, too. In a nutshell, it boils down to a worker exception indicating that the GermlineSample class can not be loaded during the unpickling of a job.

**Comment by jpfeil** [comment]
https://gist.github.com/jpfeil/7779998b9ba4b38ff07d117c14561da9

**Comment by jpfeil** [comment]
Sorry, wrong gist. Use this one: <script src="https://gist.github.com/jpfeil/fcfefb8c5ec5b1bb3643d612403b845d.js"></script>

**Comment by jpfeil** [comment]
Okay, this is the last time. https://gist.github.com/jpfeil/fcfefb8c5ec5b1bb3643d612403b845d

**Comment by fnothaft** [comment]
That looks similar to what I was seeing, let me see if I still have my logs around...

**Comment by hannes-ucsc** [comment]
I just added an update to the description.

**Comment by hannes-ucsc** [comment]
@jpfeil could you undo your workaround and verify that my changes fix your problem?

**Comment by jpfeil** [comment]
Sure!

**Comment by jpfeil** [comment]
It looks like your changes fixed the hot deployment problem. Thanks Hannes!

**Comment by hannes-ucsc** [comment]
Thanks for verifying.
