### ISSUE TITLE
Make disk logging messages debug level

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#1263]
Right now we get an info level message for every job describing the disk usage & then another warning level message if the job exceeded its requirement. 

IMO the info level message should be debug level but we can keep the warning message at its current level.

**Comment by arkal** [comment]
I think @hannes-ucsc and I discussed this and decided in INFO instead of DEBUG but you can double check with him.

**Comment by hannes-ucsc** [comment]
What was our reasoning for INFO?

**Comment by arkal** [comment]
That given the amount of logs that show up normally, this won't really add all that much and it's important information for the user to tweak parameters for future runs.

**Comment by hannes-ucsc** [comment]
Talked to @cket. We should leave this at INFO. When we clean up logging, we should clean it up in a way that lets us make WARNING the default. INFO will be for power users or people who are just interested in knowing whats going on. DEBUG is for developers.

**Comment by arkal** [comment]
Is that normal? WARNING as a default?

**Comment by hannes-ucsc** [comment]
Good software just does what its supposed to and only prints an error message if something goes wrong. So really, ERROR should be the default. WARNING is already a deviation from the norm.

**Comment by cket** [comment]
Continued in #1268 - I was going to just repurpose this ticket by renaming it but we also have several comments here.
