### ISSUE TITLE
Add continuous integration to cgl-docker-lib

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil#127]

**Comment by jvivian** [comment]
http://jenkins.cgcloud.info/job/cgl-docker-lib/

**Comment by jvivian** [comment]
First step:  Write a cgcloud role for the jenkins slave box that where the building/testing will take place.

**Comment by jvivian** [comment]
Hannes and I will set this up Friday (9/17/15)

**Comment by jvivian** [comment]
Issue:
Successfully running make on a tool doesn’t do anything to ensure that the tool actually does anything meaningful. 

Only solution I've thought of yet is to write a companion unittest for each tool that gets run when that tool gets rebuilt.

**Comment by hannes-ucsc** [comment]
Re: Smoke testing each container: I think that's a good idea. That should happen for every modified tool, and before the image is pushed such that nothing is pushed if the test fails. A test failure in one tool should prevent any tool from being pushed, it shouldn't prevent other modified tools from being tested.

It's now pretty easy to pull Docker into a role. See ToilJenkinsSlave.

**Comment by jvivian** [comment]
credential files were placed in the jenkins master home directory and the global jenkins configuration was modified to include those credentials when creating slaves.

**Comment by hannes-ucsc** [comment]
Fixed by https://github.com/BD2KGenomics/cgcloud/commit/f8b675b1c2ed0412f83cd00b38db4e121ce9a5a7
