### ISSUE TITLE
Workaround pip issue 4059

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#1270]
Symptom:

http://jenkins.cgcloud.info/job/toil-pull-requests/2029/testReport/src.toil.test.src.resourceTest/ResourceTest/testVirtualEnv/

Upstream ticket:

https://github.com/pypa/pip/issues/4059

We should prevent the latest pip from being installed in the virtualenv.

**Comment by cket** [comment]
Does this need to be backported? It seems to be showing up on the 3.3.x branch
http://jenkins.cgcloud.info/job/toil-pull-requests/2059/testReport/junit/src.toil.test.src.resourceTest/ResourceTest/testVirtualEnv/

**Comment by hannes-ucsc** [comment]
Yes. Cherrypicking won't work, though as the changes are scattered around.  For the original fix I search for all occurrences of `virtualenv`. Would mind taking this over?

**Comment by cket** [comment]
Sure, I'll take it
