### ISSUE TITLE
Assertion error in bucket creation

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#1272]
http://jenkins.cgcloud.info/job/toil-pull-requests/2032/testReport/src.toil.test.jobStores.jobStoreTest/AWSJobStoreTest/test_testImportExportFile__otherCls_awsjobstoretest__size_one/

Note that the assertion message is mangled by  pytest's weird assertion introspection.

**Comment by natanlao** [comment]
I encountered this when testing #1320. [Jenkins log here.](http://jenkins.cgcloud.info/job/toil-pull-requests/2199/testReport/junit/src.toil.test.jobStores.jobStoreTest/EncryptedAWSJobStoreTest/test_testImportExportFile__otherCls_awsjobstoretest__size_partsizeplusone/) It went away after I triggered the test again.
