### ISSUE TITLE
Random DAG test should exercise restarts

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#1293]
Issues like #1289 underline the necessity of this. Restarts go through an entirely different path than retries. Both need to be covered.

**Comment by hannes-ucsc** [comment]
@benedictpaten can you confirm that this was addressed by #1264?

**Comment by cket** [comment]
@benedictpaten pinging for an answer to @hannes-ucsc's question

**Comment by benedictpaten** [comment]
Yes, this was resolved by #1264
