### ISSUE TITLE
The sort example in running.rst has way too much code

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#1303]
http://toil.readthedocs.io/en/latest/running.html#running-a-toil-pipeline-in-detail

Documentation should contain small code snippets for illustrative purposes only. Pasting an entire script is 1) tedious for the reader and 2) difficult to maintain for us. We need to A) reduce and simplify the script, and break it up into multiple sections with explanations in between, or B) link to the sort.py file in the repo. I'm sure Sphinx has a way to embed/link longer code sections from external files. For B) sort.py may have to be refactored to allow for use as both a test and in the documentation. A) would still be hard to maintain but at least the reader gets additional value from the additional explanations.

**Comment by jessebrennan** [comment]
This wasn't really done correctly. There were two separate files. #1746 is fixing this now.
