### ISSUE TITLE
Log level must be explicitly set for RealtimeLogger to work

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#1316]
I have logging statements in my user code that log through the Toil RealtimeLogger. However, the RealtimeLogger doesn't get initialized unless I specify one of the Toil log level options (--logInfo, --logWarning, etc.). Without those I just get a message that it is disabled, even when I pass --realTimeLogging.

Instead, the real time logger should be enabled with the default log level if --realTimeLogging alone is passed.

**Comment by hannes-ucsc** [comment]
You might want to file the last paragraph as a separate issue.

**Comment by adamnovak** [comment]
I've just discovered this issue again, in my pursuit of #1818, and was about to report it again.

```
[anovak@kolossus test]$ ./test_workflow.py --help 2>&1 | grep realTimeLogging
                        [--writeLogsGzip [WRITELOGSGZIP]] [--realTimeLogging]
  --realTimeLogging     Enable real-time logging from workers to masters
[anovak@kolossus test]$ ./test_workflow.py tree --realTimeLogging 2>&1 | grep toil.realtimeLogger
kolossus 2017-08-15 11:12:42,966 MainThread INFO toil.realtimeLogger: Real-time logging disabled
[anovak@kolossus test]$ 
```
