### ISSUE TITLE
Can't restart after failures in file export code

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#1319]
The basic flow of a Toil script is:

1. Import files to the file store from somewhere
2. Run a bunch of Toil jobs that manipulate these files and produce output files
3. Export the output files from the file store to somewhere

I recently had a Toil script fail at step 3. I tried to restart it, but since the root job had already finished, Toil couldn't do anything useful with the job store, complaining that the root job had finished or had never been started.

Here's the message I get from Toil:

```
INFO:root:Running on Toil from /cluster/home/anovak/python/lib/python2.7/site-packages/toil-3.5.0a1.dev251-py2.7.egg/toil/__init__.pyc
INFO:toil.lib.bioio:Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
INFO:toil.jobStores.fileJobStore:Path to job store directory is '/hive/users/anovak/ga4gh/hgvm/hgvm-builder/tree'.
INFO:toil.common:Using the single machine batch system
WARNING:toil.batchSystems.singleMachine:Limiting maxCores to CPU count of system (64).
WARNING:toil.batchSystems.singleMachine:Limiting maxMemory to physically available memory (1084169011200).
INFO:toil.common:Created the workflow directory at /scratch/tmp/toil-aaf73598-8176-451c-b972-dc7d339ce25e
WARNING:toil.batchSystems.singleMachine:Limiting maxDisk to physically available disk (738563751936).
INFO:toil.batchSystems.singleMachine:Setting up the thread pool with 640 workers, given a minimum CPU fraction of 0.100000 and a maximum CPU value of 64.
INFO:toil.common:Written the environment for the jobs to the environment file
INFO:toil.common:Caching all jobs in job store
INFO:toil.common:0 jobs downloaded.
INFO:toil.jobStores.abstractJobStore:Checking job graph connectivity...
Traceback (most recent call last):
  File "/cluster/home/anovak/python/bin/build-hgvm", line 11, in <module>
    load_entry_point('hgvm-builder', 'console_scripts', 'build-hgvm')()
  File "/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src/hgvmbuilder/build.py", line 245, in entrypoint
    sys.exit(main(sys.argv))
  File "/hive/users/anovak/ga4gh/hgvm/hgvm-builder/src/hgvmbuilder/build.py", line 214, in main
    toil_instance.restart()
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil-3.5.0a1.dev251-py2.7.egg/toil/common.py", line 619, in restart
    rootJob = self._jobStore.clean(jobCache=self._jobCache)
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil-3.5.0a1.dev251-py2.7.egg/toil/jobStores/abstractJobStore.py", line 475, in clean
    getConnectedJobs(self.loadRootJob())
  File "/cluster/home/anovak/python/lib/python2.7/site-packages/toil-3.5.0a1.dev251-py2.7.egg/toil/jobStores/abstractJobStore.py", line 190, in loadRootJob
    "is finished or has never been started" % rootJobStoreID)
```

I need to be able to successfully call restart(), and get the return value from the root job, as many times as it takes, in different invocations of my user script, until the code in the `with Toil(options) as toil_instance:` block finishes without throwing an error.

**Comment by hannes-ucsc** [comment]
I agree that this is a problem. I disagree that `--restart` is applicable here. It would be weird to use `--restart` to resume failed imports before the workflow has even started. Failed imports are equally likely as failed exports. The `import/export on leader` feature is still a valid use case. CWL depends on it, for example. Should we instead implement special leader jobs that are tracked by Toil but are guaranteed to run on the leader?

**Comment by hannes-ucsc** [comment]
With leader jobs, `--restart` would be applicable.

**Comment by adamnovak** [comment]
If jobs can import and export, it would make sense to be able to delegate
imports from HTTP and FTP sources to workers. Only file URL imports and
exports really need to happen on the leader.

**Comment by hannes-ucsc** [comment]
Maybe Toil.importFile() and Toil.exportFile() can be rewritten to make use of these `leader jobs`.

**Comment by adamnovak** [comment]
I just wanted to note that I have once again lost time to this bug. This time it's about 3 hours of wallclock time on kolossus that I'm going to have to repeat, but in the future it might be hundreds of dollars of AWS credit.

Maybe we shouldn't delete the return value of the root job until the user script on the master exits successfully?

**Comment by joelarmstrong** [comment]
Wait, is this still a thing? This is really easy to fix if so: we can just check for whether the root promise has been fulfilled before doing anything else.

**Comment by adamnovak** [comment]
I'm not sure. I haven't had this happen lately.
