### ISSUE TITLE
Fixing service deadlocks

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/toil#1321]
We currently have three deadlock scenarios possible  in Toil by the current design (that I'm aware of!), all relate to service scheduling.

 In the first two cases (a) all the jobs in the cluster end up running services and (b) the cluster has reached its maximum possible size (either statically or through autoscaling). The two cases:

(Sub case 1) There remain non-service jobs in the queue 

(Sub case 2) There are no non-service jobs in the queue and there are service jobs in the queue.

Note, it should not be possible to reach a deadlock and have no jobs in the queue at all and have all the nodes running services.

I propose the following solution to the two sub-cases:

For (1) have a maximum services parameter such that at most x (or a proportion of the max) services are running. 

For (2), I do not see a clean solution, and propose recognising the case and throwing an exception advising the user to up the maximum number of concurrent services/increase the cluster size.

The result is that it should not be possible to deadlock in either case - although a crash is undesirable, it is definitely better than a deadlock.

The third case is more subtle - it occurs when the autoscaler estimates the number of nodes to complete a batch based on completed jobs and fails to recognise that there are running service jobs that will never finish without increasing the cluster size. To fix this I propose to ensure that run time of current jobs is factored in to the queue wait time so that the longer that services wait the more machines will be provisioned, helping to ensure that non-service jobs are given space on the cluster more quickly.

**Comment by hannes-ucsc** [comment]
I changed my mind about the node cost estimate: I wouldn't read the node cost estimate from the command line option directly. I would simply make the `--nodeType` and `--preemptableNodeType` options accept multiple node types  (via `action='append'`), pass those to the provisioner and allow the provisioner to derive the cost for each type. I would change `AbstractProvisioner.getNodeShape` to `getNodeShapes` (plural), have it return a list of `Shape` objects and add a `.cost` attribute to `Shape`. If `Shape` should not have that attribute, derive a new class called HostShape to extend Shape and add `cost`.
