### ISSUE TITLE
Create autoscaling stats collection mechanism

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#1327]
Collect the following data points over time

- number of nodes (P and NP)
- key parameters to the scaler thread
- key batch system stats, e.g. queue lengths
- key provisioner stats (node load)
- what else?

Collect data points in memory. Define file format for dumping to disk. Dump to disk at end of run. Consider implementing a size limit (ring buffer or thinning out older data points).

**Comment by cket** [comment]
Node load stats are tracked in #1339
