### ISSUE TITLE
Sporadic 409 error in AWS job store

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#1333]
Test file deletion:
http://jenkins.cgcloud.info/job/toil-pull-requests/2228/testReport/src.toil.test.jobStores.jobStoreTest/EncryptedAWSJobStoreTest/testFileDeletion/

Cache tests:
http://jenkins.cgcloud.info/job/toil-pull-requests/2190/testReport/src.toil.test.src.jobCacheTest/AwsJobStoreCacheTest/testWriteNonLocalFileToJobStore/

http://jenkins.cgcloud.info/job/toil-pull-requests/2134/testReport/src.toil.test.src.jobCacheTest/AwsJobStoreCacheTest/testCacheEvictionTotalEvict/

I believe I've also seen this with import/export, but I couldn't find any example builds.

**Comment by hannes-ucsc** [comment]
Duplicates #1093.
