### ISSUE TITLE
Optionally tag auto-scaled EC2 instances with user-specified tags

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#1341]
Add `--tag key=value` to the ~~`toil create-cluster`~~ `toil launch-cluster` entry point and use the provided key and value to tag all instances, the leader and subsequently auto-scaled worker instances.

Note that auto-scaling (i.e. the creation of worker nodes) usually happens in a different process, not the ~~`toil create-cluster`~~ `toil launch-cluster` one.  It happens in the leader process, when the user script is run on the leader. When a new worker instance has been created in the leader, simply copy the leader's tags to newly created worker instance. I know of at least one standard tag that should not be copied. I think the name of that tag is `Name` and the EC2 console uses it for the column of the same name in the list view of all instances.

For argparse, specify `action=append` such that the user can specify it multiple times. Also add a short form `-T`:

`-T foo=bar -T x=y`

**Comment by jessebrennan** [comment]
@hannes-ucsc from what I can tell so far, `create-cluster` is a CGCloud command to launch a cluster for Toil as in number 7 [here](http://toil.readthedocs.io/en/issues-1296-doc-sidebar/installation.html?highlight=create-cluster#cgcloud-in-a-nutshell). 

I assume you meant `toil launch-cluster`?

**Comment by hannes-ucsc** [comment]
> I assume you meant `toil launch-cluster`?

Correct. I'll fix it in the description.

**Comment by cket** [comment]
We also need to always include the tag: Key: Owner Value: <IAM username> so we can track the cluster's expenses.
