### ISSUE TITLE
Replace _getDebugCmd with new job name implementation

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#1343]
We should consider setting Job's jobName attribute in CWLToil to reflect the CWL step. The unitName attribute could be the sample name.

**Comment by chapmanb** [comment]
Christopher -- happy to migrate to the Toil approach for doing this. Is there documentation about what I should be setting for debugging? Just these two attributes for any classes derived from Job? Or are there other changes.

**Comment by cket** [comment]
Just those two attributes are sufficient. #1197 improved debugging native Toil jobs by making Job.__str__ return a reasonable name for the job, including the name of the method or class that defines them. The Job class automatically populates the 'jobName' attribute with this information. Users can also optionally set the 'unitName' attribute to whatever might help them with debugging, usually the sample's ID. Once these are set, calling str(job) will return the jobName followed by the unitName (if it's set), followed by the job's job store ID.

CWLToil is a special case since the steps aren't native Toil jobs so while the 'jobName' attribute is automatically set to a class name like CWLWorkflow, CWLGather, etc. they aren't particularly useful. The 'jobName' attribute should be set explicitly to a CWL analog (command?), but you can rely on the Job constructor to properly handle the 'unitName' parameter if you pass it when you construct a new CWL job.

**Comment by cket** [comment]
@chapmanb mind if I take this over? I just ran into an unpicking error thrown by _getDebugCmd so I'm probably going to implement this rather than fix the existing method

**Comment by cket** [comment]
jenkins, test this please

**Comment by chapmanb** [comment]
Christopher -- absolutely, thanks for taking this over. Apologies for being so slow and not yet having time to work on this. Much appreciated.

**Comment by cket** [comment]
No worries! I have an first pass at it in #1368
