### ISSUE TITLE
Sporadic caching failures

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#1344]
Seen on master, unfortunately.
http://jenkins.cgcloud.info/job/toil-branches/branch/master/286/console
It seems more common on the AWS job store, I will update this ticket with links for those failures once I've found them.

**Comment by hannes-ucsc** [comment]
Seems to be deterministic.

**Comment by hannes-ucsc** [comment]
http://jenkins.cgcloud.info/job/toil-branches/branch/master/286/testReport/src.toil.test.src.fileStoreTest/CachingFileStoreTestWithFileJobStore/testAsyncWriteWithCaching/history/

**Comment by arkal** [comment]
This test is the problem @hannes-ucsc . WE tried monkey patching but it's still apparently really non-determinisitc. I say for now we just skip this till we can figure out how we can test something that is inherently so non-deterministic.

**Comment by arkal** [comment]
it always passes on my laptop, and before i pushed it to jenkins, it passed 10 times in a row on a jenkins slave i had spun up

**Comment by cket** [comment]
@arkal How do you know this is a problem with the test itself and not the caching code?

**Comment by arkal** [comment]
because i've walked through the logs on the pass and fail cases and from the print statements i know the behaviour is exactly as expected.

**Comment by arkal** [comment]
The non-determinism comes from the fact that it takes longer to start a new job than it does to finish writing the file to the filestore asynchronously.

**Comment by arkal** [comment]
but maybe it has something to do with the code and i'll look into it as well.

**Comment by cket** [comment]
@arkal where/how did you monkey patch the test?
