### ISSUE TITLE
Run lots of commands in parallel?

### ISSUE THREAD

**Issue by sb10** [BD2KGenomics/toil#1376]
Is there a forum or mailing list for asking usage questions?

I'm new to toil and am trying to work out how to do some simple initial things, like run the same command on thousands of different inputs, in parallel.

Based on the docs I tried this:

    from toil.job import Job

    def echo(job, message, memory="10M", cores=1, disk="10M"):
        job.fileStore.logToMaster("%s" % message)

    j1 = Job.wrapJobFn(echo, "echo 1")
    j2 = j1.addChildJobFn(echo, "echo 2")
    j3 = j1.addChildJobFn(echo, "echo 3")
    j4 = j1.addChildJobFn(echo, "echo 4")
    ...
    j9997 = j1.addChildJobFn(echo, "echo 9997")
    j9998 = j1.addChildJobFn(echo, "echo 9998")
    j9999 = j1.addChildJobFn(echo, "echo 9999")
    j10000 = j1.addChildJobFn(echo, "echo 10000")

    if __name__=="__main__":
        options = Job.Runner.getDefaultOptions("./jobstore")
        options.logLevel = "INFO"
        Job.Runner.startToil(j1, options)

But this was very slow. How are inputs normally provided to toil scripts so that you have just 1 job definition (and no children), but have the system run the job on each of your inputs?

**Comment by jvivian** [comment]
Hi Sendu, thank you for your interest in Toil.

Toil supports _dynamic job creation_ through the use of `job.addChildJobFn`.  

So to adjust your example:

```
from toil.job import Job

def start(job):
    for i in range(10,000):
        message = 'echo ' + str(i + 1)
	job.addChildJobFn(message)

		
def echo(job, message, memory="10M", cores=1, disk="10M"):
    job.fileStore.logToMaster("%s" % message)
	
	
if __name__=="__main__":
    options = Job.Runner.getDefaultOptions("./jobstore")
    options.logLevel = "INFO"
    Job.Runner.startToil(start, options)
```

I recommend taking a look at the [toil-scripts](https://github.com/BD2KGenomics/toil-scripts) repository for some non-trivial use cases which will show you how our group implements Toil in pipelines.

https://gitter.im/bd2k-genomics-toil/Lobby is our channel for discussing Toil. 

Please re-open this issue if you feel your question was not addressed.

**Comment by sb10** [comment]
Hi, thanks for the suggestion, but I couldn't get your code to run without error 'assert self._batchSystem is not None'.

I tried this:

    from toil.job import Job

    def start(job):
        for i in range(10,000):
            message = 'echo ' + str(i + 1)
            job.addChildJobFn(echo, message)


    def echo(job, message, memory="10M", cores=1, disk="10M"):
        job.fileStore.logToMaster("%s" % message)


    if __name__=="__main__":
        parser = Job.Runner.getDefaultArgumentParser()
        options = parser.parse_args()
        Job.Runner.startToil(Job.wrapJobFn(start), options)

And while it runs to completion, it doesn't actually do the work (1 job, no echos).

Beyond the specifics of this example though, my question was if this was generally the right approach for running lots of commands? Is the optimal thing to do to end up calling addChildJobFn() lots of times in your script, one way or another?

And how long would you expect a script like this to take on a 24core machine? I think I'm doing something wrong, because it is taking >7hrs on my initial version of the script and still hasn't finished.
