### ISSUE TITLE
Add ability to provision static cluster with AWS provisioner

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#1383]
Right now the provisioner is only capable of autoscaling. The launch-cluster command should have options to spin up worker nodes as well. Ideally would include the addition of a grow-cluster command as well to add workers to an existing cluster

**Comment by cket** [comment]
This feature should include tests in awsProvisionerTest.py similar to the CGCloud provisioner's  static cluster integration tests.

**Comment by jessebrennan** [comment]
@natanlao Are you working on this? Can I take this over?

**Comment by natanlao** [comment]
Sure, feel free.

**Comment by jessebrennan** [comment]
@natanlao I couldn't find a branch for it. Do you have one locally?

**Comment by natanlao** [comment]
No - I was assigned to this last year, but didn't have enough time to start
working on it.
