### ISSUE TITLE
Move Docker call functions in Toil-lib into Toil

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/toil#1387]
See https://github.com/BD2KGenomics/toil-lib/blob/master/src/toil_lib/programs.py

Proposal is that docker_call function (and necessary functions) moves to src/toil/lib/docker.py

**Comment by benedictpaten** [comment]
Note, this needs a synched PR to remove from toil-lib.

**Comment by jvivian** [comment]
> Note, this needs a synched PR to remove from toil-lib.

and toil-scripts and toil-rnaseq

**Comment by benedictpaten** [comment]
@jvivian do you want to take this on? I figure I would take on the testing.

**Comment by benedictpaten** [comment]
Thanks @jvivian
