### ISSUE TITLE
Documentation for docker_call

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/toil#1390]
In addition to function docstring, we need information on using docker_call and creating pipelines with docker containers in the core toil docks.

**Comment by benedictpaten** [comment]
Depends on #1387

**Comment by benedictpaten** [comment]
@almussel I assign this to you, and assume you will refactor #1265 to do this? Should be quick.

**Comment by almussel** [comment]
@benedictpaten Yes, sounds good!
