### ISSUE TITLE
toilStatus broken by ToilState changes

### ISSUE THREAD

**Issue by adderan** [BD2KGenomics/toil#1425]
toilStatus is broken due to this line, which concatenates a list of jobstore IDs with a list of JobGraph instances:

https://github.com/BD2KGenomics/toil/blob/bbe8ead0ea7dd74dec3decf60cf5cab3a108a1cf/src/toil/utils/toilStatus.py#L87

**Comment by cket** [comment]
In trying to replicate this I'm also seeing 'NoSuchJobExceptions' when trying to load job's descendants. Running jobStore.clean() before building state should fix this, but I'm not sure if it's safe to clean a jobstore currently being written to by a workflow.
