### ISSUE TITLE
Documentation table of contents should not be vendored

### ISSUE THREAD

**Issue by natanlao** [BD2KGenomics/toil#1447]
Vendored `sphinxcontrib.fulltoc` can be replaced with an explicitly specified `requirements.txt` in readthedocs

**Comment by jessebrennan** [comment]
This is a valid option but Hannes asked for it to be vendored because a
requirements.txt file sets a bad trend for specifying what may be required
for compiling docs.

Either way works.

**Comment by natanlao** [comment]
I cede to The Word of Hannes
