### ISSUE TITLE
jobStore.importFile returns a string not a fileStoreID

### ISSUE THREAD

**Issue by ArtRand** [BD2KGenomics/toil#1453]
Is this intentional? It means that if you use the importFIle method then pass the result to a job and invoke the .size method (for resource allocation), you get an error...

**Comment by jessebrennan** [comment]
@cket this is an easy fix, but I need confirmation. Is this intentional? Will changing this break any existing code?

**Comment by cket** [comment]
@jessebrennan this isn't intentional, if it breaks existing code then that also needs to be fixed

**Comment by arkal** [comment]
@ifiddes also reported this to me a few days ago. It's not intentional and might not be an easy fix for non-fileJobStore implementations for importFile. My temp fix for a file that exists on the same machine was
```
from toil.fileStore import fileID
x = FileID.forPath(toil.importFile('file:///path/to/file')
```
This won't work as well for something on s3 but you could find a similar hack

**Comment by ArtRand** [comment]
I have a similar hack that works for S3 and local jobStores:
https://github.com/ArtRand/marginAlign/blob/toil_dev_signal/src/margin/toil/localFileManager.py#L145
 Ingestion of files with .importFIle and .exportFile can be a little dodgy in my experience (i.e. works sometimes).
