### ISSUE TITLE
S3 multipart uploader crashed for large file

### ISSUE THREAD

**Issue by glennhickey** [BD2KGenomics/toil#1469]
I tried to use the AWS jobStore's exportFile() to export a 30G file to an S3 bucket.  Got this error (same code worked for smaller files)

https://github.com/BD2KGenomics/toil-vg/issues/110#issuecomment-276095314

**Comment by glennhickey** [comment]
Note: boto3 has an API to do multipart uploads robustly in one call.

**Comment by joelarmstrong** [comment]
If I recall correctly toil actually uses boto's multipart upload. It looks from your stack trace like this is a problem with the simpledb part that's needed to make the job store strongly consistent.

**Comment by glennhickey** [comment]
I was trying to export an arbitrary file from the job to an S3 store inside
the job.  Perhaps that's an abuse of exportFile.  I blamed it on multipart
because it was only crashing while uploading huge files.  My apologies if
that's not the issue at heart -- I didn't really read the toil internals
too closely.

Do you have any recommendations on how to copy a file from, say, a
temporary work dir within a toil job to an arbitrary output store?  There's
code in toil_vg to do this (IOStore class, which was inherited from Adam a
while back), but I was hoping to replace it with Toil code (as IOStore
didn't support multipart uploads).  I want to checkpoint certain
intermediate files during the workflow without waiting for toil to finish
running (when I can get them with a toil.export).

Anyway, I ended up adding multipart support to IOStore in the meantime very
simply using boto3, hence my API comment.  Toil indeed uses the boto but
still takes dozens of lines of finicky looking code.  boto3 gives a higher
level API to do it in a one-liner.

https://github.com/glennhickey/toil-vg/blob/issues/54-refactor-toillib/src/toil_vg/iostore.py#L636

As an AWS newbie, it was appealing to me, but if the current version aint'
broke....

**Comment by joelarmstrong** [comment]
Well, the current version seems to be broke. I just meant, given where it failed, it looks like the multipart upload part actually technically *worked*, or would have worked, but it failed because of metadata issues.

(Toil devs--is the simpledb consistency stuff even needed now, given that file updates aren't allowed anymore? I think S3 has read-after-creation consistency.)

Do you have a version of the code that failed that you can link to? I'm interested in getting this tracked down, because I want to do exactly the same type of file-checkpointing thing for Cactus.

**Comment by cket** [comment]
IIRC we still need SDB since job files can still be updated. An S3-only job store might be possible, we probably won't be exploring that in the near future though.

I'm also interested in the code that caused this error, hopefully the bug isn't too hard to track down.

**Comment by glennhickey** [comment]
Code's here
https://github.com/glennhickey/toil-vg/blob/issues/110-fix-iostore/src/toil_vg/vg_common.py#L264-L270

Was run on a 30G local file that was written to the job store a few lines
above that link.   This code worked fine for smaller files (tried about 3G
successfully I think).  The sleep call is a bit hokey but was necessary
(and maybe related to my error?).  Run on toil 3.5.0a1.dev251 on an
r3.8xlarge cluster in mesos mode with --workDir on an EBS volume.

But yeah, a simple, standard way for checkpointing intermediate files would
be extremely helpful.

**Comment by cket** [comment]
Thanks, I'll look into this. Out of curiosity, why are you checkpointing files?

**Comment by cket** [comment]
Another thought - you aren't using `--disableCaching` are you? With caching enabled writeGlobalFile actually just queues the upload, the actual upload is asynchronous. I don't think there is any logic to consolidate caching with the imprt/exportFile methods, so that code probably works when the upload finishes in < 10 seconds.

**Comment by glennhickey** [comment]
Never heard of --disableCaching and wasn't using it.  Looks like that may
be the key to my problems.  Will try it out, thanks.

For checkpointing, it's been invaluable for debugging.  If some subprocess
fails deep in a pipeline, it's nice to quickly get at the intermediate
files to, say, rerun just the failing command by hand or in gdb.  Just
looking at the files can be revealing at times.

Another example from toil-vg, just as an end user:  Launching the whole
pipeline generates and index (couple of days), then maps to it (another
day), then calls variants etc.  If/whensomething catastrophic happens in
the mapping, I'd still like my index to be in the output store.  Maybe I
want to re-use it with a completely different set of mapping parameters and
input, or a fixed pipeline.

Maybe these files lurk hidden in the jobstore somewhere, but I can never
find them simply and reliably.  I think for my second example, the average
user would rather have the option to just get the files sent to the output
store as they're ready.
