### ISSUE TITLE
Containerize: RSEM

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil#147]

**Comment by jvivian** [comment]
Only worry about creating a runtime container for:  rsem-calculate-expression

**Comment by AashJ** [comment]
RSEM container pushed to github repository

**Comment by jvivian** [comment]
My docker build of the **build** image fails at the `wget` step.  I'm not sure why it doesn't work on my machine when it worked on yours, so we'll figure out if it's my machine or the problem can be replicated on another machine.

**Comment by jvivian** [comment]
So I didn't find out until I tried to run the tool, but the main binary (rsem-calculate-expression) calls other binaries in the rsem root directory.  So the correct installation method (and a convenience since it avoids us having one runtime container per binary) is to add the rsem directory to the image's path (use ENV).   I think that means you should put rsem root dir in opt/cgl-docker-lib and then update the PATH of the image to have /opt/cgl-docker-lib/rsem_dir on the PATH.   The entry point should still be rsem-calculate-expression.

**Comment by jvivian** [comment]
**Makefile**
Version:  MuTect is also 1.1.7 so I'm assuming this needs to be updated
head -> HEAD (git rev-parse HEAD)

**Runtime**
There is no need to separate out the .pm script and rsem-calculate-expression.  Just copy the entire RSEM folder over to to the runtime container and add it to opt/cgl-docker-lib.  Then put this on your path
`ENV PATH /opt/cgl-docker-lib/RSEM:${PATH}`

**Comment by hannes-ucsc** [comment]
This issue was moved to BD2KGenomics/cgl-docker-lib#8
