### ISSUE TITLE
 Job.wrapJobFn(), addChildJobFn(), etc. set preemptable to False by default

### ISSUE THREAD

**Issue by glennhickey** [BD2KGenomics/toil#1526]
Is this by design?  Docs for the Job class seem to say the default should be None.  As it stands, I need to pass preemptable=True to every single job invocation to get my script running on the Spot market.  What's the harm in having this on by default?

**Comment by cket** [comment]
You can use the argument `--defaultPreemptable` to enable this behavior

**Comment by glennhickey** [comment]
Aha, thanks!  Somehow missed that option -- works fine.
