### ISSUE TITLE
Add option to disable strict CWL evaluation

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#1527]
@chapmanb any opinions on this? It seems like it would be helpful to be able to control this in CWLToil

**Comment by chapmanb** [comment]
CJ -- I don't know how to do this but if it's helpful for some use case it makes sense to explore. What cases are you running into where the CWL fails evaluation but will still run correctly that we want to enable?

**Comment by cket** [comment]
I was given a CWL workflow that raised the following error:
```
Object `test.cwl` is not valid because tried `CommandLineTool` but 
unrecognized extension field xxxx and strict is True.  Did you include a $schemas section?
```
When I changed CWLToil to use strict=False everything worked OK

**Comment by chapmanb** [comment]
That's totally fine with me, I don't understand strict well enough to know any consequences but it makes sense to expose it as an option if it'll help run CWL workflows that are failing otherwise. Thanks for this.

**Comment by mr-c** [comment]
@cket I would be happy to help you and your user diagnose that error over at https://www.biostars.org/t/cwl using the `cwl` tag

**Comment by cket** [comment]
@mr-c thanks for the resource, I will keep it in mind! In this case the error is very helpful so I believe I have the solution already
