### ISSUE TITLE
Mesos batchSystem is O(n log n) in the number of job types per request per offer batch

### ISSUE THREAD

**Issue by joelarmstrong** [BD2KGenomics/toil#1531]
The mesos BatchSystem in Toil sorts its queued job "types" (i.e. resource requirements) before going through the received offers and assigning jobs to be issued. This means responding to an offer batch is O(n log n) in the number of job types, if I'm reading the method correctly. Under normal conditions this is totally fine, but when resource requirements are dynamically assigned, say based on a multiple of the input file size, there can be tens of thousands of very slightly different job types, causing the leader to slow to a crawl and the workers to be under-utilized.

This is pretty easy to solve from our end: we created a thin layer over Toil.Job that rounds all resource requirements up to the next 100MB interval. So our problem is solved, but in the interest of making sure this doesn't catch anyone else by surprise, here are a few options off the top of my head, any/all/none of these could be applied:

- Document this catch in the docs for the Mesos batch system
- Apply some rounding of resource requirements within toil itself
- (way more work) Keep the queued job types in sorted order in the first place, and use binary search to find the first job type that would fit into each offer. Maybe this would require multiple sorted lists?

**Comment by cket** [comment]
I'm leaning towards implementing suggestions 2 and 3 and taking advantage of https://docs.python.org/2/library/bisect.html#module-bisect if possible.

**Comment by joelarmstrong** [comment]
Cool! I didn't even know that module existed. Let me know if you want any help testing or anything, I occasionally still get high CPU usage on the leader (though it's never completely maxed out anymore).

**Comment by cket** [comment]
Looking deeper, responding to offers is actually a lot more expensive than the sorting step.
 
N = jobs issued but not running
M = number of offers
R = jobs to run on the given offer

I believe we are currently O(N * R) to respond to **a single offer**, for a total of O(M * N * R)

In other words, very bad. Luckily, it looks like this is easily fixable.
