### ISSUE TITLE
cwl failure

### ISSUE THREAD

**Issue by osallou** [BD2KGenomics/toil#1559]
Hi,
I tried to test example cwl but it fails. I installed extra requirements but I have error:

    (venv) osallou@tifenn~/Development/NOSAVE/go-docker/toil/toil ((releases/3.5.2)) $ cwltoil ./src/toil/test/cwl/revsort.cwl ../test.txt 
    tifenn 2017-03-13 11:34:25,655 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
    Resolved './src/toil/test/cwl/revsort.cwl' to 'file:///home/osallou/Development/NOSAVE/go-docker/toil/toil/src/toil/test/cwl/revsort.cwl'
    tifenn 2017-03-13 11:34:25,656 MainThread INFO cwltool: Resolved './src/toil/test/cwl/revsort.cwl' to 'file:///home/osallou/Development/NOSAVE/go-docker/toil/toil/src/toil/test/cwl/revsort.cwl'
    Traceback (most recent call last):
      File "/home/osallou/Development/NOSAVE/go-docker/toil/venv/bin/cwltoil", line 11, in <module>
    load_entry_point('toil', 'console_scripts', 'cwltoil')()
      File "/home/osallou/Development/NOSAVE/go-docker/toil/toil/src/toil/cwl/cwltoil.py", line 669, in main
    cwltool.builder.adjustDirObjs(job, unsupportedInputCheck)
    AttributeError: 'module' object has no attribute 'adjustDirObjs'

I installed cwltool==1.0.20170217172322

If I install cwltool==1.0.20161221171240 as per setup.py I have error:

pkg_resources.VersionConflict: (cwltool 1.0.20161221171240 (/home/osallou/Development/NOSAVE/go-docker/toil/venv/lib/python2.7/site-packages), Requirement.parse('cwltool==1.0.20170217172322'))

**Comment by andersgs** [comment]
I have the same issue with `toil 3.6`. This does not seem to be a problem in `toil 3.5` (I haven't tested it, this is just based on looking at the code). 

It seems `adjustDirObjs` is a function in `cwtools.pathmapper` not `cwtools.builder`. 

Anders.

**Comment by andersgs** [comment]
@osallou pip uninstall `cwtool` `cwtest`and `toil`, and then install toil again with:

`pip install toil[cwl]`

It should then work.

A.
