### ISSUE TITLE
effectiveRequirements and PromisedRequirement are not explained well in the documentation

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#1576]
What are they? How do I effectively use them?

The best I could find is this badly-formatted example:

http://toil.readthedocs.io/en/releases-3.6.x/toilAPI.html?#toil.job.PromisedRequirement.__init__

But is there a way to involve the size of a file in the FileStore? Or values coming from multiple jobs?

And is there a way to attach the requirement determination logic to the job being scheduled, somehow, and not the job scheduling it?

**Comment by cket** [comment]
Thanks for pointing this out, I'll fix this in #1574

**Comment by cket** [comment]
Hopefully 85c902f answers your questions, let me know if it doesn't
