### ISSUE TITLE
"beta" scaler parameter has never done anything

### ISSUE THREAD

**Issue by joelarmstrong** [BD2KGenomics/toil#1584]
This line:

```python
# Use inertia parameter to stop small fluctuations
if estimatedNodes <= self.totalNodes * self.scaler.config.betaInertia <= estimatedNodes:
```

is obviously not what is intended (it reduces to `estimatedNodes == self.totalNodes * self.scaler.config.betaInertia`), but it's had this wrong behavior ever since @benedictpaten drafted it. It even got refactored, preserving the wrong behavior perfectly but with more Pythonic style!

What's intended is definitely something like:

```
delta = self.totalNodes * self.scaler.config.betaInertia
if self.totalNodes - delta <= estimatedNodes <= self.totalNodes + delta:
```

**Comment by benedictpaten** [comment]
Oops...
