### ISSUE TITLE
Checkpoint jobs are considered "totally failed" after a successful restart

### ISSUE THREAD

**Issue by joelarmstrong** [BD2KGenomics/toil#1598]
I can consistently get failures if I do the following:
1. Run a workflow containing a checkpointed subtree with a retry count of 0, wait for the workflow to get to the checkpointed subtree, and kill the workflow (causing some job failures in the checkpointed subtree)
2. Restart the workflow

On step 2, the workflow completes the checkpointed subtree fine, but then bails out because it considers the checkpointed job to be totally failed. But restarting the workflow after that works fine, and runs to completion.

If it matters, the checkpointed job in question has an associated service. I think this is probably something wrong with the "cleanup" of the jobStore when resuming a workflow.

**Comment by benedictpaten** [comment]
You can assign to me - this is definitely my bug.

**Comment by joelarmstrong** [comment]
Well, regardless of who it's assigned to, I have a minimal example which should make things a bit easier. That minimal example actually revealed another bug: it looks like checkpointed subtrees are restarted even if the retry count is set to zero. But obviously that's a little less serious.

@cket, would it be make sense if I made a PR for the unit test I have that reproduces this, maybe marking it xfail? I think the bug(s) are probably easy to find given a reproducible example, but I don't think I'll have time to get around to fixing it for a while, since it's not really a blocker.

**Comment by cket** [comment]
A PR with a unit test would be great! You don't have to mark it expected fail since we will want it to be passing before we merge it in.

**Comment by joelarmstrong** [comment]
I went ahead and fixed this (hopefully correctly), because it was about to cost us a few hundred otherwise by needlessly restarting a successful mammals run.

**Comment by benedictpaten** [comment]
@joelarmstrong  We can close this, right? Looks like your pr was committed.

**Comment by joelarmstrong** [comment]
It hasn't been merged yet, my PR has a bug where a checkpoint can never run out of retries. The fix is simple, but I haven't gotten around to it yet.
