### ISSUE TITLE
dockerCall isn't going to work with subprocess.PIPE

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#1642]
There's no return here:

https://github.com/BD2KGenomics/toil/blob/bfb63c9c85ae311945d61be2e1fa6e7717f05522/src/toil/lib/docker.py#L55

So there's no way to get the subprocess process out of `dockerCall`, so even if you tell it to send output to `subprocess.PIPE` you won;t be able to get ahold of the pipe to read from it.

**Comment by joelarmstrong** [comment]
I think you're meant to use `dockerCheckOutput` in that situation rather than `dockerCall`. That returns the stdout as a string.

(But I don't know how you'd get stderr.)

**Comment by adamnovak** [comment]
I'm really looking for a pipe and not a string, because I'm planning to push many gigabytes of output through it.

I'd also need @cmarkello and @glennhickey 's wrappers that I'm using to allow you to start up a Docker call and not wait for it to run to completion, so maybe for now I will write to disk.
