### ISSUE TITLE
`job.addChild().encapsulate` doesn't work

### ISSUE THREAD

**Issue by arkal** [BD2KGenomics/toil#1643]
A.addChild(B).encapsulate creates the relationship between jobs A and B before encapsulating B, thereby causing the encapsulated version of B to have 2 parents with unique roots (the original parent, and the synthetic root for the encapsulation subgraph) Adding a relationship between the synthetic encapsulating parent and the original parent fixes this (the if block in the snippet).
```
    def __init__(self, job):
        """
        :param toil.job.Job job: the job to encapsulate.
        """
        # Giving the root of the subgraph the same resources as the first job in the subgraph.
        Job.__init__(self, **job._requirements)
        if job._directPredecessors:
            for job_ in job._directPredecessors:
                job_.addChild(self)
        self.encapsulatedJob = job
        Job.addChild(self, job)
        # Use small resource requirements for dummy Job instance.
        self.encapsulatedFollowOn = Job(disk='1M', memory='32M', cores=0.1)
        Job.addFollowOn(self, self.encapsulatedFollowOn)
```

**Comment by ejacox** [comment]
Would it be clearer and cleaner to allow only graphs to be encapsulated? That is, only jobs with no parents. In the above example, A.addChild(B), would give an error, and would need to be done in two steps: 
```python
B'=B.encapsultate()
A.addChild(B')
```

**Comment by arkal** [comment]
Well the alternative is to do
```
B = job.wrapJobFn().encapsulate()
A.addChild(B)
```

I would be fine if `A.addChild(B).encapsulate()` explicitly raised an error saying that syntax is incorrect.
