### ISSUE TITLE
Increase default deadlock wait time

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/toil#1648]
Currently, the default deadlock wait time is [one minute](https://github.com/BD2KGenomics/toil/blob/master/src/toil/common.py#L97). This can cause spurious deadlock failures (e.g., https://github.com/BD2KGenomics/toil-lib/pull/89) if the service jobs that are deadlocking have to pull down large containers/resources. I'd suggest bumping this to 2.5–5 minutes, esp. since most jobs that we are running in Toil are relatively long lived.

**Comment by cket** [comment]
@fnothaft in the current code we only start counting against the wait time after all the issued services have started successfully. I think the only way we can mistakenly deadlock if it then it takes > 1 minute for the leader to schedule another successor from the service's parent job. 

The behavior you're describing is consistent with the old deadlock check (which is in Toil 3.5, which the Toil-lib PR is running). Did you try running the Toil-lib test with a version of Toil with the deadlock fix? I believe @joelarmstrong fixed that race so I'm hoping that it would prevent that failure. 

I don't think we are likely run into situations where it would take > 1 minute to schedule a job, but it also doesn't hurt to be safe by increasing the timeout anyway.

**Comment by fnothaft** [comment]
Hmmm, let me retest against the latest version of Toil.

**Comment by fnothaft** [comment]
Hi @cket! You were correct about this. I've updated https://github.com/BD2KGenomics/toil-lib/pull/89 to eliminate the deadlock timeout bump, and will close my PR.
