### ISSUE TITLE
Is --cleanWorkdir=onSuccess available for cwltoil?

### ISSUE THREAD

**Issue by brainstorm** [BD2KGenomics/toil#1667]
```
'CWLWorkflow' C/q/jobQn0554    INFO:toil.worker:Worker log can be found at /home/005/rg3930/dev/test_bcbio_cwl/cwltoil_work/toil-631282a7-9f7e-428f-aa0f-ac769d6dbb27/tmpcgS1HA. 


Set --cleanWorkDir to retain this log
```

Shouldn't this flag be called `--keepWorkDir` if the intended effect is to keep the logs?

**Comment by cket** [comment]
There are multiple options for this parameter: `--cleanWorkDir=always`, `never`, `onSuccess` and `onFailure`. The default is `always` and you can use the other options so only logs you want will be retained. `onSuccess` means that the work directory will only be removed when the job is successful and is typically the most useful debugging option.

**Comment by brainstorm** [comment]
Thanks @cket for the hints! Is it possible that `cwltoil` does not support it or am I passing it wrong on the cmdline?:

```
cwltoil: error: unrecognized arguments: --cleanWorkdir=onSuccess
```

Currently using the following cmdline from [test_bcbio_cwl](https://github.com/bcbio/test_bcbio_cwl):

```
bcbio_vm.py cwlrun toil --no-container run_info-cwl-workflow -- --cleanWorkdir=onSuccess 
--batchSystem torque --logLevel DEBUG
```

**Comment by jessebrennan** [comment]
@brainstorm what happens if you try `--cleanWorkDir onSuccess` instead?

**Comment by brainstorm** [comment]
Thanks for the feedback @jessebrennan! For each run above I've `rm -rf cwltoil_work *.log`, so all intermediate files and jobstore should be gone. I'm giving it a try with that flag now!

**Comment by brainstorm** [comment]
That seems to work, unfortunately I'm stuck with issue https://github.com/BD2KGenomics/toil/issues/1772 now.

Closing this one though.
