### ISSUE TITLE
Import from Azure Storage to Azure JobStore needlessly slow

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#1671]
I'm trying to import some data from Azure Storage, where it lives, to a job store also in Azure Storage on the same account, running on a node on Azure.

Some of my files are a bit big, and my run has been sitting here for a couple of minutes:

```
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): hgvmeast.blob.core.windows.net
INFO:plan:Imported base VG wasb://hgvm-builds@hgvmeast.blob.core.windows.net/2017-05-02/hgvm/hgvm.vg as 6aa6fa2b_1fea_4256_8e5c_abe558601d56
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): hgvmeast.blob.core.windows.net
```

It looks to me like Toil is actually downloading and then re-uploading these files. What it should be doing is using Azure-side copy operations to copy the blobs between containers, without them having to stream over the network to the Master and back. If I had to import a bunch of files, it would be very slow to wait to download and upload them all one at a time.

(Can Toil handle simultaneous imports with e.g. `multiprocessing`?)

**Comment by cricketsloan** [comment]
Azure has been re-written
