### ISSUE TITLE
Job chaining breaks service termination timing

### ISSUE THREAD

**Issue by joelarmstrong** [BD2KGenomics/toil#1698]
The docs say:

> The services of a job are started before any of its successors have been run and stopped after all the successors of the job have completed successfully.

But that's not the case if a chained job starts a service. The chaining works by pushing the predecessor's "stack" onto the next job's "stack", basically making the predecessor's successors into successors of the next job. So the job graph as designed by the user is no longer the same graph that's in the job store: the chained job has extra successors. This breaks the timing of service termination.

Consider this example (follow-on edges in red, service edges dotted):
![toil-chaining-issue dot](https://cloud.githubusercontent.com/assets/4723163/26659729/b28afba2-4627-11e7-84c2-fc48da5c7fb2.png)

`chainEnd` can be chained to `chainStart` (assuming it has the same CPU, memory, etc requirements). If it's chained, then `service` will stick around not just through `job1` and `job2`, but also `job3` and `job4`. This isn't great, because if the service is, say, a very large database, it will hang around on a non-preemptable server costing lots of money for no reason.

I fixed this on my fork by just disabling chaining entirely--I've never been too convinced of its value and I'm not sure there aren't other edge cases like this still remaining to be found. I don't think it's feasible to shoehorn a fix into the chaining code as written, because it's undecidable to figure out whether the next job will run a service or not.

**Comment by jsmedmar** [comment]
I agree with @joelarmstrong, this also a problem in LSF when the logic in the batchSystem includes wall times (e.g. short running jobs accessing a short queue preference)

**Comment by jsmedmar** [comment]
@DailyDreaming, do think its possible we can add a command line option to disable job chaining? In our case `LSF` kills jobs that take more than 2 hours (given that you said it was going to be a short job). As such, when toil chain jobs, things that were expected to last less than 2 hours last longer.

**Comment by DailyDreaming** [comment]
That seems very reasonable. @joelarmstrong just spoke with me about this and he's better situated to help on this front. He's been generously giving us his time in sharing some of the fixes he's had to patch in to toil for his own projects and I think he'll be adding this.
