### ISSUE TITLE
Credentials storage is confusing

### ISSUE THREAD

**Issue by natanlao** [BD2KGenomics/toil#1701]
I can count at least three files that Toil looks at for provisioner credentials:
* `.boto` For AWS and sometimes for Google Cloud.
* `.toilAzureCredentials` For Azure.
* `.aws/credentials` For AWS, which should be used instead of `.boto` now.

This should be standardized and noted in the documentation. Sections of the documentation referencing any of these files should also be updated to reflect new convention.

**Comment by ejacox** [comment]
Addressed in #1752
