### ISSUE TITLE
Toil intro page fails to brag about it's most important feature

### ISSUE THREAD

**Issue by diekhans** [BD2KGenomics/toil#1712]
https://toil.readthedocs.io/en/releases-3.7.x/

fails to mention it's most important feature:  you can program workflows in an excellent Turning-complete language.

Instead, it talks about CWL, which is fine for simple workflows, but is not what Toil is all about.  The fact that it could easily implement CWL is a fall out of it being programmable in a Turing completely language.  

Don't ignore CWL, but don't lead with it, it's not why Toil is cool.

**Comment by benedictpaten** [comment]
+1 on this. I noticed this too. Just needs a sentence about the Python API,
and doesn't need to knock CWL in any way.

**Comment by ejacox** [comment]
Fixed in #1752
