### ISSUE TITLE
sort.py crashes: sort.py fromhttps://github.com/BD2KGenomics/toil/blob/master/src/toil/test/sort/sort.py

### ISSUE THREAD

**Issue by paul-sanghera** [BD2KGenomics/toil#1717]
Command and Output:
Apples-Air:examples paulsanghera$ python2.7 sort.py --fileToSort ./file_to_sort.txt file:jobStore
Apples-Air 2017-06-15 12:34:26,917 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
Apples-Air 2017-06-15 12:34:26,918 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
Apples-Air 2017-06-15 12:34:26,922 MainThread INFO toil.jobStores.abstractJobStore: The workflow ID is: 'f25f2bc9-b63d-4584-88c3-d6609d6704bc'
Apples-Air 2017-06-15 12:34:26,974 MainThread INFO toil.common: Using the single machine batch system
Apples-Air 2017-06-15 12:34:26,974 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxCores to CPU count of system (4).
Apples-Air 2017-06-15 12:34:26,974 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxMemory to physically available memory (4294967296).
Apples-Air 2017-06-15 12:34:26,976 MainThread INFO toil.common: Created the workflow directory at /var/folders/2t/y0xgs0l51wq34rcx3z1rqwr80000gp/T/toil-f25f2bc9-b63d-4584-88c3-d6609d6704bc
Apples-Air 2017-06-15 12:34:26,976 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxDisk to physically available disk (132000854016).
Apples-Air 2017-06-15 12:34:26,985 MainThread INFO toil.common: No user script to hot-deploy.
Apples-Air 2017-06-15 12:34:26,986 MainThread INFO toil.common: Written the environment for the jobs to the environment file
Apples-Air 2017-06-15 12:34:26,986 MainThread INFO toil.common: Caching all jobs in job store
Apples-Air 2017-06-15 12:34:26,986 MainThread INFO toil.common: 0 jobs downloaded.
Apples-Air 2017-06-15 12:34:26,992 MainThread INFO toil: Running Toil version 3.7.0-73c62d7698bb6f4154d276994df4353ce4d7826b.
Apples-Air 2017-06-15 12:34:26,992 MainThread INFO toil.realtimeLogger: Real-time logging disabled
Apples-Air 2017-06-15 12:34:26,996 MainThread INFO toil.toilState: (Re)building internal scheduler state
Apples-Air 2017-06-15 12:34:26,996 MainThread INFO toil.leader: Found 1 jobs to start and 0 jobs with successors to run
Apples-Air 2017-06-15 12:34:26,996 MainThread INFO toil.leader: Checked batch system has no running jobs and no updated jobs
Apples-Air 2017-06-15 12:34:26,997 MainThread INFO toil.leader: Starting the main loop
Apples-Air 2017-06-15 12:34:26,997 MainThread INFO toil.leader: Issued job 'setup' 0/l/jobFNP5Px with job batch system ID: 0 and cores: 1, disk: 2.0 G, and memory: 1000.0 M
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/toil/fileStore.py", line 1468, in asyncWrite
    raise RuntimeError("The termination flag is set, exiting")
RuntimeError: The termination flag is set, exiting
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/toil/fileStore.py", line 1468, in asyncWrite
    raise RuntimeError("The termination flag is set, exiting")
RuntimeError: The termination flag is set, exiting

Exception RuntimeError: RuntimeError('cannot join current thread',) in <bound method CachingFileStore.__del__ of <toil.fileStore.CachingFileStore object at 0x1103dc5d0>> ignored
Apples-Air 2017-06-15 12:34:29,233 MainThread INFO toil.leader: Job ended successfully: 'setup' 0/l/jobFNP5Px
Apples-Air 2017-06-15 12:34:29,236 MainThread WARNING toil.leader: The job seems to have left a log file, indicating failure: 'setup' 0/l/jobFNP5Px
Apples-Air 2017-06-15 12:34:29,236 MainThread WARNING toil.leader: 0/l/jobFNP5Px    ---TOIL WORKER OUTPUT LOG---
Apples-Air 2017-06-15 12:34:29,236 MainThread WARNING toil.leader: 0/l/jobFNP5Px    INFO:toil:Running Toil version 3.7.0-73c62d7698bb6f4154d276994df4353ce4d7826b.
Apples-Air 2017-06-15 12:34:29,236 MainThread WARNING toil.leader: 0/l/jobFNP5Px    WARNING:toil.resource:Can't find resource for leader path '/Users/paulsanghera/A-A-UCSC-Courses/A-A-Research/A-Toil/examples'
Apples-Air 2017-06-15 12:34:29,237 MainThread WARNING toil.leader: 0/l/jobFNP5Px    WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/Users/paulsanghera/A-A-UCSC-Courses/A-A-Research/A-Toil/examples', name='sort', fromVirtualEnv=False)
Apples-Air 2017-06-15 12:34:29,237 MainThread WARNING toil.leader: 0/l/jobFNP5Px    INFO:toil.fileStore:Starting job ('setup' 0/l/jobFNP5Px) with ID (12dac4474744867aff6dab9541a2c2823c7b09cb).
Apples-Air 2017-06-15 12:34:29,237 MainThread WARNING toil.leader: 0/l/jobFNP5Px    WARNING:toil.resource:Can't find resource for leader path '/Users/paulsanghera/A-A-UCSC-Courses/A-A-Research/A-Toil/examples'
Apples-Air 2017-06-15 12:34:29,237 MainThread WARNING toil.leader: 0/l/jobFNP5Px    WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/Users/paulsanghera/A-A-UCSC-Courses/A-A-Research/A-Toil/examples', name='sort', fromVirtualEnv=False)
Apples-Air 2017-06-15 12:34:29,238 MainThread WARNING toil.leader: 0/l/jobFNP5Px    Traceback (most recent call last):
Apples-Air 2017-06-15 12:34:29,238 MainThread WARNING toil.leader: 0/l/jobFNP5Px      File "/usr/local/lib/python2.7/site-packages/toil/worker.py", line 340, in main
Apples-Air 2017-06-15 12:34:29,238 MainThread WARNING toil.leader: 0/l/jobFNP5Px        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
Apples-Air 2017-06-15 12:34:29,238 MainThread WARNING toil.leader: 0/l/jobFNP5Px      File "/usr/local/lib/python2.7/site-packages/toil/job.py", line 1288, in _runner
Apples-Air 2017-06-15 12:34:29,238 MainThread WARNING toil.leader: 0/l/jobFNP5Px        returnValues = self._run(jobGraph, fileStore)
Apples-Air 2017-06-15 12:34:29,239 MainThread WARNING toil.leader: 0/l/jobFNP5Px      File "/usr/local/lib/python2.7/site-packages/toil/job.py", line 1233, in _run
Apples-Air 2017-06-15 12:34:29,239 MainThread WARNING toil.leader: 0/l/jobFNP5Px        return self.run(fileStore)
Apples-Air 2017-06-15 12:34:29,239 MainThread WARNING toil.leader: 0/l/jobFNP5Px      File "/usr/local/lib/python2.7/site-packages/toil/job.py", line 1405, in run
Apples-Air 2017-06-15 12:34:29,239 MainThread WARNING toil.leader: 0/l/jobFNP5Px        rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
Apples-Air 2017-06-15 12:34:29,239 MainThread WARNING toil.leader: 0/l/jobFNP5Px      File "/Users/paulsanghera/A-A-UCSC-Courses/A-A-Research/A-Toil/examples/sort.py", line 39, in setup
Apples-Air 2017-06-15 12:34:29,239 MainThread WARNING toil.leader: 0/l/jobFNP5Px        inputFileStoreID = job.fileStore.writeGlobalFile(inputFile, True)
Apples-Air 2017-06-15 12:34:29,239 MainThread WARNING toil.leader: 0/l/jobFNP5Px      File "/usr/local/lib/python2.7/site-packages/toil/fileStore.py", line 548, in writeGlobalFile
Apples-Air 2017-06-15 12:34:29,240 MainThread WARNING toil.leader: 0/l/jobFNP5Px        os.link(absLocalFileName, self.jobStore._getAbsPath(jobStoreFileID))
Apples-Air 2017-06-15 12:34:29,240 MainThread WARNING toil.leader: 0/l/jobFNP5Px    OSError: [Errno 2] No such file or directory
Apples-Air 2017-06-15 12:34:29,240 MainThread WARNING toil.leader: 0/l/jobFNP5Px    ERROR:toil.worker:Exiting the worker because of a failed job on host Apples-Air
Apples-Air 2017-06-15 12:34:29,240 MainThread WARNING toil.leader: 0/l/jobFNP5Px    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'setup' 0/l/jobFNP5Px with ID 0/l/jobFNP5Px to 0
Apples-Air 2017-06-15 12:34:29,240 MainThread WARNING toil.leader: 0/l/jobFNP5Px    WARNING:toil.jobGraph:We have increased the default memory of the failed job 'setup' 0/l/jobFNP5Px to 2147483648 bytes
Apples-Air 2017-06-15 12:34:29,241 MainThread WARNING toil.leader: Job 'setup' 0/l/jobFNP5Px with ID 0/l/jobFNP5Px is completely failed
Apples-Air 2017-06-15 12:34:31,244 MainThread INFO toil.leader: No jobs left to run so exiting.
Apples-Air 2017-06-15 12:34:31,244 MainThread INFO toil.leader: Finished the main loop
Apples-Air 2017-06-15 12:34:31,245 MainThread INFO toil.serviceManager: Waiting for service manager thread to finish ...
Apples-Air 2017-06-15 12:34:32,013 MainThread INFO toil.serviceManager: ... finished shutting down the service manager. Took 0.768140077591 seconds
Apples-Air 2017-06-15 12:34:32,013 MainThread INFO toil.statsAndLogging: Waiting for stats and logging collator thread to finish ...
Apples-Air 2017-06-15 12:34:32,049 MainThread INFO toil.statsAndLogging: ... finished collating stats and logs. Took 0.0355849266052 seconds
Apples-Air 2017-06-15 12:34:32,049 MainThread INFO toil.leader: Finished toil run with 1 failed jobs
Apples-Air 2017-06-15 12:34:32,050 MainThread INFO toil.leader: Failed jobs at end of the run: 'setup' 0/l/jobFNP5Px
Traceback (most recent call last):
  File "sort.py", line 189, in <module>
    main()
  File "sort.py", line 186, in main
    memory=sortMemory), options)
  File "/usr/local/lib/python2.7/site-packages/toil/job.py", line 742, in startToil
    return toil.start(job)
  File "/usr/local/lib/python2.7/site-packages/toil/common.py", line 682, in start
    return self._runMainLoop(rootJobGraph)
  File "/usr/local/lib/python2.7/site-packages/toil/common.py", line 991, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/usr/local/lib/python2.7/site-packages/toil/leader.py", line 201, in run
    raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
toil.leader.FailedJobsException: The job store 'file:/Users/paulsanghera/A-A-UCSC-Courses/A-A-Research/A-Toil/examples/jobStore' contains 1 failed jobs: 'setup' 0/l/jobFNP5Px
=========> Failed job 'setup' 0/l/jobFNP5Px 
---TOIL WORKER OUTPUT LOG---
INFO:toil:Running Toil version 3.7.0-73c62d7698bb6f4154d276994df4353ce4d7826b.
WARNING:toil.resource:Can't find resource for leader path '/Users/paulsanghera/A-A-UCSC-Courses/A-A-Research/A-Toil/examples'
WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/Users/paulsanghera/A-A-UCSC-Courses/A-A-Research/A-Toil/examples', name='sort', fromVirtualEnv=False)
INFO:toil.fileStore:Starting job ('setup' 0/l/jobFNP5Px) with ID (12dac4474744867aff6dab9541a2c2823c7b09cb).
WARNING:toil.resource:Can't find resource for leader path '/Users/paulsanghera/A-A-UCSC-Courses/A-A-Research/A-Toil/examples'
WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/Users/paulsanghera/A-A-UCSC-Courses/A-A-Research/A-Toil/examples', name='sort', fromVirtualEnv=False)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/toil/worker.py", line 340, in main
    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
  File "/usr/local/lib/python2.7/site-packages/toil/job.py", line 1288, in _runner
    returnValues = self._run(jobGraph, fileStore)
  File "/usr/local/lib/python2.7/site-packages/toil/job.py", line 1233, in _run
    return self.run(fileStore)
  File "/usr/local/lib/python2.7/site-packages/toil/job.py", line 1405, in run
    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
  File "/Users/paulsanghera/A-A-UCSC-Courses/A-A-Research/A-Toil/examples/sort.py", line 39, in setup
    inputFileStoreID = job.fileStore.writeGlobalFile(inputFile, True)
  File "/usr/local/lib/python2.7/site-packages/toil/fileStore.py", line 548, in writeGlobalFile
    os.link(absLocalFileName, self.jobStore._getAbsPath(jobStoreFileID))
OSError: [Errno 2] No such file or directory
ERROR:toil.worker:Exiting the worker because of a failed job on host Apples-Air
WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'setup' 0/l/jobFNP5Px with ID 0/l/jobFNP5Px to 0
WARNING:toil.jobGraph:We have increased the default memory of the failed job 'setup' 0/l/jobFNP5Px to 2147483648 bytes
<=========

**Comment by arkal** [comment]
Use the absolute path to `--fileToSort`.  Toil jobs are placed into their own sandboxes and </path/to/sandbox>/file_to_sort.txt does not exist.

We can modify sort test to resolve the abspath in a future PR.

**Comment by paul-sanghera** [comment]
You are right, Arjun. Closing this one.
