### ISSUE TITLE
Allow memory requirements to be specified as resource string

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/toil#172]

**Comment by cket** [comment]
What exactly does this mean? Do you mean storage?

**Comment by benedictpaten** [comment]
It is annoying to have to specify everything in bytes. It would be good to be able to specify things in other byte units, e.g. "10GB", "1000MB", etc. I assume

**Comment by benedictpaten** [comment]
(oops, continuing) I assume... this is possible? I think Hannes mentioned a standard module for interpreting such strings.

**Comment by hannes-ucsc** [comment]
This is in bd2k-python-lib

https://github.com/BD2KGenomics/bd2k-python-lib/blob/master/src/bd2k/util/humanize.py

We can either steal it from there or add bd2k-python-lib as a dependency. I'd prefer the latter even though we recently got rid of sonLib. The difference is that bd2k-python-lib is already on PyPI.
