### ISSUE TITLE
Add 'make tests' for running locally.

### ISSUE THREAD

**Issue by ejacox** [BD2KGenomics/toil#1741]
'make test' and 'make integration_test' are configured to run under Jenkins. 

New targets should be added to run tests locally. They should call pytest directly, skipping the docker target and calling run_tests.py.

Consider renaming the existing tests to 'jenkins_<test_name>'.

**Comment by jessebrennan** [comment]
I have some improvements for the local testing experience in the works. Currently however, `make test` _does_ call run_tests.py directly. 

I'm confused on which `make` targets Jenkins actually runs. I cannot find where the [environment variable `make_targets`](https://github.com/BD2KGenomics/toil/blob/master/jenkins.sh#L37) is defined for Jenkins. 

Currently I suspect that Jenkins uses just `test_parallel` and `test_integration`, but I'm not sure how to confirm.

@ejacox do you have any ideas?

**Comment by ejacox** [comment]
Would it be simpler to call the tests directory, rather than through run_tests.py?

Jenkins toil-pull-requests calls the following make targets:
check_cpickle docs clean_docs test_parallel check_clean_working_copy

Jenkins toil-pull-request-test-integration calls these make targets:
docs clean_docs integration_test check_clean_working_copy

**Comment by jessebrennan** [comment]
Woops! that was a typo... I mean to say the exact oposite:   Currently however, `make test` **_does not_** call run_tests.py directly. This was actually addressed in an [old PR I found](https://github.com/BD2KGenomics/toil/issues/1284).

I'm editing run_test.py to have a separate option for running the integration tests locally—the main reason being that then we have only one source of what counts as an integration test.

**Comment by jessebrennan** [comment]
I have a working target for running integration tests locally in series. Unfortunately this takes _ages_ to run. There is also an immense amount of output from the tests. @ejacox looking for input.

**Comment by ejacox** [comment]
The motivation for this issue is to be able to run as many tests locally as possible and to get away from using Jenkins to test code under development. 

One issue is how to choose which tests to run. Currently, decorators are used to skip tests that don't have the right environment (e.g. no Azure credentials). One option is to select tests by name, such as all AWS tests.

The other issue is setting up the environment correctly. For example, the current configuration always pushes a docker container before starting the tests. Is this required for some tests? Which ones? Some of the AWS tests fail for me locally, even though I have AWS credentials configured.

We can start with targets useful to us to setup a framework for running sets of tests and expand on it as needed for other uses.

If the Makefile approach isn't working, a python script could be used, too (reusing run_tests.py or creating another).

**Comment by jessebrennan** [comment]
I have looked into the docker issue. We're actually not [the first to find building the docker container a little superfluous](https://github.com/BD2KGenomics/toil/issues/1193). 

The current solution which is basically undocumented—minus a couple comments in the makefile—requires setting `TOIL_DOCKER_REGISTRY` to the empty string. This prevents the docker appliance from being built.

The test(s) that need the docker appliance are marked with `@needs_appliance`. They are skipped if the appliance isn't built.

This all seemed pretty round-about to me so I am adding a new make target to run tests without docker and skip all of the `@needs_appliance` tests.

**Comment by ejacox** [comment]
@jessebrennan I think what the make file is missing is the setup that is done in jenkins.sh.
Jenkins calls this before calling the make targets:
export TOIL_DOCKER_REGISTRY=quay.io/ucsc_cgl
export TOIL_DOCKER_NAME=toil-pr
export docker_registry=$TOIL_DOCKER_REGISTRY # delete once PR #1260 is merged
export docker_base_name=$TOIL_DOCKER_NAME # delete once PR #1260 is merged
. ./jenkins.sh

**Comment by jessebrennan** [comment]
As a side note, it looks like #1260 has been merged, those last two environment variables have been merged, and those two lines can be deleted.
