### ISSUE TITLE
simple cwl example does not print

### ISSUE THREAD

**Issue by DailyDreaming** [BD2KGenomics/toil#1747]
Using cwltoil to run a cwl file for the helloworld example, the echo command does not actually output "Hello World" to the screen, despite stating that it has run successfully.

If one uses cwl-runner instead, this runs successfully and prints "Hello World" to the screen successfully using the same files.

The commands should be run with the two attached files as follows:

cwltoil simple.cwl simple.yml
or
cwl-runner simple.cwl simple.yml

Posted at the request of @jessebrennan.

[simple.zip](https://github.com/BD2KGenomics/toil/files/1132033/simple.zip)

**Comment by tetron** [comment]
The message is going to standard output.  The default behavior of toil seems to be to discard standard output unless there is an error.  Perhaps there should be different default logging behavior?
