### ISSUE TITLE
readFileStream deadlocks when not read through completely

### ISSUE THREAD

**Issue by joelarmstrong** [BD2KGenomics/toil#1748]
I think I was aware of this at one point, but using readFileStream without reading all the way to EOF will totally deadlock the worker process on anything but the file jobStore. This is pretty unintuitive (surely this is one of the only use cases for streaming the file?). It may be especially confusing to new users who aren't used to toil deadlocks.

Unfortunately, it's not easy to fix. The writing thread will be blocked on write, so there's no way to wake it up and tell the writing thread to quit. Python threads can't (safely) be killed from their parents. The thread *should* have dropped the GIL while blocked on the write, so we might barely get away with killing its PID. But I'd suggest adjusting the ReadableThread/WritableThread classes to use processes rather than threads. They already use pipes, so very little would need to change. There would be a bit of added overhead from the extra fork(), but surely that's worth getting rid of some of these GIL nightmares.

**Comment by diekhans** [comment]
Setting thread.daemon to True may solve the deadlock problems:

        self.__thread = threading.Thread(target=self.__reader)
        self.__thread.daemon = True

 http://bugs.python.org/issue21822
 http://code.activestate.com/recipes/496735-workaround-for-missed-sigint-in-multithreaded-prog/

**Comment by joelarmstrong** [comment]
I use thread.daemon all the time, it's really useful, but I don't think it'll solve this problem. The writing thread is stuck on write(), the other thread is stuck on thread.join(). We could possibly send SIGINT to the writing thread, and rely on that to cause an exception, but my Unix-fu is lacking, I don't know if that would always interrupt write(). The man page says:
```
       EINTR  The  call  was interrupted by a signal before any data was writ‐
              ten; see signal(7).
```
so does that imply that write blocks the signal handler from running if it's already written something but is blocked on writing more?

We could attempt to be sane and use timeouts in the writing thread, but we often just delegate to boto or shutil.copyfileobj which don't support timeouts.

**Comment by diekhans** [comment]
Does the read thread close the stream before join()?  this would
cause the write to fail.

**Comment by joelarmstrong** [comment]
d'oh, that's brilliant! I'll try that.
