### ISSUE TITLE
Weird permissions error when using importFile with file jobStore

### ISSUE THREAD

**Issue by jessebrennan** [BD2KGenomics/toil#1755]
I encountered this bug last week, wrote a ticket for it, was about to submit—and then it mysteriously vanished. Well now it's back.

The importFile can change the permissions of the local copy of the file when using the file jobStore This is my best diagnosis although I'm not certain.

When using the file JobStore, [importFile](https://github.com/BD2KGenomics/toil/blob/90bd990f5f0eb2ccc8c2018c244ff43ea2898135/src/toil/jobStores/fileJobStore.py#L165) uses a slight hack/optimization: if the file is being imported from the same disk, instead of copying it, a hard link is made. This shouldn't be a problem except that permissions are stored on the inode.

_THIS_ wouldn't be a problem if not for the fact that somewhere the permissions are changed to read only (I cannot find where in the code).

The code that is causing this error for me is my current version of the [toil-sort-example.py.txt](https://github.com/BD2KGenomics/toil/files/1140489/toil-sort-example.py.txt) (I had to add the .txt so that github would let me upload it) that I was revamping for #1722.

The problem arises from using exportFile because the exporting the file with the same name back to the source directory because we don't have permissions to overwrite it.

It would be awesome if someone else could validate this. by error trace looks like:
>Traceback (most recent call last):
  File "toil-sort-example.py", line 170, in <module>
    main()
  File "toil-sort-example.py", line 165, in main
    toil.exportFile(sorted_file_id, sort_file_url)
  File "/Users/jesse/Documents/genomics/toil/src/toil/common.py", line 900, in exportFile
    self._jobStore.exportFile(jobStoreFileID, dstUrl)
  File "/Users/jesse/Documents/genomics/toil/src/toil/jobStores/abstractJobStore.py", line 327, in exportFile
    self._exportFile(otherCls, jobStoreFileID, dstUrl)
  File "/Users/jesse/Documents/genomics/toil/src/toil/jobStores/fileJobStore.py", line 190, in _exportFile
    shutil.copyfile(self._getAbsPath(jobStoreFileID), self._extractPathFromUrl(url))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/Users/jesse/Documents/genomics/toil/docs/running/file_to_sort.txt'

**Comment by joelarmstrong** [comment]
I can at least point you to where in the code things are changed to be read-only. It's almost certainly in the caching code, either [here](https://github.com/BD2KGenomics/toil/blob/7b1f22ecd3f8aea6d0a86ab56344d7d80bade4ab/src/toil/fileStore.py#L702) or [here](https://github.com/BD2KGenomics/toil/blob/7b1f22ecd3f8aea6d0a86ab56344d7d80bade4ab/src/toil/fileStore.py#L1040).

**Comment by jessebrennan** [comment]
Bingo! Disabling caching makes everything work as expected! Thanks @joelarmstrong for the leads.

**Comment by jessebrennan** [comment]
More details:
- The permissions are modified in the caching fileStore exactly where Joel had indicated [here](https://github.com/BD2KGenomics/toil/blob/7b1f22ecd3f8aea6d0a86ab56344d7d80bade4ab/src/toil/fileStore.py#L702).
- The permissions are only changed if kwarg `cache=False` is set.

The comments here aren't very clear as to why permissions are set to read only. I'm not really sure which way to proceed. Options I see:
- (temporarily?) disable hardlinks when importing files into fileJobStore
- remove the line that sets the permissions to read-only. I'm not really sure what the repercussions would be.
- only remove the line that sets the permissions to read-only _if_ it's a hardlink

The only solution I feel really comfortable with is the first one. For the second two I could use some guidance from someone (@arkal) with some knowledge about how this thing works to know if that would be a safe change.

**Comment by kozbo** [comment]
Feel free to add comments at the bottom

**Comment by arkal** [comment]
We purposely made cached files read-only since they are meant to be accessed simultaneously by multiple jobs

**Comment by jessebrennan** [comment]
Solution after discussion with @arkal: By default, imported files into the jobStore won't be hardlinked. A flag will be added that gives linking as an option and explains that the permissions may change out from under you. This is a little ugly and kind of a pain for users, but it also probably makes the most sense.

**Comment by arkal** [comment]
permissions *will*

**Comment by jessebrennan** [comment]
Well not technically if your file started out read-only ;)

**Comment by arkal** [comment]
Haha *touche*
