### ISSUE TITLE
Jobtree jenkins hasn't been running

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#176]
Hannes emailed me over the weekend saying that a jobtree build hung for about a day before he shut it down. The build hung on the DAG branch, but I think that this hanging has already been fixed on DAG-rebased, so this is not a current issue. 

However, since then Jenkins hasn't been building any new commits, and I don't know whether it was intentionally disabled or it is some sort of bug. This also occurred about the same time DAG-rebased was merged into master.

**Comment by cket** [comment]
I've been running jenkins manually, and it just started building automatically upon push again.

**Comment by hannes-ucsc** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-29796

I fixed this in fork of the Jenkins Git plugin and installed that fork on our instance. Since then Jenkins automatically detected pushes to master and triggered a build.
