### ISSUE TITLE
cwltoil.py fails in resolve_indirect_inner for Workflow if substep is a workflow and some inputs are optional and empty

### ISSUE THREAD

**Issue by liuxf09** [BD2KGenomics/toil#1761]
I have a Workflow job that uses workflow for the substep. If some inputs for the substep are optional and empty, it fails resolve_indirect_inner() in cwltoil.py:

    def resolve_indirect_inner(d):
        if isinstance(d, IndirectDict):
            r = {}
            for k, v in d.items():
                if isinstance(v, MergeInputs):
                    r[k] = v.resolve()
                else:
                    r[k] = v[1][v[0]]
            return r
        else:
            return d

The problem is at Line 103:

             r[k] = v[1][v[0]]

**Comment by ejacox** [comment]
Thank you for this fix @liuxf09
