### ISSUE TITLE
Job.Runner class should probably be deprecated

### ISSUE THREAD

**Issue by jessebrennan** [BD2KGenomics/toil#1764]
`Job.Runner` is a class of static methods the most important of which was `startToil()`. Since `startToil()` is deprecated there isn't a lot of coherence in this class. All of the options/arguments related function (`getDefaultArgumentParser()`, `getDefaultOptions()`, and `addToilOptions()`) could be happily moved somewhere else. Probably just common.

This isn't such a big change, except that it would entail a lot of refactoring because many examples and docs use these methods.

What are other opinions on the matter @ejacox @joelarmstrong @benedictpaten?

**Comment by joelarmstrong** [comment]
I totally agree it should be deprecated, but, since removing it would be a breaking change, I'd like it to stick around until a bump of the major version number.

**Comment by jessebrennan** [comment]
That makes a lot of sense. We could at the very least make them wrappers for their replacements, but keep them around for legacy code.
