### ISSUE TITLE
cwltoil issues on AWS.

### ISSUE THREAD

**Issue by DailyDreaming** [BD2KGenomics/toil#1765]
I opened a t2.xlarge AWS instance and attempted to run hello_world.cwl and md5sum.cwl as per Synapse instructions here:

https://www.synapse.org/#!Synapse:syn9630940
https://www.synapse.org/#!Synapse:syn10167920

These workflows seem to work with cwltool just fine, but not cwltoil.  Each gave different errors (hello_world omitted getting a directory when initially fetching the files; md5sum looks like it allocated too few resources), which are attached.

[hello_world.log.txt](https://github.com/BD2KGenomics/toil/files/1159356/hello_world.log.txt)
[md5sum.log.txt](https://github.com/BD2KGenomics/toil/files/1159357/md5sum.log.txt)

**Comment by ejacox** [comment]
Thank you @DailyDreaming for making a first pass at this. Why are you running them on AWS? These small examples can run locally.

MD5SUM EXAMPLE
There is a problem in dockstore-tool-md5sum.cwl. The outdirMin value is specified in MB (mebibytes actually). It is asking for 512000, so 1/2 a TB. I changed this value to 5 and it ran fine.

See the spec for more details - http://www.commonwl.org/draft-3/CommandLineTool.html#ResourceRequirement.

HELLO_WORLD EXAMPLE
Your error text file is for the results validation. Does that mean that cwltoil ran without a problem?

**Comment by ejacox** [comment]
Toil doesn't have a --non-strict option. I removed the creator field from a few cwl files and things ran fine.

**Comment by DailyDreaming** [comment]
I was told to run Toil on AWS.  We have a checklist and that was one of my tasks.  Running toil locally wasn't on there.

Good catches on the cwl files, it would be nice though if cwltoil could handle these issues the way that cwltool does.  These files are the templates provided for the challenge and since this is meant to be an easy run.  I'll update and run again on AWS to see if it works.

**Comment by ejacox** [comment]
@DailyDreaming are these running now?

**Comment by DailyDreaming** [comment]
Yes, this can be closed.
