### ISSUE TITLE
AWS Install

### ISSUE THREAD

**Issue by jasper1918** [BD2KGenomics/toil#1766]
Im jumping in to using TOIL in aws for the first time and hit this error that confuses me. This happens when I run `toil launch-cluster` on ubuntu16 EC2 instance and specify the keypairname with a known working key. Does it expect the public key to be copied somewhere locally first? FWIW- I have installed toil[aws,cwl] and the awscli and configured it.

>Permission denied (publickey,password,keyboard-interactive). toil.provisioners.aws.awsProvisioner: Connection rejected, waiting for public SSH key to be propagated. Trying again in 10s

The coreos instance is created and I can ssh into it outside of AWS/EC2. Seems to be a local ssh config problem.

**Comment by jessebrennan** [comment]
Can you post exactly the entire `launch-cluster` command you typed in? We're currently in the process of improving the documentation in this area.

**Comment by jasper1918** [comment]
Happy to provide more context if it helps. 
1. User has full AdministrativeAccess policy and has an aws access key(jj_aws)
2. Launch an Ubunt16.04 image. SSH with (jj_aws) private key.
3. Install. `sudo apt-get update;sudo apt install -y python2.7; sudo apt install -y python-pip`
4. `pip install awscli`. Configure default user
5. `pip install toil[aws,cwl]`
6. `toil launch-cluster jj_test --nodeType=m3.medium --keyPairName=jj_aws`

I initially started in a VPC but backed out to the simplest use case here.

**Comment by jessebrennan** [comment]
Huh. I just tried to launch a cluster locally and was stuck in exactly the same place. This makes me think that the problems could be external. Perhaps boto throwing a fit. To add support to this theory a [recent unexplained test failure](http://jenkins.cgcloud.info/job/toil-pull-request-integration-tests/1309/testReport/junit/src.toil.test.utils.utilsTest/UtilsTest/testAWSProvisionerUtils/) seems like it may have had the same cause.

There's a chance that mine failed to launch for a different reason and I will look into this to confirm. Hopefully boto is the cause and this will just disappear shortly.

**Comment by ejacox** [comment]
@jasper1918 can you verify that your key pair was correctly injected into the Ubuntu box you created? Can you use the aws client tools from the box?

The trace you sent says "Trying again in 10s". How long did you wait?

**Comment by jasper1918** [comment]
I was able to confirm that the aws tools are working by using `aws s3 ls`. At this point, I have tried to use a 
 base ubuntu AMI, with and w/out a VPC and changing group settings.The "Trying again in 10s" continues indefinitely. 

However, the weird thing is that in each case a key( `AAAAB3NzaC1yc2Enoauthorizedkeyneeded`) does get pushed to the spawned image and I can confirm it is present when I log in from my desktop using my aws key. 

Certainly others are launching a cluster without problems. What am I missing? Do you have a minimal set of commands and configuration specs you could share?

**Comment by jessebrennan** [comment]
Did you run `ssh-add` to add the key?

**Comment by jessebrennan** [comment]
One more piece of debugging... After you launch the cluster and it is continuously trying to connect:

1. Copy the public ip of the machine to which you want to connect. Then ssh to it
```
ssh core@123.123.123.123
```
It seems like you should be able to do this fine.

2. Once connected, you can see if any docker containers are running by typing
```
docker ps
```
Let us know the result there.

3. Finally, to access the logs from the toil leader process as it starts up run:
```
journalctl -u toil-leader
```
Please share those logs! 

As a side note, when deleting these half baked instances make sure to use the ``toil destroy-cluster`` command. This ensures that all of the security groups and what not are all deleted as well.

**Comment by jessebrennan** [comment]
@jasper1918 Okay final thing. Assuming that your results for the steps above match what I suspect then we will have found the problem!

Which version of Toil are you using? It looks like you posted this right after the latest release. For some reason when 3.9 was pushed out its appliance image wasn't pushed onto [quay.io](https://quay.io/repository/ucsc_cgl/toil?tab=tags). This would be reflected in the logs of step 3 above.

If this is the problem, the simplest workaround is just to use a previous version of Toil until this is resolved. If you want the latest features you can [build from source](http://toil.readthedocs.io/en/latest/contributing/contributing.html) and then [post the appliance image yourself](http://toil.readthedocs.io/en/latest/contributing/contributing.html#developing-with-the-toil-appliance).

Apologies for the inconvenience!

**Comment by jasper1918** [comment]
@jessebrennan Thanks for looking into this. 

Just as you suspected the problem was a failed docker pull. I installed 3.8.0 and it worked smoothly. 

For those reading it may be important to note that you must:
1. Ensure VPC has DNS hostnames enabled
2. Ensure VPC has DNS resolution enabled
3. Ensure subnet has auto-assign ip enabled

**Comment by jessebrennan** [comment]
@jasper1918 glad it worked!
