### ISSUE TITLE
Toil 3.9 quay image wasn't pushed!

### ISSUE THREAD

**Issue by jessebrennan** [BD2KGenomics/toil#1776]
The result is that no one can spin up a cluster!

Work around is to use 3.8

Discovery of this bug is due to #1765

**Comment by ejacox** [comment]
Where is 3.9 referenced? It should be 3.9.1 (pypi choked on 3.9.0 and there is no way to redo it). 3.9.1 should be the latest.

**Comment by jessebrennan** [comment]
3.9.1 then. The point is the three isn't aqua image for it.

**Comment by nujhedtozu** [comment]
Hi, after looking at issue #1766, I can't seem to spin up a cluster on AWS even when using 3.8.0. The leader EC2 instance is spawned but I get the following message indefinitely:

> MainThread INFO toil.provisioners.aws.awsProvisioner: Attempting to establish SSH connection...
Permission denied (publickey,password,keyboard-interactive).
MainThread INFO toil.provisioners.aws.awsProvisioner: Connection rejected, waiting for public SSH key to be propagated. Trying again in 10s.

Is there anything that I may be missing?

**Comment by ejacox** [comment]
The 3.9.1 docker image was properly tagged, resolving this issue.

@nujhedtozu, I don't think your issue is related. I tried 3.9.1 and 3.8.0. They both worked for me. If you are still having problems, you could post more information at https://gitter.im/bd2k-genomics-toil/Lobby.
