### ISSUE TITLE
Futurize Stage 2 [python 2/3]

### ISSUE THREAD

**Issue by ryanking** [BD2KGenomics/toil#1785]
For context: https://github.com/BD2KGenomics/toil/issues/1780

In this step we'll run stage 2 of the futurize tool. See http://python-future.org/automatic_conversion.html#stage-2-py3-style-code-with-wrappers-for-py2

**Comment by diekhans** [comment]
How does futurize compare to using the six package?  It does seem to have the advantage of automating a lot of the work.

**Comment by ryanking** [comment]
The advantage of futurize is that it will rewrite the code automatically. :)

**Comment by diekhans** [comment]
I guess the question is about the maintainability of the code
after futurize?  I have no idea.  I did one small package with
six and it worked out well, however Toil is a *lot* more code.

**Comment by ryanking** [comment]
What are you worried about maintaining?

Maintaining a python 2 and 3 compatible codebase takes work, but much of it
can be automated. For example pylint has a python3 mode that will give
errors if any incompatible constructs are used.

This might be a bit easier once I have some diffs posted that illustrate
the examples.

**Comment by diekhans** [comment]
Main concern is ability to work on code after automated
modification.

A tool like fake8 or pylint is really helpful for ensuring
compatibility, but that doesn't necessary make continuing work
on the code easy.

Yea, please some diffs would help a lot.  It's reaching the
point where both py 2 and 3 compatibility seems important for a
package to be accepted, so I am very supportive of this.

**Comment by diekhans** [comment]
I just did a quick run of futurize on a big pile of my own python 2 code.  While all I did is observe the changes it made, I am rather impressed.  The results look simple to continue to develop.  I am positive that this approach will work out.

**Comment by jsmedmar** [comment]
This can be closed, no? as per #1806

**Comment by jessebrennan** [comment]
@jsmedmar nice catch.
