### ISSUE TITLE
Better manage provisioning.

### ISSUE THREAD

**Issue by ejacox** [BD2KGenomics/toil#1800]
The current AWS provisioner uses various adhoc methods to check on progress, e.g. 'ssh ps' to see if the docker daemon is running. This is not the most reliable method and often hangs.

One possible solution is Ansible.

**Comment by natanlao** [comment]
#1912

**Comment by DailyDreaming** [comment]
Closing this in favor of adding it to the list of provisioning refactor items in #2095.
