### ISSUE TITLE
Fork-free mode for debugging

### ISSUE THREAD

**Issue by mr-c** [BD2KGenomics/toil#1802]
So that we can use `ipdb` to debug Toil

**Comment by ejacox** [comment]
Is this mostly for the system calls in src/toil/test/utils/utilsTest.py?

**Comment by mr-c** [comment]
Forking also happens during regular execution of Toil outside of a testing

**Comment by jessebrennan** [comment]
I've finally taken some time to look into this and it looks like the singleMachine batchSystem uses threads. I haven't yet found where else forking might be happening. @mr-c can you point me to where you were running into problems?

**Comment by jessebrennan** [comment]
Nevermind, I see that jobs are launched with Popen.

**Comment by jessebrennan** [comment]
After looking into this more, completing this will require more in-depth knowledge of how jobs are serialized, stored, and prepared to be run than I currently have... 

Perhaps I can revisit this in the indefinite future. Meanwhile I'll see what I can learn.

**Comment by diekhans** [comment]
To generally address this issue, we need a way to integrate into remote debugging.
