### ISSUE TITLE
add option to install cwltoil as the default cwl-runner

### ISSUE THREAD

**Issue by mr-c** [BD2KGenomics/toil#1804]
See also https://github.com/common-workflow-language/cwltool/tree/master/cwlref-runner

Could be the right time to rename `cwltoil` to something else, maybe `toil-cwl-runner` ?

**Comment by ejacox** [comment]
The official name is now toil-cwl-runner. The cwltoil entry point is still there for now so as to not break any existing usages of it.

**Comment by ejacox** [comment]
@mr-c, is this just adding another entry point in setup.py called cwl-runner? It is already there. Should it be optional?

toil-cwl-runner is the official entry point. The old entry point (cwltoil) is still there for now, but not documented.

**Comment by mr-c** [comment]
@ejacox Well, we did that as a separate micro project so that it is optional thus allowing multiple CWL compliant workflow runners to be co-installed: https://github.com/common-workflow-language/cwltool/tree/master/cwlref-runner

**Comment by mr-c** [comment]
To be clear, it should indeed be optional so that the user can switch between CWL implementations in the same virtualenv. I just ran into this :-(

**Comment by mr-c** [comment]
Another option besides https://github.com/BD2KGenomics/toil/issues/1804#issuecomment-331088776 could be a "fake" `extra` like `cwl_not_default_runner` and then skip adding `cwl-runner` to the `entry_points.console_scripts` if the user did `pip install toil[cwl,cwl_not_default_runner]` or similar.
