### ISSUE TITLE
Remove cgcloud lib dependencies from the AWS provisioner.

### ISSUE THREAD

**Issue by ejacox** [BD2KGenomics/toil#1813]
At a minimum, the code from cgcloud should be moved into Toil. The instance types should not be hard-coded. Consider keeping them in a separate file. Also, is there way to use instance types that are not pre-defined?

**Comment by joelarmstrong** [comment]
We need the instance specs (cpu, memory, etc.) for the autoscaler to work correctly. As of right now, there isn't an EC2 API to get specs from a string like `t2.nano`. So there has to be a manually updated list of instance types somewhere. I'm OK with moving the one from cgcloud into toil.

**Comment by jessebrennan** [comment]
Should cgcloud then import the code from Toil? Should it instead be moved to a repository like https://github.com/BD2KGenomics/bd2k-python-lib that is shared by both?

**Comment by ejacox** [comment]
We are deprecating cgcloud. Do any of the other libraries rely on cgcloud?

**Comment by jessebrennan** [comment]
@ejacox I don't know. For now, I will just copy them over to Toil.
