### ISSUE TITLE
RealtimeLogging doesn't work with autoscaling

### ISSUE THREAD

**Issue by glennhickey** [BD2KGenomics/toil#1818]
I'm a huge fan of the --realTimeLogging option as it's great for following progress and debugging.  It worked on Mesos with cgcloud, but does not seem to work at all on the AWS provisioner with autoscaling.  Is this fixable?  I believe @adamnovak is the original author...

**Comment by adamnovak** [comment]
It could just be a firewall issue. Can random AWS instances send packets to
your master? Or is it locked down by an AWS security group?

**Comment by adamnovak** [comment]
Keep in mind that there's no encryption or authentication on the real time
log messages. So someone on the Internet can inject things into your logs
if you open the port up globally.
