### ISSUE TITLE
NonCachingFileStore open() may delete the parent directory of localTempDir in LSF job

### ISSUE THREAD

**Issue by liuxf09** [BD2KGenomics/toil#1825]
I have a workflow that is running using `--disableCaching --batchSystem=lsf `. In the workflow, it will use scatter method, that means a set of jobs will be executed under the same parent directory. The symptom is that some job will fail to open `.jobState` file because its directory is removed by another job. 

In `NonCachingFileStore open()`, it will call `findAndHandleDeadJobs(workFlowDir)`. Howerver `workFlowDir` is assigned to be the parent directory of `localTempDir`. I guess there is some confusion about `localTempDir`: `localTempDir` is assigned to a sub directory of the input `localTempDir`, and the input `localTempDir` should become the `workFLowDir` of the current job.

Since `workFlowDir` is used in `NonCachingFileStore`, it is better to move `workFlowDir` from the base class `FileStore` to as a data member of `NonCachingFileStore`, and assign 'localTempDir` to `workFlowDir` solved my problem.

**Comment by liuxf09** [comment]
I tested for my toil workflow job using batchSystem LSF, and it worked.

**Comment by ejacox** [comment]
This seems like it is related to #1863. If not, this issue can be reopened.
