### ISSUE TITLE
cwltoil memory options not working

### ISSUE THREAD

**Issue by DailyDreaming** [BD2KGenomics/toil#1835]
I've run the new cwltoil branch (CWL v1.0.1 support #1810 @tetron ) for some of the GA4GH-DREAM challenges on AWS using:
pip install cwltool==1.0.20170815202200
pip install git+https://github.com/BD2KGenomics/toil.git@9cf913bf53

It seems to work for the small jobs (fixing old problems), but fails on the larger jobs because it seems to still be using Toil's default: "cores: 1, disk: 2.0 G, and memory: 1.0 G"
Even when specifying something like:
`cwltoil --defaultMemory 16 --defaultCores 8 --defaultDisk 2 /home/ubuntu/cwl/workflows/dnaseq/transform.cwl /home/ubuntu/transform.cwl.json`

**Comment by mr-c** [comment]
@DailyDreaming This could be due to https://github.com/BD2KGenomics/toil/pull/1810#discussion_r132965651 perhaps?

Does your `transform.cwl` use a `ResourceRequirement` to specify min/max resources?

**Comment by tetron** [comment]
I suspect what is happening is that transform.cwl doesn't have ResourceRequirement, but cwltoil overrides Toil's resource defaults, so you're getting the cwltool defaults.

When it loads the tool in #1810 it should set up a default ResourceRequirement hint at the top level that reflects the command line options.

**Comment by tetron** [comment]
Should be fixed in #1810 now.
