### ISSUE TITLE
cwltoil on LSF + CWL conformance tests

### ISSUE THREAD

**Issue by mr-c** [BD2KGenomics/toil#1836]
Current failures
- [x] 81 `v1.0/cat3-tool.cwl v1.0/file-literal.yml`
```
[job cat3-tool.cwl] /hps/nobackup/production/metagenomics/CWL/mcrusoe/common-workflow-language/tmpW4Eb1h/JHnHbU$ cat \
    /hps/nobackup/production/metagenomics/CWL/mcrusoe/common-workflow-language/tmpW4Eb1h/tmpGkG54b/stg10ed1aed-cea5-4231-8fc2-c36d34f53b3d/85436fff-4f2
e-48b2-a568-b2267ab9ba0c > /hps/nobackup/production/metagenomics/CWL/mcrusoe/common-workflow-language/tmpW4Eb1h/JHnHbU/output.txt
INFO:cwltool:[job cat3-tool.cwl] /hps/nobackup/production/metagenomics/CWL/mcrusoe/common-workflow-language/tmpW4Eb1h/JHnHbU$ cat \
    /hps/nobackup/production/metagenomics/CWL/mcrusoe/common-workflow-language/tmpW4Eb1h/tmpGkG54b/stg10ed1aed-cea5-4231-8fc2-c36d34f53b3d/85436fff-4f2
e-48b2-a568-b2267ab9ba0c > /hps/nobackup/production/metagenomics/CWL/mcrusoe/common-workflow-language/tmpW4Eb1h/JHnHbU/output.txt
cat: /hps/nobackup/production/metagenomics/CWL/mcrusoe/common-workflow-language/tmpW4Eb1h/tmpGkG54b/stg10ed1aed-cea5-4231-8fc2-c36d34f53b3d/85436fff-4f
2e-48b2-a568-b2267ab9ba0c: No such file or directory
```
- [ ] 82 (Checksum due to different Java version?)
- [x] ~~89 (DockerReq should be under `hints`)~~
- [x] ~~91 (DockerReq should be under `hints`)~~
- [x] ~~94 (DockerReq, not fixable as it tests the docker output directory feature -- should be marked optional)~~
- [x] 109 (Fixed in https://github.com/BD2KGenomics/toil/pull/1810/commits/ceaf9472aac76f0422bbb1ba6bd548168d3ed4ea from #1810? )

82, 89, 91, 94 are not Toil's fault and will be fixed by https://github.com/common-workflow-language/common-workflow-language/issues/491

**Comment by tetron** [comment]
I'm a little puzzled because the file literal test works for me.  What version did you test with?  This was updated in 9cf913bf

**Comment by mr-c** [comment]
@tetron The file literal test failure is reproducible with latest cwltool by passing `--no-container`

See https://github.com/common-workflow-language/common-workflow-language/pull/507 where I add the same conformance test but without Docker

**Comment by tetron** [comment]
Oops, thanks for tracking down & fixing.

**Comment by tetron** [comment]
Will bump cwltool used in #1810

**Comment by mr-c** [comment]
@tetron Thanks!
