### ISSUE TITLE
Fix flakey AWS tests

### ISSUE THREAD

**Issue by jessebrennan** [BD2KGenomics/toil#1840]
Boto calls fail sometimes when Amazon get's finicky and throttles us. We aren't prepared to handle these exceptions.

Also sometimes with newly created instances, a 400 error is returned and we don't catch it. [example](http://jenkins.cgcloud.info/job/toil-pull-request-integration-tests/1950/testReport/junit/src.toil.test.provisioners.aws.awsProvisionerTest/AWSAutoscaleTestMultipleNodeTypes/testAutoScale/)

One solution is to make a wrapper for all boto calls. 

Another would be to take the mechanism used in #1837, stick it inside a context manager or decorator or something and then apply the decorator to functions that make these boto calls.

**Comment by jessebrennan** [comment]
https://www.saltycrane.com/blog/2009/11/trying-out-retry-decorator-python/ here is a decent implementation of the decorator idea

**Comment by jessebrennan** [comment]
Or see https://github.com/BD2KGenomics/toil/pull/1976/commits/8a0d8e5fba484f3965777781275c8bedb87ac870#diff-4e9889af67d06e458ad1528557a177c9R73
for an example of the same thing, but with google.

**Comment by jessebrennan** [comment]
src.toil.test.provisioners.aws.awsProvisionerTest.AWSStaticAutoscaleTest.testSpotAutoScale fails sometimes because it thinks there are more workers than there are.

**Comment by jessebrennan** [comment]
http://jenkins.cgcloud.info/job/toil-pull-request-integration-tests/1972/testReport/junit/src.toil.test.provisioners.aws.awsProvisionerTest/AWSAutoscaleTestMultipleNodeTypes/testAutoScale/ has been failing fairly frequently. @ejacox suggested this could be due to the Spectre bug making everything cloud 30% as fast. Probably timeout should be increased.

**Comment by joelarmstrong** [comment]
Don't bother increasing the timeout. This is the same root issue I mentioned in [this comment](https://github.com/BD2KGenomics/toil/pull/2059#issuecomment-364617498). Basically, for some reason the t2.small, which has 2GB of RAM, is only reporting ~1GB, and often (randomly) a few MB left, which triggers the failure.

```
2018-02-14 18:46:33,053 - toil.batchSystems.mesos.batchSystem - DEBUG - Got offer de67f2db-3845-4fed-9535-148723cf69d5-O0 for a non-preemptable slave with 997.00 MiB memory, 1.00 core(s) and 42121.00 MiB of disk.
2018-02-14 18:46:33,053 - toil.batchSystems.mesos.batchSystem - DEBUG - Offer de67f2db-3845-4fed-9535-148723cf69d5-O0 not suitable to run the tasks with requirements {'cores': 1, 'preemptable': False, 'disk': 2147483648, 'memory': 1048576000}. Mesos offered 1045430272.0 memory, 1.0 cores and 44167069696.0 of disk on a non-preemptable slave.
```

I haven't yet checked what exactly is causing ~1GB of overhead on these t2.smalls. I really haven't seen this much overhead in my runs. Maybe it's somehow caused by the node-exporter container failure/restart loop? I really have no good guess.

**Comment by ejacox** [comment]
This is happening on Google, too. Tests are now timing out during cluster shutdown after the test ran successfully.
