### ISSUE TITLE
Avoid copying files to the jobStore on shared file systems.

### ISSUE THREAD

**Issue by ejacox** [BD2KGenomics/toil#1846]
See the discussion at the end of #1627.

**Comment by tetron** [comment]
Maybe #1786 is what you want?

**Comment by tetron** [comment]
If hard links are available, they can be used to avoid copying the initial input files, and also avoid copying intermediate files (create a hard link in the filestore, can then delete the original output file in the temp directory).

**Comment by evanthomas** [comment]
#1786 does indeed look like what I want. I am running 3.9.1 which looks like I've just missed.

**Comment by evan-wehi** [comment]
evanthomas is me as well. I was logged in with my personal user id. #1786 just makes this the default action, doesn't actually solve the problem (which I am experiencing severely at the moment).

**Comment by ejacox** [comment]
Hey @evan-wehi. I am not sure what thread you are referring to. Is this the problem of copying the files on the same system (~4tb of them).

**Comment by evan-wehi** [comment]
Hi @ejacox - When a workflow starts the leader stages input files into the jobs store by copying them. This takes a long time and duplicates the data on storage. Hard linking would solve this. It seems Toil does this for files between steps but not for the initial files.

**Comment by diekhans** [comment]
It's probably necessary to use symbolic links, as the source
file might not be on the same file system as the jobstore.

**Comment by joelarmstrong** [comment]
In that case a worker running on a different node may not be able to access the linked file, though (if the import is from a local disk, for example). At least a hard link will fail at creation time rather than access time. On the other hand, symbolic links would help if there are two separate shared filesystems.

There is a --linkImports function you can use--it's not enabled by default because if caching is enabled, the permissions on the imported file may be changed.

**Comment by evan-wehi** [comment]
My understanding was that --linkImports only supports imports between job steps, not the initial file staging. It certainly didn't work me. Do I need to do something else to enable it? I'm using my own BatchSystem (ala pr #1392). Perhaps I'm missing something in the BS implementation?

**Comment by ejacox** [comment]
@evan-wehi, #1864 also discusses the input file copy issue.

**Comment by ejacox** [comment]
@evan-wehi, --linkImports worked for me. I tried `toil-cwl-runner --linkImports --clean never inp.cwl inp-job.yml`, from http://www.commonwl.org/user_guide/03-input/. The hard link count on the input (whale.txt) incremented correctly. Are you doing something differently?

**Comment by evan-wehi** [comment]
@ejacox I'll do some testing myself later in the week and let you know.

**Comment by evan-wehi** [comment]
@ejacox I tested again and sure enough imports are being linked. Not sure what happened with my earliers run, earlier toil version and/or user error, I guess. Thanks for looking at it for me.

**Comment by ejacox** [comment]
No problem @evan-wehi. We appreciate your feedback.
