### ISSUE TITLE
What happened to `make test_local`?

### ISSUE THREAD

**Issue by mr-c** [BD2KGenomics/toil#1848]
https://github.com/BD2KGenomics/toil/blob/master/Makefile#L41

**Comment by ejacox** [comment]
It looks like it was renamed to test_offline, but the description wasn't changed. @jessebrennan can you take a look at this.

**Comment by jessebrennan** [comment]
@ejacox is right. It seemed like a better name (of two, not great options) to me. This was addressed in #1741 and in in the documentation [here](http://toil.readthedocs.io/en/latest/contributing/contributing.html#running-tests).

**Comment by mr-c** [comment]
This is not yet fixed in the `Makefile` as linked to above

**Comment by jessebrennan** [comment]
@mr-c oops! you're totally right. I was confused.

**Comment by mr-c** [comment]
Still not fixed in the makefile :-P
