### ISSUE TITLE
TestService failing

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#185]

**Comment by cket** [comment]
This test is disabled via
9942f87ff5b0469b25286fde17aea216c52d9fe4

**Comment by benedictpaten** [comment]
Is this still failing?

**Comment by hannes-ucsc** [comment]
Last time I checked (yesterday) it was failing.

On Thu, Aug 13, 2015 at 11:00 PM, Benedict Paten <notifications@github.com>
wrote:

> Is this still failing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BD2KGenomics/toil/issues/185#issuecomment-130982938>.
>



-- 
Hannes Schmidt
Software Engineer
Center for Biomolecular Science and Engineering
University of California, Santa Cruz

(206) 696-2316 (cell)
hannes@ucsc.edu
