### ISSUE TITLE
AWS autoscaling instructions don't include a virtualenv

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#1857]
The [running on AWS instructions](http://toil.readthedocs.io/en/3.10.1/running/amazon.html#runningaws) don't mention that you need to set up a virtualenv, install your script and its dependencies in that virtualenv, and run from that virtualenv in order to allow Toil to hot-deploy the dependencies to the cluster nodes.

I'm trying to run a Toil workflow packaged as a pip-installed module (toil-vg) with dependencies, using a bunch of `toil ssh-cluster <command to run>` commands from a controlling host, and the need to have a virtualenv is complicating things, because I can't source the activate script when running a single command on a remote machine. It would be extremely helpful to have an example of what the Right Way to do this is, or even an example of the Right Way to set up a virtualenv to hold your autoscaling workflow when using an interactive `toil ssh-cluster` shell (so I know I at least have that part right).

┆Issue Number: TOIL-8

**Comment by DailyDreaming** [comment]
Docs now include this: http://toil.readthedocs.io/en/3.15.0/running/cloud/amazon.html
