### ISSUE TITLE
Many references in the API documentation are not linked.

### ISSUE THREAD

**Issue by diekhans** [BD2KGenomics/toil#1885]
for instance http://toil.readthedocs.io/en/3.10.1/developingWorkflows/toilAPI.html

readGlobalFile fileStoreID (toil.fileStore.FileID) is not a link to the documention on FileID.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-33)
┆Issue Number: TOIL-33

**Comment by diekhans** [comment]
referencestoil.fileStore.FileID is inconsistencly names in the API doc

**Comment by DailyDreaming** [comment]
One more documentation problem:

`Job.Runner.startToil(j, options)` is deprecated and should not be in the docs:
https://toil.readthedocs.io/en/3.11.0/developingWorkflows/developing.html?highlight=starttoil

DEPRECATED (Example 1 in the docs):
`from toil.job import Job
def init_job(job, variable):
    return variable
j = Job.wrapFn(init_job)
if __name__=="__main__":
    options = Job.Runner.getDefaultOptions("./toilWorkflow")
    print Job.Runner.startToil(j, options)`


PROPER FORM (should be this instead):
`from toil.job import Job
def init_job(job, variable):
    return variable
if __name__=="__main__":
    options = Job.Runner.getDefaultOptions("./toilWorkflow")
    options.logLevel = "DEBUG"
    with Toil(options) as toil:
        job0 = Job.wrapJobFn(init_job)
        toil.start(job0)`

**Comment by natanlao** [comment]
In addition, some modules are omitted from the documentation altogether. (#1624)

**Comment by bencvdb** [comment]
Fixed as of 3.15
