### ISSUE TITLE
Move AWS instance list to Toil (from cgcloud) and update it

### ISSUE THREAD

**Issue by joelarmstrong** [BD2KGenomics/toil#1893]
AWS doesn't provide an API to get instance specs, so we need to keep a list of valid instance names and their corresponding details (cpu, memory, disk, etc.). Right now we use the cgcloud list, but it's not sufficiently kept up to date, and this seems like it should be Toil's responsibility.

The old list is missing the new i3 instances, as well as the new t2s, and probably more.

**Comment by jessebrennan** [comment]
This is being covered in #1813.

**Comment by jessebrennan** [comment]
I wrote a little script to compare the instances listed [here](http://www.ec2instances.info/?region=us-west-2) with the ones from [here](https://github.com/BD2KGenomics/toil/pull/1923/files#diff-ed008c1cdf921cfa8f0f83a80388e1a2R188).

It seems like the instances that need to be added are 't1.micro', 't2.nano', 't2.xlarge', 't2.2xlarge', 'm4.16xlarge', 'r4.large', 'r4.xlarge', 'r4.2xlarge', 'r4.4xlarge', 'r4.8xlarge', 'r4.16xlarge', 'p2.xlarge', 'p2.8xlarge', 'p2.16xlarge', 'g3.4xlarge', 'g3.8xlarge', 'g3.16xlarge', 'g2.8xlarge', 'x1.16xlarge', 'x1.32xlarge', 'x1e.32xlarge', 'f1.2xlarge', 'f1.16xlarge', 'i3.large', 'i3.xlarge', 'i3.2xlarge', 'i3.4xlarge', 'i3.8xlarge', 'i3.16xlarge'

I'm not quite sure where to get information on para-virtualization and hardware virtualization, but it seems like a lot of this info can be automatically scrapped from that webpage.

**Comment by adderan** [comment]
It might also be good to include the on-demand instance prices in that list, and then prioritize cheapest nodes in the autoscaling rather than lowest memory.
