### ISSUE TITLE
Deprecate pycrypto.

### ISSUE THREAD

**Issue by ejacox** [BD2KGenomics/toil#1935]
pycrypto hasn't been maintained in 3 years. It also doesn't support Python 3. (I think this last point is a work in progress for toil)

Consider using pycryptodome (drop-in replacement) or cryptography as a dependency.

Comment from @psafont in #1923

**Comment by psafont** [comment]
In the documentation, cryptography is listed as an [extra requirement](http://toil.readthedocs.io/en/3.11.0/gettingStarted/install.html#installing-extra-features), some consolidation would be great.

**Comment by ejacox** [comment]
It needs to be installed if the files need to be encrypted. What do you mean by 'consolidation'?

**Comment by psafont** [comment]
I mean using a single library for cryptography instead of depending on two different ones.

**Comment by ejacox** [comment]
OK. Thank you @psafont. I will add these to #1780 since they impact using Python 3.
