### ISSUE TITLE
Move bd2k-python-lib into Toil.

### ISSUE THREAD

**Issue by ejacox** [BD2KGenomics/toil#1936]
┆Issue Number: TOIL-7

**Comment by jessebrennan** [comment]
Why?

**Comment by ejacox** [comment]
To make the python 3 compatibility move easier. There is some thornier low level code that is going to be hard to convert. I didn't see a reason for us to continue supporting a separate repository. Do you?

**Comment by jessebrennan** [comment]
Python 3 compatibility is a pretty good reason although we could just as easily maintain it in the other repository. Are there any other projects that make use of that code? It was probably placed in a separate repository initially for a reason. Why not just leave it there?

**Comment by jvivian** [comment]
@jessebrennan — What about moving the _minimum_ set of functions over that Toil relies on from bd2k-python-lib. It was initially placed in its own repo so Hannes wouldn't have to push updates to Toil for bd2k-python-lib related things. 

Extending this issue to cover moving over a few choice functions from toil-lib would also be useful. I think Toil should have native support for things like: downloading a file from a URL, moving files, map job (unless that bugs been fixed @joelarmstrong), etc.

**Comment by jessebrennan** [comment]
@jvivian yeah, that sounds reasonable.

**Comment by diekhans** [comment]
Yea! copying only what toil needs is a good idea.

Are there non-toil projects using bd2k-python-lib?

If code is being used by non-toil based projects, I would
suggest leaving it in bd2k-lib, maybe marking with @deprecated,
or at least with a comment.

**Comment by DailyDreaming** [comment]
Closed by #2209.
