### ISSUE TITLE
Convenience job attributes

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil#1940]
I was talking with a few other pipeline developers and a few additions to the `job` instance, like `job.cores`,  would cut down on boilerplate and make the code more readable.

- [ ] `job.tempDir` —  At the top of every job function I have to write `work_dir = job.fileStore.getLocalTempDir()` to create and get the localTempDir path. Instead, have `job.tempDir` return the file path from `job.fileStore.getLocalTempDir()`, but don't require me to invoke it to create the local temp dir, i.e. create the directory when invoked for the first time in a job function or just always create it if that overhead isn't large. 

- [ ] `job.log` — We could just point this to `job.fileStore.logToMaster` or w/e the preferred logging  system is.

**Comment by fnothaft** [comment]
+1

**Comment by jessebrennan** [comment]
ill take a crack at it...

**Comment by jvivian** [comment]
@jessebrennan — That's my kinda enthusiasm.
