### ISSUE TITLE
Cluster manager exception causes cluster to stay up

### ISSUE THREAD

**Issue by tpesout** [BD2KGenomics/toil#1945]
An exception in the cluster manager (or the cluster scaler?) causes the leader to die, but the cluster is left running.  

I can supply a log file if need be, or a better explanation of what happened.

Sorry if this is a duplicate, I looked but couldn't find anything.

>  File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 544, in _addNodes
>     return self.scaler.provisioner.addNodes(nodeType=nodeType, numNodes=numNodes, preemptable=preemptable)
>   File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/aws/awsProvisioner.py", line 297, in addNodes
>     spec=kwargs, num_instances=numNodes)
>   File "/usr/local/lib/python2.7/dist-packages/cgcloud/lib/ec2.py", line 414, in create_ondemand_instances
>     **spec ).instances
>   File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 973, in run_instances
>     verb='POST')
>   File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1208, in get_object
>     raise self.ResponseError(response.status, response.reason, body)
> EC2ResponseError: EC2ResponseError: 400 Bad Request
> <?xml version="1.0" encoding="UTF-8"?>
> <Response><Errors><Error><Code>InstanceLimitExceeded</Code><Message>Your quota allows for 1 more running instance(s). You requested at least 2</Message></Error></Errors><RequestID>f7745311-49af-49bd-872e-71573250f090</RequestID></Response>
> ip-172-31-31-120.us-west-2.compute.internal 2017-10-28 02:04:41,568 MainThread INFO toil.leader: Waiting for workers to shutdown
> 2017-10-28 02:04:41,568 - toil.leader - INFO - Waiting for workers to shutdown
> ip-172-31-31-120.us-west-2.compute.internal 2017-10-28 02:04:41,568 MainThread INFO toil.leader: Worker shutdown complete in 1.28746032715e-05 seconds
> 2017-10-28 02:04:41,568 - toil.leader - INFO - Worker shutdown complete in 1.28746032715e-05 seconds
> ip-172-31-31-120.us-west-2.compute.internal 2017-10-28 02:04:41,568 MainThread INFO toil.serviceManager: Waiting for service manager thread to finish ...
> 2017-10-28 02:04:41,568 - toil.serviceManager - INFO - Waiting for service manager thread to finish ...
> ip-172-31-31-120.us-west-2.compute.internal 2017-10-28 02:04:41,802 MainThread INFO toil.serviceManager: ... finished shutting down the service manager. Took 0.23318696022 seconds
> 2017-10-28 02:04:41,802 - toil.serviceManager - INFO - ... finished shutting down the service manager. Took 0.23318696022 seconds
> ip-172-31-31-120.us-west-2.compute.internal 2017-10-28 02:04:41,802 MainThread INFO toil.statsAndLogging: Waiting for stats and logging collator thread to finish ...
> 2017-10-28 02:04:41,802 - toil.statsAndLogging - INFO - Waiting for stats and logging collator thread to finish ...
> ip-172-31-31-120.us-west-2.compute.internal 2017-10-28 02:04:41,911 MainThread INFO toil.statsAndLogging: ... finished collating stats and logs. Took 0.108911037445 seconds
> 2017-10-28 02:04:41,911 - toil.statsAndLogging - INFO - ... finished collating stats and logs. Took 0.108911037445 seconds
> I1028 02:04:41.911429 22624 sched.cpp:1987] Asked to stop the driver
> I1028 02:04:41.911499 22707 sched.cpp:1187] Stopping framework '806e1237-19b6-4f11-a599-f5c0ee7d0ad4-0003'
> Traceback (most recent call last):
>   File "/opt/marginPhase/toil/venv/bin/toil-marginphase", line 11, in <module>
>     load_entry_point('toil-marginPhase==1.0.0a1', 'console_scripts', 'toil-marginphase')()
>   File "/opt/marginPhase/toil/venv/local/lib/python2.7/site-packages/toil_marginphase/marginphase_pipeline.py", line 1113, in main
>     Job.Runner.startToil(Job.wrapJobFn(map_job, prepare_input, samples, config), args)
>   File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 753, in startToil
>     return toil.start(job)
>   File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 727, in start
>     return self._runMainLoop(rootJobGraph)
>   File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 997, in _runMainLoop
>     jobCache=self._jobCache).run()
>   File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 183, in run
>     self.innerLoop()
>   File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 479, in innerLoop
>     self.clusterScaler.check()
>   File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 273, in check
>     raise RuntimeError('The cluster scaler has exited due to an exception')
> RuntimeError: The cluster scaler has exited due to an exception

**Comment by DailyDreaming** [comment]
You're right, if your AWS user account limit is reached, toil should carry on with the resources it's allowed or at the very least fail a bit more gracefully.  @ejacox , could you take a look at this?

**Comment by ejacox** [comment]
@DailyDreaming, does the autoscalar take in to account the AWS limit?

**Comment by tpesout** [comment]
I've got another error which caused "the cluster scaler has exited due to an exception" and left my ~50 node cluster running.  This is different from the instance limit exception above, but I still think it's important for the cluster manager to try to shut down the cluster when it fails.

> 2017-11-30 06:11:52,245 - toil.provisioners.clusterScaler - ERROR - The read operation timed out
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 270, in check
>     self.scaler.join(timeout=0)
>   File "/opt/marginPhase/toil/venv/local/lib/python2.7/site-packages/bd2k/util/threading.py", line 52, in run
>     self.tryRun( )
>   File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 415, in tryRun
>     self.totalNodes[nodeShape] = len(self.scaler.leader.provisioner.getProvisionedWorkers(nodeType=nodeType, preemptable=nodeShape.preemptable))
>   File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/aws/awsProvisioner.py", line 325, in getProvisionedWorkers
>     entireCluster = self._getNodesInCluster(ctx=self.ctx, clusterName=self.clusterName, both=True, nodeType=nodeType)
>   File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/aws/awsProvisioner.py", line 745, in _getNodesInCluster
>     'instance-state-name': 'running'})
>   File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 622, in get_only_instances
>     next_token=next_token)
>   File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 681, in get_all_reservations
>     [('item', Reservation)], verb='POST')
>   File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1171, in get_list
>     body = response.read()
>   File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 410, in read
>     self._cached_response = http_client.HTTPResponse.read(self)
>   File "/usr/lib/python2.7/httplib.py", line 578, in read
>     return self._read_chunked(amt)
>   File "/usr/lib/python2.7/httplib.py", line 636, in _read_chunked
>     value.append(self._safe_read(chunk_left))
>   File "/usr/lib/python2.7/httplib.py", line 693, in _safe_read
>     chunk = self.fp.read(min(amt, MAXAMOUNT))
>   File "/usr/lib/python2.7/socket.py", line 380, in read
>     data = self._sock.recv(left)
>   File "/usr/lib/python2.7/ssl.py", line 341, in recv
>     return self.read(buflen)
>   File "/usr/lib/python2.7/ssl.py", line 260, in read
>     return self._sslobj.read(len)
> SSLError: The read operation timed out
> ip-172-31-29-174.us-west-2.compute.internal 2017-11-30 06:11:52,246 MainThread INFO toil.leader: Waiting for workers to shutdown
> 2017-11-30 06:11:52,246 - toil.leader - INFO - Waiting for workers to shutdown
> ip-172-31-29-174.us-west-2.compute.internal 2017-11-30 06:11:52,246 MainThread INFO toil.leader: Worker shutdown complete in 1.12056732178e-05 seconds
> 2017-11-30 06:11:52,246 - toil.leader - INFO - Worker shutdown complete in 1.12056732178e-05 seconds
> ip-172-31-29-174.us-west-2.compute.internal 2017-11-30 06:11:52,246 MainThread INFO toil.serviceManager: Waiting for service manager thread to finish ...
> 2017-11-30 06:11:52,246 - toil.serviceManager - INFO - Waiting for service manager thread to finish ...
> ip-172-31-29-174.us-west-2.compute.internal 2017-11-30 06:11:52,482 MainThread INFO toil.serviceManager: ... finished shutting down the service manager. Took 0.235867023468 seconds
> 2017-11-30 06:11:52,482 - toil.serviceManager - INFO - ... finished shutting down the service manager. Took 0.235867023468 seconds
> ip-172-31-29-174.us-west-2.compute.internal 2017-11-30 06:11:52,482 MainThread INFO toil.statsAndLogging: Waiting for stats and logging collator thread to finish ...
> 2017-11-30 06:11:52,482 - toil.statsAndLogging - INFO - Waiting for stats and logging collator thread to finish ...
> ip-172-31-29-174.us-west-2.compute.internal 2017-11-30 06:11:52,646 MainThread INFO toil.statsAndLogging: ... finished collating stats and logs. Took 0.164399147034 seconds
> 2017-11-30 06:11:52,646 - toil.statsAndLogging - INFO - ... finished collating stats and logs. Took 0.164399147034 seconds
> I1130 06:11:52.647231 14349 sched.cpp:1987] Asked to stop the driver
> I1130 06:11:52.702985 14951 sched.cpp:1187] Stopping framework 'b35a9e7c-9994-4ba9-95ae-a8aed2a4384f-0031'
> Traceback (most recent call last):
>   File "/opt/marginPhase/toil/venv/bin/toil-marginphase", line 11, in <module>
>     load_entry_point('toil-marginPhase==1.0.0a1', 'console_scripts', 'toil-marginphase')()
>   File "/opt/marginPhase/toil/venv/local/lib/python2.7/site-packages/toil_marginphase/marginphase_pipeline.py", line 1111, in main
>     Job.Runner.startToil(Job.wrapJobFn(map_job, prepare_input, samples, config), args)
>   File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 753, in startToil
>     return toil.start(job)
>   File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 727, in start
>     return self._runMainLoop(rootJobGraph)
>   File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 997, in _runMainLoop
>     jobCache=self._jobCache).run()
>   File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 183, in run
>     self.innerLoop()
>   File "/usr/local/lib/python2.7/dist-packages/toil/leader.py", line 479, in innerLoop
>     self.clusterScaler.check()
>   File "/usr/local/lib/python2.7/dist-packages/toil/provisioners/clusterScaler.py", line 273, in check
>     raise RuntimeError('The cluster scaler has exited due to an exception')
> RuntimeError: The cluster scaler has exited due to an exception
