### ISSUE TITLE
exporting a file to local disk (from another jobStore) reads the entire file into RAM

### ISSUE THREAD

**Issue by joelarmstrong** [BD2KGenomics/toil#1983]
https://github.com/BD2KGenomics/toil/blob/890480506f977ba5faadab4b1cdb90696a7dd2da/src/toil/jobStores/fileJobStore.py#L223

This means that you run out of memory (raising MemoryError) when exporting large files.

**Comment by DailyDreaming** [comment]
I think it might actually be two methods.  I made a PR: #2047.
