### ISSUE TITLE
Makefile does not detect virtualenv with Python 3

### ISSUE THREAD

**Issue by natanlao** [BD2KGenomics/toil#1985]
```
$ virtualenv venv3 -p python3.6
$ . venv3/bin/activate.fish
$ make prepare
A virtualenv must be active.
make: *** [check_venv] Error 1
```

Fix: https://stackoverflow.com/a/42580137
Related to #1780

**Comment by jsmedmar** [comment]
Had same problem today.

**Comment by ygrange** [comment]
After bumping into this one myself, I decided to implement the linked solution and propose a pull request.
