### ISSUE TITLE
Provisioner refactor

### ISSUE THREAD

**Issue by natanlao** [BD2KGenomics/toil#1986]
- [ ] `AWSProvisioner` implementation differs from `AbstractProvisioner` specification (e.g. [AbstractProvisioner:167][0] specifies `launchCluster(cls, instanceType, ...)` but [AWSProvisioner:110][1] implements `launchCluster(self, leaderNodeType, ..., nodeTypes, preemptableNodeTypes, ...)`

- [ ] A number of methods that are shared between provisioners (e.g. `_waitForDockerDaemon`, `_waitForSSHKeys`) should be moved to the `AbstractProvisioner`. This is a continuation of #1971
- [ ] CLI cluster utils and tests will probably needed be updated
- [ ] [AWSProvisioner constructor docstring](https://github.com/BD2KGenomics/toil/blob/27edc4b64e992f29de64c863f00044771d494022/src/toil/provisioners/aws/awsProvisioner.py#L69) specifies `batchSystem` parameter not present in signature
- [ ] `toil.provisioners.awsFilterImpairedNodes` is aws-specific
- [ ] `toil.test.provisioners.awsProvisionerTest` should be refactored so that a single test suite can be used interchangeably with different provisioners

  [0]: https://github.com/BD2KGenomics/toil/blob/27edc4b64e992f29de64c863f00044771d494022/src/toil/provisioners/abstractProvisioner.py#L167
  [1]: https://github.com/BD2KGenomics/toil/blob/27edc4b64e992f29de64c863f00044771d494022/src/toil/provisioners/aws/awsProvisioner.py#L110
  [2]: https://github.com/BD2KGenomics/toil/blob/27edc4b64e992f29de64c863f00044771d494022/src/toil/provisioners/aws/awsProvisioner.py#L74

**Comment by ejacox** [comment]
For the second point, are you suggesting passing in the clusterName to the constructor? Where will the clusterName be "guessed"? Or will there be another way for the leader to determine which cluster it is in when it starts?

**Comment by natanlao** [comment]
On further review, it looks like I've very grossly misunderstood that code - I've removed my second point. The other points still stand, however.

**Comment by DailyDreaming** [comment]
Covered by #2095.
