### ISSUE TITLE
move "cwl-runner" script from the CWL extra to a different package or a different extra

### ISSUE THREAD

**Issue by mr-c** [BD2KGenomics/toil#1994]
By always installing `toil-cwl-runner` as `cwl-runner`, Toil takes away the users choice to switch between CWL implementations.

https://github.com/BD2KGenomics/toil/blob/master/setup.py#L76

Options:
1. `pip install toil[cwl_default]` is equivalent to the current behaviour (both `toil-cwl-runner` and `cwl-runner` console scripts are setup; and `pip install toil[cwl]` only installs the `toil-cwl-runner` script
2. the reverse of the above: `pip install toil[cwl_notdefault]` leaves out the `cwl-runner` console script
3. the `cwl-runner` shortcut is moved to another package, like `cwlref-runner` is for `cwltool`: https://github.com/common-workflow-language/cwltool/tree/master/cwlref-runner

I prefer option 1, but I'm curious to hear what others think..

**Comment by DailyDreaming** [comment]
`cwltool` is still an option if the user wishes.

**Comment by DailyDreaming** [comment]
Option 1 makes sense to me too, along with some documentation.

**Comment by diekhans** [comment]
Is there really a need for the cwl-runner to be a generic command?   Give that there will be some logical reason to chose some runner over another, it seems most straight forward to not attempt to hide it.  Just have a toil-cwl-runner, a foo-cwl-runner, etc.

If there is real demand, then make a generic symbolic like.

**Comment by DailyDreaming** [comment]
Referencing and closing #1804 as it's basically the same issue.

**Comment by DailyDreaming** [comment]
I feel like having one generic command makes more sense for toil, just `toil-cwl-runner`.  Of course keeping `cwltoil` for backwards compatibility.  If a user wants to set the default for their `cwl-runner` though, I feel like it should be done from the cwl side, not toil.  Having `toil[cwl_default]` AND `toil[cwl]` seems potentially confusing, especially for new users.

I feel like when a user installs cwltool, if they want to override the command, they should be able to specify that they want to use toil as their default `cwl-runner` with an option or config file.

**Comment by diekhans** [comment]
I would even make cwltoil a bash script that tells the user to
run toil-cwl-runner and exits with an error.  All this software
is immature, wean the off the old stuff.

Agreed, having multiple install modes will be confusing.
