### ISSUE TITLE
submitting job to mesos gives error

### ISSUE THREAD

**Issue by gijzelaerr** [BD2KGenomics/toil#2005]
Using Mesos 1.4.1 debian packages and latest toil master (7f23f6d7905c35a5e6238b97a7825c13a7e174c8). 

command:
```
$  toil-cwl-runner \
        --batchSystem=mesos \
        --preserve-environment PATH \
        --no-container \
        --logFile $(RUN)/log \
        --outdir $(RUN)/results \
        --jobStore file://$(RUN)/job_store \
        prefactor.cwl \
        jobs/job_20sb.yaml
```
output:
```
Traceback (most recent call last):
  File "/usr/local/bin/toil-cwl-runner", line 9, in <module>
    load_entry_point('toil==3.13.0a1', 'console_scripts', 'toil-cwl-runner')()
  File "/usr/local/lib/python2.7/dist-packages/toil/cwl/cwltoil.py", line 870, in main
    with Toil(options) as toil:
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 668, in __enter__
    config.setOptions(self.options)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 212, in setOptions
    setBatchOptions(self, setOption)
  File "/usr/local/lib/python2.7/dist-packages/toil/batchSystems/options.py", line 83, in setOptions
    batchSystem = factory()
  File "/usr/local/lib/python2.7/dist-packages/toil/batchSystems/registry.py", line 32, in _mesosBatchSystemFactory
    from toil.batchSystems.mesos.batchSystem import MesosBatchSystem
  File "/usr/local/lib/python2.7/dist-packages/toil/batchSystems/mesos/batchSystem.py", line 43, in <module>
    import mesos.native
  File "/usr/lib/python2.7/site-packages/mesos/native/__init__.py", line 17, in <module>
    from mesos.executor import MesosExecutorDriver
  File "/usr/lib/python2.7/site-packages/mesos/executor/__init__.py", line 17, in <module>
    from ._executor import MesosExecutorDriverImpl as MesosExecutorDriver
  File "/usr/lib/python2.7/site-packages/mesos/interface/mesos_pb2.py", line 23, in <module>
    n\x03gid\x18\x07 \x01(\t\"r\n\x06\x44\x65vice\x12\x0c\n\x04path\x18\x01 \x01(\t\x12$\n\x06number\x18\x02 \x01(\x0b\x32\x14.mesos.Device.Number\x1a\x34\n\x06Number\x12\x14\n\x0cmajor_number\x18\x01 \x02(\x04\x12\x14\n\x0cminor_number\x18\x02 \x02(\x04\"\x8f\x01\n\x0c\x44\x65viceAccess\x12\x1d\n\x06\x64\x65vice\x18\x01 \x02(\x0b\x32\r.mesos.Device\x12*\n\x06\x61\x63\x63\x65ss\x18\x02 \x02(\x0b\x32\x1a.mesos.DeviceAccess.Access\x1a\x34\n\x06\x41\x63\x63\x65ss\x12\x0c\n\x04read\x18\x01 \x01(\x08\x12\r\n\x05write\x18\x02 \x01(\x08\x12\r\n\x05mknod\x18\x03 \x01(\x08\"?\n\x0f\x44\x65viceWhitelist\x12,\n\x0f\x61llowed_devices\x18\x01 \x03(\x0b\x32\x13.mesos.DeviceAccess*\\\n\x06Status\x12\x16\n\x12\x44RIVER_NOT_STARTED\x10\x01\x12\x12\n\x0e\x44RIVER_RUNNING\x10\x02\x12\x12\n\x0e\x44RIVER_ABORTED\x10\x03\x12\x12\n\x0e\x44RIVER_STOPPED\x10\x04*\x8c\x02\n\tTaskState\x12\x10\n\x0cTASK_STAGING\x10\x06\x12\x11\n\rTASK_STARTING\x10\x00\x12\x10\n\x0cTASK_RUNNING\x10\x01\x12\x10\n\x0cTASK_KILLING\x10\x08\x12\x11\n\rTASK_FINISHED\x10\x02\x12\x0f\n\x0bTASK_FAILED\x10\x03\x12\x0f\n\x0bTASK_KILLED\x10\x04\x12\x0e\n\nTASK_ERROR\x10\x07\x12\r\n\tTASK_LOST\x10\x05\x12\x10\n\x0cTASK_DROPPED\x10\t\x12\x14\n\x10TASK_UNREACHABLE\x10\n\x12\r\n\tTASK_GONE\x10\x0b\x12\x19\n\x15TASK_GONE_BY_OPERATOR\x10\x0c\x12\x10\n\x0cTASK_UNKNOWN\x10\rB\x1a\n\x10org.apache.mesosB\x06Protos')
TypeError: __init__() got an unexpected keyword argument 'syntax'
```

OS: Ubuntu 16.04
full python package list: https://gist.github.com/gijzelaerr/a471dda7bf9f22a784d7316bb21da0b4

**Comment by ejacox** [comment]
First, both slurm and mesos can't be specified. If this doesn't fix the problem, then we will need more information about where this is running and what commands were used with the cluster tools.

**Comment by gijzelaerr** [comment]
Hi @ejacox, thanks for your reply. Sorry, that is a copy paste error, I will fix the run command.

I'm not sure what you are asking for, but I'm running this on a custom cluster running a single mesos node and 2 clients, all with the packages from the mesosphere repository. I've written some ansible scripts to set up the cluster:

https://github.com/EOSC-LOFAR/ansible

**Comment by ejacox** [comment]
Hi @gijzelaerr. Toil needs to configure the leader and workers. This is normally done by using the toil tools (e.g. "toil launch-cluster..."). See http://toil.readthedocs.io/en/3.12.0/running/amazon.html.

**Comment by gijzelaerr** [comment]
ah! So it is currently not possible to use Mesos without a supported cloud provider like Amazon?

**Comment by hannes-ucsc** [comment]
Two observations: 

1) Looks like Toil hasn't been upgraded to more recent Mesos versions in a while. The Toil appliance docker image still uses 1.0.1 (https://github.com/BD2KGenomics/toil/blame/master/docker/Dockerfile.py#L31). IIRC (I am a retired Toil maintainer) Toil does not depend explicitly on any specific version of Toil so this is not necessarily a bad sign. The Mesos folks are doing a good job in maintaining backwards compatibility with older clients. They only dropped support for 0.x clients in version 1.2.1 (http://mesos.apache.org/documentation/latest/upgrades/#upgrading-from-1-1-x-to-1-2-x). IOW, chances are that you could get your setup to work.

2) I am worried that your package list mentions protobuf==2.6.1 while the mesos-interface package for Mesos 1.4.x actually depends on protobuf 3.3.0 or higher (https://github.com/apache/mesos/blob/1.4.x/src/python/interface/setup.py.in#L29). So something must have downgraded that package. Can you try upgrading protobuf to a version that fits the version constraint in mesos-interface?

**Comment by DailyDreaming** [comment]
Thanks Hannes!

**Comment by DailyDreaming** [comment]
Thank you @hannes-ucsc .

**Comment by gijzelaerr** [comment]
hi @hannes-ucsc , thanks for this great analysis. Indeed, `protobuf `was outdated and after updating to `3.5.1` I can submit a job now.  Thanks!
