### ISSUE TITLE
Perpetual connection rejections while trying to ssh to toil cluster

### ISSUE THREAD

**Issue by gnetsanet** [BD2KGenomics/toil#2015]
Dear Developers of Toil,

I keep getting a perpetual 'Connection rejected, waiting for public SSH key to be propagated. Trying again in 10s.' while trying to launch a toil cluster and ssh into the leader node.

I can ssh into the leader independently of toil, so it appears that the issue is related to a missing image. I am wondering if there is a latest workaround than reverting to an older version of toil whose image is available in quay.?

```
docker ps
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                    NAMES
f9f44c50f9be        prom/node-exporter:0.12.0   "/bin/node_exporter -"   16 minutes ago      Up 16 minutes       0.0.0.0:9100->9100/tcp   node-exporter
```

```
Jan 11 21:30:08 ip-10-0-0-241.ec2.internal docker[1468]: Unable to find image 'quay.io/ucsc_cgl/toil:3.13.0a1' locally
Jan 11 21:30:09 ip-10-0-0-241.ec2.internal docker[1468]: Pulling repository quay.io/ucsc_cgl/toil
Jan 11 21:30:09 ip-10-0-0-241.ec2.internal docker[1468]: /usr/bin/docker: Tag 3.13.0a1 not found in repository quay.io/ucsc_cgl/toil.
```

**Comment by DailyDreaming** [comment]
Sorry, the latest docker image should be up now.  In general, if you wanted to create your own fresh toil docker image and push it to your own quay.io repo, you could clone toil and while in the /toil/ folder (containing the make file), run the following:

docker login quay.io
export TOIL_DOCKER_REGISTRY=quay.io/<your quay user name here>
export TOIL_DOCKER_NAME=toil
make push_docker

This would create a fresh docker image of that clone of toil.  More can be found here: https://github.com/BD2KGenomics/toil/blob/f462225e5ddf2848ede783f953f18fe18ccc8ff3/docs/contributing/contributing.rst under "Developing with the Toil Appliance".
