### ISSUE TITLE
Measure performance of batchputattributes vs putattributes

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#203]

**Comment by hannes-ucsc** [comment]
From EC2 and from the UCSC network

**Comment by cket** [comment]
The results from UCSC are varied. batch_put is consistently faster, but not by a predictable margin- it is anywhere from 2X to 40X faster. On average, it was ~10X faster.

**Comment by cket** [comment]
On EC2 the results are more consistent, with batch_put being 23X to 32X faster. The tasks are done so I'm closing the issue
