### ISSUE TITLE
BatchJob is a bad name

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#204]
The name "BatchJob" suggests that it is associated with the batch system. This isn't the case. Possible alternatives include PersistentJob, StoredJob, JobStoreJob etc.

**Comment by hannes-ucsc** [comment]
On 8/7 it was agreed that we use the name JobWrapper.

**Comment by benedictpaten** [comment]
I see some places batchJob has been replaced with jobWrapper, but not everywhere (e.g. in the code).

**Comment by hannes-ucsc** [comment]
I hope I caught them all in #218.
