### ISSUE TITLE
Release 3.13.0 in pip doesn't match code in github release

### ISSUE THREAD

**Issue by jsmedmar** [BD2KGenomics/toil#2044]
The code in the [commit][commit] linked to release [3.13.0][3.13.0] doesn't match that retrieved from `pip install`. I noticed this because the `displayName` feature is not available with `pip install toil==3.13.0` but it is in the 3.13.0 [commit][commit].

PIP tar md5:

    43d0b3a617747c1f05f9eea22c1b1575

Release md5:

    8ebb452a7e0ed08eea5344a1eca41cb6

[commit]: https://github.com/BD2KGenomics/toil/commit/b800392ce7f6e0a47ef90844f8a9d7fa078226c7
[3.13.0]: https://github.com/BD2KGenomics/toil/releases/tag/releases%2F3.13.0-dirty

**Comment by DailyDreaming** [comment]
@ejacox @benedictpaten Is this worth hot-fixing?  We were going to release 3.14.0 next week, which should include displayName.

**Comment by jsmedmar** [comment]
That should be good. Just wanted to point it out, maybe some problem in the release process?

**Comment by DailyDreaming** [comment]
It was my first time going through the steps and making a release so it was likely some mistake I made.  Thank you for catching the difference!

**Comment by ejacox** [comment]
Thank you @jsmedmar. We will check this in the upcoming release.
