### ISSUE TITLE
We can't afford to create one file per job

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#205]
It takes 45min to create 5000 children in the AWS job store. The creation of a file is relatively expensive in the AWS job store. I need to verify this but according to CJ there are five round trips involved in storing a file.

We cannot afford to maintain per-job state outside of the primary job store, especially if that state is written by the master. 

I have the feeling that this is all caused by the Job/BatchJob dichotomy which may simply be a bad design choice.

Once we eliminate the file-per-job problem we can go ahead and batch up to 25 items (jobs) in SimpleDB by using BatchPutAttributes instead of  PutAttributes. This will need a separate issue as batching would require delaying writing to the store. The atomicity guarantee would still hold but the durability one would be violated by this. There are additional considerations like handling reads on the same node or another one while a batch is pending.

**Comment by cket** [comment]
6 round trips required for 1 call to _makeJobWrappers, 4 of which are for storing the file: 1 initial registration of the file, then 2 (at a minimum) for the multipart upload, then another registration to update the file's version.

**Comment by cket** [comment]
Also, this happens on the worker, not the master.

**Comment by hannes-ucsc** [comment]
As discussed on 8/8, we will implement the following improvements:

Toil will not call  JobStore.create() followed by JobStore.update() when creating the wrappers, but instead invoke a single method. Alternatively, create will be changed to not persist right away. This is a commonplace pattern in the persistence layer of an application.

Secondly, we will provide batch-style methods to the JobStore API that allow for 1) persisting multiple jobs  at once and 2) saving multiple smallish files at once. The AWS job store will then implement these methods by 1) attempting to batch  SDB writes using BatchPutAttributes , 2) parallelize writing multiple batches using a thread pool and 3) inlining a small file in an SDB item as opposed to storing it in S3 and writing the version reference to SDB.

**Comment by hannes-ucsc** [comment]
See #355 and #351. Closing this one.
