### ISSUE TITLE
HTCondor extra not supported on apple computers.

### ISSUE THREAD

**Issue by DailyDreaming** [BD2KGenomics/toil#2070]
Using the command `pip install toil[all]` on apple computers tries to pip install the htcondor package, but cannot find it because it is not supported on apple computers.

**Comment by mr-c** [comment]
You can keep it in `all`, if you make a separate entry tagged with the correct environment marker: https://www.python.org/dev/peps/pep-0508/#environment-markers

**Comment by mr-c** [comment]
`htcondor; sys_platform not 'darwin'` I think

**Comment by DailyDreaming** [comment]
That is very cool and I was unaware that that existed.  Thanks @mr-c !
