### ISSUE TITLE
Toil Installation via pip -> toil command fails

### ISSUE THREAD

**Issue by kmpf** [BD2KGenomics/toil#2081]
I installed toil via:
`$ pip install toil[cwl,wdl]`

Running toil by:
`$ toil`
Or
`$ toil --help`
result in:

> Traceback (most recent call last):
>   File "/usr/bin/toil", line 11, in <module>
>     load_entry_point('toil==3.14.0', 'console_scripts', 'toil')()
>   File "/usr/lib/python2.7/site-packages/toil/utils/toilMain.py", line 16, in main
>     printHelp(modules)
>   File "/usr/lib/python2.7/site-packages/toil/utils/toilMain.py", line 62, in printHelp
>     descriptions='\n'.join("%s - %s" % (n, m.__doc__.strip()) for n, m in iteritems(modules))))
>   File "/usr/lib/python2.7/site-packages/toil/utils/toilMain.py", line 62, in <genexpr>
>     descriptions='\n'.join("%s - %s" % (n, m.__doc__.strip()) for n, m in iteritems(modules))))
> AttributeError: 'NoneType' object has no attribute 'strip'

Can this be fixed in the PyPI package?

**Comment by DailyDreaming** [comment]
I made a fix, but it'll likely be in the next release: #2082 

Thanks for catching this!
