### ISSUE TITLE
trying to run tests from git checkout on Mac laptop creates pytest errors

### ISSUE THREAD

**Issue by diekhans** [BD2KGenomics/toil#2083]
* checkout master
* create and active virtual env
* make prepare
* make develop
* TOIL_TEST_QUICK=True make

Get 1 fail test for testRealtimeLogger and 14 import errors.  See attached output.

**Comment by diekhans** [comment]
[unmodified.log](https://github.com/BD2KGenomics/toil/files/1753494/unmodified.log)

**Comment by DailyDreaming** [comment]
Same exact error here on Ubuntu.  These need requirement decorators so that they are skipped if they do not meet the dependency requirements.

**Comment by ejacox** [comment]
Closed in favor #2070
