### ISSUE TITLE
cwltoil: Too many file descriptors and filedescriptor out of range in select()

### ISSUE THREAD

**Issue by andreyto** [BD2KGenomics/toil#2087]
# Conditions when it happens:

- Large CWL workflow
- Node where `cwltoil` is executed has a lot of cores (72 cores)
- Batch system is used as a backend (Torque)

# What happens:

- First, the leader was exiting in a traceback about too many open file descriptors
- Increasing the ulimit helps initially
- Eventually, this error is produced, as the workflow progresses:
  ```
   2018-02-26 18:05:29,818 - toil.leader - WARNING - 2/L/jobOEI_uS      File "...envs/toil/lib/python2.7/site-packages/schema_salad/sourceline.py", line 157, in __exit__
  xxx.xxx 2018-02-26 18:05:29,818 MainThread WARNING toil.leader: 2/L/jobOEI_uS        raise 
  self.makeError(six.text_type(exc_value))
  2018-02-26 18:05:29,818 - toil.leader - WARNING - 2/L/jobOEI_uS        raise 
  self.makeError(six.text_type(exc_value))
  xxx.xxx 2018-02-26 18:05:29,818 MainThread WARNING toil.leader: 2/L/jobOEI_uS    
  WorkflowException: :1:1: Expression evaluation error:
  2018-02-26 18:05:29,818 - toil.leader - WARNING - 2/L/jobOEI_uS    WorkflowException: :1:1: 
  Expression evaluation error:
  xxx.xxx 2018-02-26 18:05:29,818 MainThread WARNING toil.leader: 2/L/jobOEI_uS    :1:1: f 
  filedescriptor out of range in select()
  2018-02-26 18:05:29,818 - toil.leader - WARNING - 2/L/jobOEI_uS    :1:1: filedescriptor out of range 
  in select()
  xxx.xxx 2018-02-26 18:05:29,818 MainThread WARNING toil.leader: 2/L/jobOEI_uS    
  ERROR:toil.worker:Exiting the worker because of a failed job on host yyy.yyy
  ```
- Restarting the workflow with `--restart` lets it progress some more until the next traceback like the above. Eventually, the workflow finishes OK, after one or several restarts.

# Why it probably happens:

I noticed that when `cwltoil` starts with Torque backend, it also launches multiple jobs with a `singleMachine` backend, with names something like `_cwltoil`. These are apparently CWL orchestration jobs running locally. The problem is that Toil always starts as many of these as there are cores on the master node. On a node with 72 cores and a large workflow (large scatter), these jobs completely take the node over for about a minute, to the detriment of other users. My guess is that it is there the file descriptors might be initially overcommitted. Toil does not seem to provide any option to restrict the number of cores for these jobs without simultaneously restricting the number of cores for the actual tasks with the cluster backend. And I do not have smaller nodes in this cluster.

The eventual `out of range in select()` error must be another manifestation of the file descriptor hogging. According to [this](https://github.com/ansible/ansible/issues/10157#issuecomment-73292415): `The problem with select() is that it has FD_SETSIZE hard limit for number of descriptors (1024 for Linux)`. In other words, increasing `ulimit` does not help `select()`.

Although it is not obvious that the `select()` errors come from the leader, and not the worker. Perhaps, creating an option to constraint the number of concurrent `localMachine` instances for CWL housekeeping jobs would be a good start in debugging this issue, as well as a useful feature by itself.

**Comment by mr-c** [comment]
Hello @andreyto and thanks for this detailed issue

> Perhaps, creating an option to constraint the number of concurrent localMachine instances for CWL housekeeping jobs would be a good start in debugging this issue, as well as a useful feature by itself.

I concur

**Comment by diekhans** [comment]
this appears to be within cwltoil or cwltool, as Toil proper doesn't have a WorkflowException.  It would be good if cwdtool used poll rather than select.

**Comment by mr-c** [comment]
Neither toil-cwl-runner, cwltool, nor schema_salad call `select`. Since #2134 has been merged and released I'm going to close this issue; thanks for the report!
