### ISSUE TITLE
Hot-deployment is completely undocumented.

### ISSUE THREAD

**Issue by diekhans** [BD2KGenomics/toil#2089]
The only documentation on what `hot-deployment' is

>  Hot-deployment does not work here because Toil cannot hot-deploy itself, the classic "Which came first, chicken or egg?" problem.

**Comment by jessebrennan** [comment]
Actually the whole
http://toil.readthedocs.io/en/latest/running/deploying.html section
explains hot deployment in pretty good detail.

**Comment by diekhans** [comment]
I can't find the word `hot' (agreed, it's bad terminology) or
discussion of restarting in the page.   Can you point out specifics
discussion?

**Comment by joelarmstrong** [comment]
I think remote-deployment == hot-deployment here. I like the remote-deployment terminology a bit better.

I don't think there is any mention of the script being re-deployed on restart. We could add that, though if we *really* want to document everything, we should definitely also mention that this only works on Mesos (right?).

**Comment by DailyDreaming** [comment]
Someone changed `hot-deployment` to `remote-deployment`, but only in one place.  The code still has functions saying stuff like `supportsHotDeployment()` and sprinkled throughout the comments.

**Comment by DailyDreaming** [comment]
Also, wtf is `pip install fairydust` and why is it in the `remote-deployment` explanation?

http://toil.readthedocs.io/en/latest/running/deploying.html?highlight=fairydust

**Comment by DailyDreaming** [comment]
I get that it's probably a joke PyPi repo, but I think it's just confusing.

**Comment by DailyDreaming** [comment]
I think it would be a good idea to change `remote-deployment` back to `hot-deployment`.  There's a test file that needs to be renamed, functions need to be refactored, documentation that was missed, and comments that need to be edited.  It looks like `hot-deployment` renaming to `remote-deployment` only occurred in one section, so it'd be much easier and more consistent to change back to `hot-deployment`.

**Comment by diekhans** [comment]
Main immediate concern now is having consistent user doc.  Long
term, a clean conceptual name is better.  Hot deploy means
changing while running; is not what this does. 

Change names in code is easy (well, easy in emacs, YMMV); easier
than documentation, since running tests will find typos.
Documentation has to be understandable to a wide range of users.
That is hard!!

**Comment by DailyDreaming** [comment]
I've converted everything to `remote-deployment`.  It's pretty straight-forward in PyCharm too.  I really didn't want to leave things half-way.

**Comment by hannes-ucsc** [comment]
The term "hot" was originally chosen because the user script and its dependencies are deployed at every invocation of said script. Compare this to cold deployment where the user has to deploy the user script manually to all cluster nodes, before every invocation of that script.

I don't like "remote deployment" because "deployment" already implies "remote" in most contexts. There is no "local deployment" because that is typically referred to as "installation". So while "hot" isn't exactly accurate, "remote" isn't an improvement either because it is a redundant qualifier. You may as well call it "deployment".

How about "warm deployment"? JK. How about "auto-deployment"?

**Comment by diekhans** [comment]
:-)

The problem with `hot deployment' is it has a long meaning with
hard disks being replaced without shutting things down.  That
was what I first though hot deployment was.  New jobs just got
the new code.

I really like auto-deployment!!

although magic-deployment might have a bit of a flair

**Comment by diekhans** [comment]
Work isn't done; I think this is a straight-forward doc change.  Clearing communicating concepts are important for ease of use.   Lets got with auto-deployment

(or maybe self-driving deployment)
