### ISSUE TITLE
Provisioner Refactor

### ISSUE THREAD

**Issue by ejacox** [BD2KGenomics/toil#2095]
Various issues to address for provisioners.

- [ ] set and test vpc-subnet
- [ ] zone is hard-coded for AWS
- [ ] environment variable to change image
- [ ] test SSE keys (implement them if not yet added)
- [ ] Add TOIL_<>_ZONE for azure and gce and make a consistent zone call
- [ ] Remove hard-coded 3000 port forward from coreSSH.
- [ ] The current AWS provisioner uses various adhoc methods to check on progress, e.g. 'ssh ps' to see if the docker daemon is running. This is not the most reliable method and often hangs.

┆Issue Number: TOIL-65

**Comment by DailyDreaming** [comment]
Adding to #2203 and closing this.
