### ISSUE TITLE
toilStatus uses FileJobStore.loadToilState

### ISSUE THREAD

**Issue by adderan** [BD2KGenomics/toil#211]
FileJobStore.loadToilState was deleted in commit 9f56a61044dded40705ce4a9711dc0f318496242, but toilStatus still uses it. I tried to fix this with:

rootJob = jobStore.load(config.attrib["rootJob"])
toilState = ToilState(jobStore, rootJob)

instead of:
toilState = jobStore.loadToilState()

This works some of the time, but sometimes it crashes saying that the child jobs don't exist.

**Comment by benedictpaten** [comment]
Fixed.
