### ISSUE TITLE
python dill requirement

### ISSUE THREAD

**Issue by matthdsm** [BD2KGenomics/toil#2110]
Hi,

Is there a reason for the strict version requirements in `setup.py`. I've  just come across a small issue with the dill package when using toil in a bcbio-nextgen context. The conda recipe installs the latest version of Dill (0.2.7.1), and `setup.py` requires v0.2.5. 

Are you guys open to make the req a bit more lenient?
In the mean time, I'll just open a PR with bioconda to update the recipe.

Cheers
M

**Comment by matthdsm** [comment]
ref https://github.com/bioconda/bioconda-recipes/pull/8185

**Comment by DailyDreaming** [comment]
We can update dill.  The reason for specific versioning is that because there are so many dependencies, you wouldn't want one silently updating and causing errors.

**Comment by matthdsm** [comment]
Thanks!
I'll make sure the conda recipe gets updated one this makes it into the next release.

Cheers
M
