### ISSUE TITLE
Provisioner test refactor (related to #1986)

### ISSUE THREAD

**Issue by natanlao** [BD2KGenomics/toil#2120]
`toil.test.provisioners.awsProvisionerTest` should be refactored so that a single test suite can be used interchangeably with different provisioners.

I also think `toil.test.utils.utilsTest` should be refactored so that it runs for each provisioner, but that work hasn't been approved yet. (I haven't begun work on the latter, pending approval.)

**Comment by DailyDreaming** [comment]
Duplicate of #1986.
