### ISSUE TITLE
Fix GridEngine batch system

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#213]

**Comment by jvivian** [comment]
- [x] Install Toil on PODK
- [ ] Test "hello world" user script with:  `--batchSystem=gridEngine`

**Comment by jvivian** [comment]
User script did not run with batchSystem=gridEngine.   Changed issue to "Fix GridEngine".

- [ ] Fix bugs
- [ ] Test on PODK
- [ ] Pull Request from branch

**Comment by jvivian** [comment]
I'm not sure how any of our development could have broken this, but this function (getjobexitcode): http://pastebin.com/WgC5ZDQE creates an infinite loop because it always returns `None` given that the debug line from the Popen call complains:  

`"DEBUG:toil.batchSystems.gridengine:error: job id 10181 not found"`

The complete list of DEBUG messages is as follows:
```
DEBUG:toil.batchSystems.gridengine:qsubline: ['qsub', '-b', 'y', '-terse', '-j', 'y', '-cwd', '-o', '/dev/null', '-e', '/dev/null', '-v', 'LD_LIBRARY_PATH=/opt/gridengine/lib/linux-x64:/opt/openmpi/lib:/opt/python/lib', '-hard', '-l', 'p=0.5,vf=0K,h_vmem=0K', '/pod/home/jvivian/python-2.7.3/bin/python2.7 -E /pod/home/jvivian/python-2.7.3/lib/python2.7/site-packages/toil/worker.py /pod/home/jvivian/toil 5/7/jobclsHDn']
DEBUG:toil.batchSystems.gridengine:**qsub -b y -terse -j y -cwd -o /dev/null -e /dev/null -v LD_LIBRARY_PATH=/opt/gridengine/lib/linux-x64:/opt/openmpi/lib:/opt/python/lib -hard -l p=0.5,vf=0K,h_vmem=0K /pod/home/jvivian/python-2.7.3/bin/python2.7 -E /pod/home/jvivian/python-2.7.3/lib/python2.7/site-packages/toil/worker.py /pod/home/jvivian/toil 5/7/jobclsHDn
DEBUG:toil.batchSystems.gridengine:Got the job id: 10183
DEBUG:toil.batchSystems.gridengine:sgeJobID: 10183
DEBUG:toil.batchSystems.gridengine:Jobs have been created
DEBUG:toil.batchSystems.gridengine:List of runningJobs: set([0])
DEBUG:toil.batchSystems.gridengine:['qacct', '-j', '10183']
DEBUG:toil.batchSystems.gridengine:error: job id 10183 not found

DEBUG:toil.batchSystems.gridengine:Exit status: None
```

**Comment by jvivian** [comment]
jobs are getting passed to gridengine, but they are not being run.  This may be an issue of trying to run the job from my home dir.   I'll ask Hannes if I can get access to pod-1-1 to try out this hypothesis.
