### ISSUE TITLE
toil ssh-cluster opens toil appliance

### ISSUE THREAD

**Issue by Chasearmer** [BD2KGenomics/toil#2147]
After running the following code in my terminal:
`export TOIL_APPLIANCE_SELF=quay.io/ucsc_cgl/toil:3.14.0`
`export TOIL_AWS_AMI=ami-cc0900ac`
`export TOIL_AWS_ZONE=us-west-1b`
`toil launch-cluster new-cluster --leaderNodeType t2.medium --keyPairName hi`
`toil ssh-cluster new-cluster`
This message appears:

> This is the Toil appliance. You can run your Toil script directly on the appliance, but only
in single-machine mode. Alternatively, create a Toil cluster with `toil launch-cluster`,
log into the leader of that cluster with `toil ssh-cluster` and run your Toil script there.
>
> For more information see http://toil.readthedocs.io/en/latest/
> 
> Copyright (C) 2015-2016 Regents of the University of California
> 
> Version: quay.io/ucsc_cgl/toil:3.14.0-b91dbf9bf6116879952f0a70f9a2fbbcae7e51b6
> 
> root@ip-172-31-12-42:/#

I've retried multiple times with new clusters and this appears to keep occurring. Please let me know what other details I should provide.

**Comment by DailyDreaming** [comment]
The text is misleading.  You are, in fact, inside of the cluster and can run autoscaling scripts.

**Comment by Chasearmer** [comment]
Thanks @DailyDreaming !
