### ISSUE TITLE
Add option not to generate a master public key for the AWS provisioner

### ISSUE THREAD

**Issue by wshands** [BD2KGenomics/toil#2154]
Add an option to Toil to not create a master public key for the provisioner when using autoscaling and running the pipeline from Dockstore (which calls cwl-runner) where the pipeline is running as the leader node, because cwl-runner locks the file system on the leader and creation of an ssh key is not possible. If the provisioner attempts to create the ssh key an exception will be thrown.

**Comment by diekhans** [comment]
This seems like a confusing option.  Does using cwltool mean there is no writable file system?  Can you explain the situation in more detail?
