### ISSUE TITLE
regression: CWL conformance test "simple workflow with a dynamic resource requirement"

### ISSUE THREAD

**Issue by mr-c** [BD2KGenomics/toil#2161]
https://ci.commonwl.org/job/toil-conformance/558/testReport/conformance_test_v1/0/Test_simple_workflow_with_a_dynamic_resource_requirement/

from build https://ci.commonwl.org/job/toil-conformance/558/
Changes
added encryption test (commit: b987d2e) 
Removed fileJobStore encryption test (commit: ea59818) 
Add a more robust deleter to the file job store (commit: ca93b2c)
Avoid eagerly loading all versions on AWS jobstore destruction (commit: ec231d9)

**Comment by mr-c** [comment]
So it could be https://github.com/BD2KGenomics/toil/commit/ca93b2c361c0a69d22ad2c99100af7359676f654 ?

**Comment by ejacox** [comment]
@mr-c , where can I find this test? I updated the cwltest version, but still can't find it.

**Comment by mr-c** [comment]
@ejacox `cwltest` is just a test runner; the conformance tests are listed in https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/conformance_test_v1.0.yaml

Here is the test in question: https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/conformance_test_v1.0.yaml#L1515

From https://ci.commonwl.org/job/toil-conformance/558/testReport/conformance_test_v1/0/Test_simple_workflow_with_a_dynamic_resource_requirement/ we see the command that was run inside https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/

```
cwltoil --outdir=/tmp/tmpEIkClr --quiet v1.0/dynresreq-workflow.cwl v1.0/dynresreq-job.json
```

(oops, I need to update our CI to use `toil-cwl-runner` instead of `cwltoil`)

To reproduce this test you can leave out the `--outdir=/tmp/tmpEIkClr` and `--quiet` parts.

**Comment by mr-c** [comment]
As you know, your running of the CWL conformance tests is controlled by https://github.com/BD2KGenomics/toil/blob/master/src/toil/test/cwl/cwlTest.py#L131 which is pulling in a version of the conformances tests prior to the introduction of this test: https://github.com/common-workflow-language/common-workflow-language/pull/626

**Comment by mr-c** [comment]
Drilling down on https://ci.commonwl.org/job/toil-conformance/test_results_analyzer/ we can see that this test was passing until our build 557 of toil (2018-03-28)
