### ISSUE TITLE
problems running stats with toil 3.15.0

### ISSUE THREAD

**Issue by gijzelaerr** [BD2KGenomics/toil#2188]
doing a normal local toil with the `--stats` flag, but while trying to query the job_store while the run is still going i get:
```
$ toil stats runs/run_2018-04-23-16-45-17/job_store
tshikovski 2018-04-23 17:04:24,562 MainThread INFO toil.lib.bioio: Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
tshikovski 2018-04-23 17:04:24,562 MainThread INFO toil.utils.toilStats: Parsed arguments
tshikovski 2018-04-23 17:04:24,562 MainThread INFO toil.utils.toilStats: Checking if we have files for toil
tshikovski 2018-04-23 17:04:24,562 MainThread INFO toil.utils.toilStats: Checked arguments
Traceback (most recent call last):
  File ".virtualenv/bin/toil", line 11, in <module>
    sys.exit(main())
  File "/home/gijs/Work/spiel/.virtualenv/local/lib/python2.7/site-packages/toil/utils/toilMain.py", line 34, in main
    module.main()
  File "/home/gijs/Work/spiel/.virtualenv/local/lib/python2.7/site-packages/toil/utils/toilStats.py", line 605, in main
    collatedStatsTag = processData(jobStore.config, stats)
  File "/home/gijs/Work/spiel/.virtualenv/local/lib/python2.7/site-packages/toil/utils/toilStats.py", line 547, in processData
    total_clock=stats.total_clock,
AttributeError: 'Expando' object has no attribute 'total_clock'
```

┆Issue Number: TOIL-86

**Comment by DailyDreaming** [comment]
Just tested `--stats` on a simple workflow in `3.15.0` and it seemed to work.  Do you have a short case that can reproduce the error?

**Comment by gijzelaerr** [comment]
not really a short case, but it happens in this project:

https://github.com/gijzelaerr/spiel/tree/be51fd42c55c62344da8e768d4d39258b614d0f6
I start toil like this: (`make multi`):
```
$ .virtualenv/bin/toil-cwl-runner \
		--stats \
	    --cleanWorkDir onSuccess \
		--logFile $(RUN)/log \
		--outdir $(RUN)/results \
		--jobStore file:///$(CURDIR)/$(RUN)/job_store \
		--workDir $(CURDIR)/work \
		multi.cwl \
		job.yaml
```

**Comment by gijzelaerr** [comment]
to be sure I have the latest packages I've recreated and repopulated my virtualenv but i still see this problem.

**Comment by DailyDreaming** [comment]
I think this is a problem with some misplaced imports in Toil 3.15.0 and related to #2183 (it needs a hotfix).  If that's the case, then replacing `toil[cwl]` with `toil[all]` should resolve your problem in `requirements.txt` and `Dockerfile`.  If you test it, let me know the result?  Otherwise, I can try and give it a run this afternoon.

**Comment by gijzelaerr** [comment]
will test it tomorrow. I remember now, I have to install `toil[azure]` to get it working, although i dont use azure.

**Comment by gijzelaerr** [comment]
sorry, completely forgot about this. Yes, installing `toil[all]` seems to solve this problem.

**Comment by gijzelaerr** [comment]
actually, i i encountered this problem yesterday again. If toil[cw] is already installed and toil[all] is installed afterward the problem is not solved.

**Comment by ionox0** [comment]
I've seen this while the workflow is running, but `toil stats` for me will succeed once the workflow is complete. Maybe it is supposed to work with running workflow as well

**Comment by gijzelaerr** [comment]
Im still experiencing this issue and indeed it has to to with that the job is not finished. There is a bug in the code. I'll issue a PR.
