### ISSUE TITLE
Bump subprocess32 to 3.5.0

### ISSUE THREAD

**Issue by TMiguelT** [BD2KGenomics/toil#2210]
I notice that we're using `subprocess32==3.5.0rc1`, which is an issue because it causes installation to fail on Python 3, due to this bug: https://github.com/google/python-subprocess32/issues/44

Can we bump this version? The version upgrade shouldn't do anything other than fix bugs.

**Comment by mr-c** [comment]
Fixed in https://github.com/BD2KGenomics/toil/pull/2208
