### ISSUE TITLE
Toil only supports Docker registries hosted in the .io TLD

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#2245]
https://github.com/BD2KGenomics/toil/blob/45de1029ae190b8e0bb3a4addcc7ebc7bec69173/src/toil/__init__.py#L204-L212

This seems... overly specialized. Just because docker.io and quay.io are in .io doesn't mean *every* registry is going to be in .io.

The spec url of https://docs.docker.com/registry/spec/manifest-v2-2/ given to support this British-Indian-Ocean-Territory-centric restriction doesn't seem to have anything to say about registry domain names; it's all about image manifest files.

There exist real registries in other TLDs; for example, [Gitlab operates a registry](https://docs.gitlab.com/ee/user/project/container_registry.html) at `registry.gitlab.com`.

The relevant code should be rewritten to support registries at arbitrary domain names.

┆Issue Number: TOIL-283

**Comment by DailyDreaming** [comment]
I included the wrong link in the docstring: `https://docs.docker.com/registry/spec/api`.  Fair point though, `gcr.io`, `docker.io`, and `quay.io` were the only ones I saw at the time and I think I conflated the convention with actually being part of the schema.  I'll amend that.

**Comment by DailyDreaming** [comment]
I've rewritten the functions to accommodate more exotic repos, and will create a PR once #2247 is merged.  Specifically, if you have an image in mind, I'd like to test it.
