### ISSUE TITLE
Set up continuous integration for toil-scripts

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#226]

**Comment by hannes-ucsc** [comment]
This mostly consists of coming up with

**Comment by hannes-ucsc** [comment]
@jpfeil come find @jvivian and me after scrum to discuss this.

**Comment by hannes-ucsc** [comment]
Jacob to start with the creation of minimized input files.

**Comment by jvivian** [comment]
This ticket should fall under toil-scripts not Toil.

**Comment by hannes-ucsc** [comment]
There's only noisy here. Just create a new issue in toil-scripts, link to this one from there and close this one.

**Comment by hannes-ucsc** [comment]
@jvivian to create individual tickets per pipeline.

**Comment by jvivian** [comment]
BD2KGenomics/toil-scripts#238  BD2KGenomics/toil-scripts#239
