### ISSUE TITLE
Change license to ASL

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#255]

**Comment by hannes-ucsc** [comment]
Continued from #183

**Comment by cket** [comment]
General UC copyright information:

http://policy.ucop.edu/doc/2100003/CopyrightOwnership

NIH BD2K Grant licensing info:

http://grants.nih.gov/grants/guide/rfa-files/RFA-MD-15-005.html

I'm not sure who the copyright owner is. The UC normally gets ownership and licensing rights, but the NIH grant includes specific licensing restrictions. I don't think NIH owns the copyright, so it is either CGL or the UC but I'm not sure which. 

Is there someone I can talk to get more specific information?
