### ISSUE TITLE
need to reimport from program

### ISSUE THREAD

**Issue by diekhans** [BD2KGenomics/toil#257]
The README says you need to do:

    if __name__ == '__main__':
        from toil.test.sort.scriptTreeTest_Sort import *

to
> reload the objects in the module, such that their module names will be absolute (this is necessary for the serialization that is used). 

This doesn't seem like it will work in cases were you have the program implemented as a command in  a bin directory rather than a module in a package.   Can someone give me more details on this, I might be able to come up with a better solution.  

Simple experimentation didn't produce a pickle stream with a file path in it.

**Comment by benedictpaten** [comment]
This was fixed a long time ago, we have to update the doc.

**Comment by diekhans** [comment]
Well, then reopening it to fix the doc, since it just wasted time trying to figure this out.

**Comment by benedictpaten** [comment]
This is covered by other issues. Stop meddling, we're in the middle of reorganising!

**Comment by diekhans** [comment]
Benedict Paten <notifications@github.com> writes:
> This is covered by other issues. Stop meddling, we're in the middle of
> reorganising!

I am not meddling, I am filing a ticket.

[if you close comment has indicated this, I wouldn't have re-open it]
