### ISSUE TITLE
Fix parasol job IDs

### ISSUE THREAD

**Issue by adderan** [BD2KGenomics/toil#282]
Parasol doesn't start the job ID's at zero

>self = <toil.test.batchSystems.batchSystemTest.ParasolBatchSystemTest >testMethod=testGetIssuedJobIDs>

> def testGetIssuedJobIDs(self):
>        self.batchSystem.issueBatchJob('sleep 1', memory=10, cpu=numCoresPerJob, disk=1000)
>       self.batchSystem.issueBatchJob('sleep 1', memory=10, cpu=numCoresPerJob, disk=1000)
>       self.assertEqual({0, 1}, set(self.batchSystem.getIssuedBatchJobIDs()))
>E       AssertionError: Items in the first set but not the second:
>E       0
>E       1
>E       Items in the second set but not the first:
>E       3800017
>E       3800018

**Comment by hannes-ucsc** [comment]
Glancing at the parasol source it seems that, there should be a parasol.jid somewhere that contains the next available job id. The nextJobId argument to the paraHub command seems to override the job ID.

However, I don't think our tests should assume anything how job IDs are allocated by the batch system under test. Could it be that the test needs to be improved?
