### ISSUE TITLE
Single machine batch system swallows logs?

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#288]
If exception occurs in worker,  the  message printed by leader should contain all logging done in worker if its above the configured log level. I don't *think* it does.

**Comment by hannes-ucsc** [comment]
Could it be that the log level isn't propagated to worker anymore?

**Comment by cket** [comment]
I haven't been able to replicate this, but I did confirm that log level is still propagated. Worker debug level logs are not sent back to master with the default info level debugging, but they are when logLevel is set to debug.

**Comment by hannes-ucsc** [comment]
So it's not reproducible. Closing.
