### ISSUE TITLE
Sort test leaves S3 buckets behind

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil#298]

**Comment by cket** [comment]
The "clean" flag default value was switched to 'never' when config was refactored to a full class. Setting it back to 'onSuccess' would help but both util tests run the sort test with stats, which would result in 4 buckets left behind whenever the test suite is run.

**Comment by cket** [comment]
Change clean flag's default back to "onSuccess" and fix any tests that may fail as a result
