### ISSUE TITLE
Add encryption to Azure job store

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#308]

**Comment by joelarmstrong** [comment]
Sadly Azure doesn't use server side encryption so you would need to roll your own client-side. The SDK supports client side encryption, but only for .NET, and I don't imagine that feature will ever propagate to python.

On the other hand, that means any client-side solution for Azure would work for the filesystem jobstore as well. I've heard good things about pynacl and simple-crypt, but the latter only works for python 3.0+, I think. Alternatively there is gpg, which is a lot harder to screw up, but it involves wrangling an external dependency.
