### ISSUE TITLE
parseSuiteTestOptions is not needed anymore

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#315]
... since there are no tests processing command line options anymore. IOW, `--logLevel` and `--testLength` aren't used anymore.

**Comment by hannes-ucsc** [comment]
Benedict, could you please confirm or  deny and reassign to me?

**Comment by benedictpaten** [comment]
I think it is not used anymore, the only place I see it referenced is in setupClass in the __init__.py of the test module. So, I think you are good to delete.
