### ISSUE TITLE
Worker crash on EC2

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#319]
http://pastebin.com/NgHi8MnS

**Comment by cket** [comment]
Possibly related:
https://bugs.launchpad.net/ubuntu/natty/+source/linux/+bug/854050

**Comment by cket** [comment]
Definitely related:
https://lkml.org/lkml/2014/9/30/498

**Comment by cket** [comment]
Asked on user list:
https://mail-archives.apache.org/mod_mbox/mesos-dev/201508.mbox/browser
First response pointed me to this:
https://community.nitrous.io/posts/stability-and-a-linux-oom-killer-bug

**Comment by cket** [comment]
Hannes pointed out that there is no evidence of the oom killer in our traceback. Until this happens again there isn't too much we can do, but we should keep this problem in mind. If it does occur again, we should try stopping/starting the box to recover more logs that might give us more information.

**Comment by hannes-ucsc** [comment]
We haven't observed this in a while.  Unassigned.

**Comment by hannes-ucsc** [comment]
Never occurred again. Closing.
