### ISSUE TITLE
Verify that "pip install toil" still works

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#336]
Three scenarios:

pip install toil
pip install --user toil
virtualenv venv && . venv/bin/activate && pip install toil

In each scenario, test basic functionality with toil, like running a helloWorld script.

**Comment by cket** [comment]
I started a trusty box on ec2 to test and found that I can install each, but only regular "pip install toil" results in a functional copy.

pip install --user causes:
Traceback (most recent call last):
  File "docker_test.py", line 1, in <module>
    from toil.job import Job
ImportError: No module named toil.job

virtualenv installation causes:
Traceback (most recent call last):
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/toil/worker.py", line 24, in <module>
    sys.path.remove(os.path.dirname(os.path.abspath(__file__)))
ValueError: list.remove(x): x not in list
ERROR:toil.batchSystems.singleMachine:Got exit code 1 (indicating failure) from command '/home/ubuntu/venv/bin/python -E /home/ubuntu/venv/local/lib/python2.7/site-packages/toil/worker.py /home/ubuntu/toil q/d/jobLf1pTz'.

**Comment by cket** [comment]
With hannes' help I verified that pip install --user does actually work. The virtualenv problem error is a known problem and should be fixed soon, before the release

**Comment by cket** [comment]
All three work with pip install --pre, however the current "stable" release still is broken.

**Comment by hannes-ucsc** [comment]
3.0.7 is out. Could you retest?

**Comment by cket** [comment]
All 3 work
