### ISSUE TITLE
Mesos batchsystem tests fail outside of virtualenv

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/toil#342]
This failure happens on toil-jenkins-slave (if run outside of virtualenv)

**Comment by jvivian** [comment]
Could not replicate on mesos-box, which points to a conflict on the toil-jenkins-slave.  mesos.interface is installed (as seen in `pip list`), but psutil wasn't, yet installing that didn't fix it.

I resolved the problem on toil-jenkins-slave by cloning the toil repo and executing: 
`sudo pip install -e .[mesos]` in the root dir before running the tests with:
 `python setup.py test --pytest-args "-vv src/toil/test/batchSystems/batchSystemTest.py"`.  

This allowed me to run the tests outside of virtualenv and I was not required to set the environment variables that jenkins sets up afterwards.

**Comment by jvivian** [comment]
Since this works on toil-jenkins-slave as is, I"m not really sure what resolving this entails.

**Comment by hannes-ucsc** [comment]
Hmm, I guess it's not reproducible then.
