### ISSUE TITLE
Implement inlining of files in SDB

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#355]

**Comment by joelarmstrong** [comment]
I just had a thought: does simpleDB actually support SSE? If not, then these inline files won't be encrypted, right? So only files without isProtected=True, or whatever, should be inlined.

Sorry if that was already obvious.

**Comment by hannes-ucsc** [comment]
You are right. We would need to implement client-side encryption.

**Comment by hannes-ucsc** [comment]
Post-poned until immutability of job stores is available.
