### ISSUE TITLE
Jenkins build should deploy Sphinx doc to readthedocs.org

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#356]
I am unsure if we can/should do this on unstable builds or only on stable builds.

This should be a separate Makefile target, aside from pypi and pypi_stable.

**Comment by cket** [comment]
Readthedocs recommends using github webhooks to do this. I assume we want a more selective way of publishing?

**Comment by cket** [comment]
Readthedocs now builds new documentation whenever we push to master or 3.0.x branch. The default documentation shown is from the 3.0.x branch.
