### ISSUE TITLE
Dependency test is still failing

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#357]
It's currently marked as an expected failure but I couldn't find an issue about this, so I created one.

**Comment by benedictpaten** [comment]
Thanks, I noticed this too. I think we need Glenn to take a look. I'm really not sure what the assertion that's failing means.

**Comment by hannes-ucsc** [comment]
"Assigned" to Glen. Glen, please see this as an invitation to contribute, not a mandate, of course.

**Comment by glennhickey** [comment]
This test was originally written to reproduce some fairly subtle jobtree (er, toil) bugs that were driving me nuts while developing progressive cactus.  These bugs were fixed long ago by Ben as far as I remember.  I'll take a look to see what's going on now this week.

**Comment by hannes-ucsc** [comment]
In sprint planning it was decided to remove this test.
