### ISSUE TITLE
Real-time logging to master

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#359]
I want to see some output from my jobs as they are running, so I can get an idea of what's up with them and guess at whether (and when) they are going to finish. `--logDebug` does not appear to accomplish this.

It would be nice if this also worked over the network somehow.

**Comment by hannes-ucsc** [comment]
In single-machine we should be able to do this easily. We just need to disable the capturing of stdout and stderr in the worker.

Would being restricted to single-machine be sufficient for you, Adam? Also, feel free to take the issue if you would like to

**Comment by hannes-ucsc** [comment]
The most general and light-weight solution would be a UDP listener on the leader to which the workers send all output.  UDP is ideal for this.

**Comment by benedictpaten** [comment]
I thought CJ implemented a change to worker to capture all output, using
the logging & stats framework?

**Comment by cket** [comment]
I did, but you don't see those logs until the job is finished. This ticket would enable you to see the worker logs in real-time

**Comment by hannes-ucsc** [comment]
As discussed in today's meeting, we'll use TCP instead.
