### ISSUE TITLE
"make test tests=my.module.test" doesn't work

### ISSUE THREAD

**Issue by joelarmstrong** [BD2KGenomics/toil#360]
The makefile advertises:

```
Set the 'tests' variable to run a particular test, e.g.

make test tests=toil.test.src.jobTest.JobTest
```

But that doesn't seem to work. I checked and no custom arguments seem to be passed to py.test at all.

**Comment by hannes-ucsc** [comment]
That's outdated. Assigning to John, he knows how to run individual tests. The "src" in the test command line needs to be replaced with path_to_python_file.py::class::method. John could you updated the Makefile help string to reflect that?

**Comment by hannes-ucsc** [comment]
I'm working on the Makefile right now so I'll take this one.
