### ISSUE TITLE
addToilOptions runtime error says it accepts OptionParser

### ISSUE THREAD

**Issue by adderan** [BD2KGenomics/toil#367]

**Comment by hannes-ucsc** [comment]
Alden, unless you plan on fixing this yourself, this would need a little more information on how to reproduce the problem.

**Comment by adderan** [comment]
In common.addOptions, a runtime error is thrown if anything other than an ArgumentParser is passed, but the error says it needs either an OptionParser or an ArgumentParser. I can take the issue, but I'm not sure whether we're eliminating support for OptionParser or not.

**Comment by hannes-ucsc** [comment]
@cket already eliminated optparse. Assigning to him.
