### ISSUE TITLE
Design key-per-file encryption mechanism

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#372]

**Comment by jvivian** [comment]
This basically does what we want (as previously discussed in scrum):
https://github.com/jvivian/one_off_scripts/blob/master/master_key_generator.py

**Comment by joelarmstrong** [comment]
Could we use SHA-256 instead? MD5 has only 128 bits of output (even though it is 32 characters, they are hex encoded).

**Comment by jvivian** [comment]
Good catch Joel, I've updated the code to incorporate your suggestion.
