### ISSUE TITLE
Create caching interface

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/toil#375]
Depends on #374, should obey resource limits

**Comment by benedictpaten** [comment]
Given that user files are immutable, the following is true/easy to implement:

- Deletes (which actually are not strictly immutable ops), should only occur at the end of the worker process, and are necessary only for cleanup.
- Writes are asynchronous. User access to a file being written either waits till the file is written to the jobStore, or accesses the copy of the file in the users cache if available.
- Reads check the cache first, then the global file store.

**Comment by hannes-ucsc** [comment]
I don't know why I was assigned to this. 

Also, is this really done? I have the feeling PR #397 incorrectly refers to this issue.
