### ISSUE TITLE
Port user scripts to new job store API in 3.1.0

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/toil#378]

**Comment by benedictpaten** [comment]
He John, you'll own this once PR #393 goes in. You can take a look at the modified Job.FileStore interface here: 

https://github.com/BD2KGenomics/toil/pull/397

It is considerably simpler, but will make much simpler. You'll want to use promises everywhere you previously used empty job store files.

**Comment by benedictpaten** [comment]
Now that #397 is in, you are unblocked on this.

**Comment by jvivian** [comment]
- [x] Batch Alignment
- [ ] Somatic variant calling 
- [ ] RNA Seq

**Comment by hannes-ucsc** [comment]
This issue should be associated with toil-scripts, not toil.

**Comment by hannes-ucsc** [comment]
This issue was moved to BD2KGenomics/toil-scripts#33
