### ISSUE TITLE
Research data transfer cost on Azure

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#380]

**Comment by jvivian** [comment]
Inbound is free.

| Outbound Data Transfer            	| Price         	|
|-----------------------------------	|---------------	|
| First 5 GB /Month                 	| Free          	|
| 5 GB - 10 TB 2 /Month             	| $0.087 per GB 	|
| Next 40 TB (10 - 50 TB) /Month    	| $0.083 per GB 	|
| Next 100 TB (50 - 150 TB) /Month  	| $0.07 per GB  	|
| Next 350 TB (150 - 500 TB) /Month 	| $0.05 per GB  	|

**Comment by hannes-ucsc** [comment]
We have a special price sheet with slightly lower prices.

https://docs.google.com/spreadsheets/d/18upIPRHEXy2VlcMeB-eFK7uXS-41csMXkwkbig06XrA/edit#gid=0

Service|Part|Price|Unit|Included|Overage|OveragePrice
-------|--------------------|-------------------|-------------|----------------|-----------------|-------------
Data Transfer Out - Zone 3|Q5H-00014|$1.67|10 GB|0|Q5H-00015|$1.67
Data Transfer In - Zone 1|Q5H-00016|$0.00|10 GB|0|Q5H-00017|$0.00
Data Transfer In - Zone 3|Q5H-00020|$0.00|10 GB|0|Q5H-00021|$0.00
Data Transfer In - Zone 2|Q5H-00018|$0.00|10 GB|0|Q5H-00019|$0.00
Data Transfer Out - Zone 1|Q5H-00010|$0.81|10 GB|0|Q5H-00003|$0.81
Data Transfer Out - Zone 2|Q5H-00009|$1.27|10 GB|0|Q5H-00002|$1.27
Premium Data Transfer Zone 1 - Preview|F7Z-01682|$0.79|10 GB|0|F7Z-01683|$0.79
Premium Data Transfer Zone 2 - Preview|F7Z-01689|$1.15|10 GB|0|F7Z-01688|$1.15
ADN Data Transfer|P3H-00039|$1.29|10 GB|0|P3H-00040|$1.29
