### ISSUE TITLE
Internal S3 error seemed to cause job failure

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#391]
see log here:
http://pastebin.com/xfHZtYx3
I think we should be retrying on this error

**Comment by joelarmstrong** [comment]
Unrelated, but why does it say an err

**Comment by joelarmstrong** [comment]
Oops. Misclick (on mobile). Was going to say, why is an error a 200 status code

**Comment by hannes-ucsc** [comment]
Link is dead.

**Comment by hannes-ucsc** [comment]
With the link being dead there is not information to pursue this issue. Closing. In the future please paste logs directly into the issue between using an line with triple backquotes before and after.
