### ISSUE TITLE
Change log to master behavior

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/toil#402]
the FileStore.logToMaster does not result in a log message within the worker, rather the message is transmitted back. In the case the job crashes you therefore don't see these messages in the worker log. I think logToMaster should therefore both create a log message within the worker, as well as transmitting back the log message. I also think we should be able to specify the log level of the log to master message.

**Comment by hannes-ucsc** [comment]
And add levels to logToMaster
