### ISSUE TITLE
Character values >=128 in job output crash Toil log retrieval

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#427]
My user script invokes wget, which likes to output "smart quotes" to its standard output.

This standard output gets collected by toil, put into XML, and sent back to the master (at least when I run in debug mode).

Unfortunately, `ElementTree` assumes all its strings are encoded in ASCII, when it tries to encode characters with XML entities (like &amp; and &quot;), and it panics when it sees bytes >128, because it doesn't know what entities to use:

```
Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 408, in <module>
            main()
          File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 392, in main
            jobStore.writeStatsAndLogging(ET.tostring(elementNode))
          File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
            ElementTree(element).write(file, encoding, method=method)
          File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
            serialize(write, self._root, encoding, qnames, namespaces)
          File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
            _serialize_xml(write, e, encoding, qnames, None)
          File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
            _serialize_xml(write, e, encoding, qnames, None)
          File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
            write(_escape_cdata(text, encoding))
          File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1073, in _escape_cdata
            return text.encode(encoding, "xmlcharrefreplace")
        UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 48: ordinal not in range(128)
```

Toil should assume an encoding for the standard output and standard error of the user script (probably UTF-8), and should strip or replace characters that can't later be encoded in the XML serialization format.

**Comment by hannes-ucsc** [comment]
We just need to set an encoding on the ElementTree object. Should be trivial. Or ditch ElementTree altogether and use json. The latter is preferred.

**Comment by adamnovak** [comment]
Maybe that will work? Watch out for byte values that don't correspond to
any characters in the encoding you set, though.

**Comment by benedictpaten** [comment]
There is a long standing back log issue to switch out the stats and logging
xml for a python object and use pickling (see issue #125). It's assigned to
CJ. I think it should be pushed through sooner rather than later.

**Comment by hannes-ucsc** [comment]
@cket, can you take this? Take a look at my comment at the end of the discussion to PR #438, specifically https://github.com/BD2KGenomics/toil/pull/438#issuecomment-144542067.

**Comment by hannes-ucsc** [comment]
First step is to reproduce this in a test.
```
>>> u'ü'
u'\xfc'
>>> u'Ü'
u'\xdc'
>>> u'ü'.encode('utf-8')
'\xc3\xbc'
>>> len(u'ü'.encode('utf-8'))
2
>>> u'\xfc'
u'\xfc'
```

Second step is to move to JSON for logs.

**Comment by adamnovak** [comment]
@cket did this happen to get fixed while I was away?

**Comment by hannes-ucsc** [comment]
No.
