### ISSUE TITLE
~mesosbox/shared has wrong permissions

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#432]
On toil-box it is owned by root.  On toil-leader and toil-worker it is owned by mesosbox but world writable. It should always be owned by mesosbox and rwx------ since we used it to store key files.

**Comment by cket** [comment]
PR here:
https://github.com/BD2KGenomics/cgcloud/pull/68

**Comment by hannes-ucsc** [comment]
The PR wasn't merged so this issue needs to remain open.
