### ISSUE TITLE
Mesos BatchSystem dict changing size during iteration

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#433]
I haven't had time to update Toil yet; I'm on my fork of 3a81f1114ec7f3 which includes environment serialization, and doesn't yet include the idempotent job deletion.

However, I just went to run a job on Mesos on Azure, and got this on my master:

```
Failed to call scheduler's resourceOffer
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/toil/batchSystems/mesos/batchSystem.py", line 359, in resourceOffers
    self._updateStateToRunning(offer, task)
  File "/usr/local/lib/python2.7/dist-packages/toil/batchSystems/mesos/batchSystem.py", line 310, in _updateStateToRunning
    self._deleteByJobID(int(task.task_id.value))
  File "/usr/local/lib/python2.7/dist-packages/toil/batchSystems/mesos/batchSystem.py", line 301, in _deleteByJobID
    for key, jobType in self.jobQueueList.iteritems():
RuntimeError: dictionary changed size during iteration
I0929 00:22:16.111704 31507 sched.cpp:1623] Asked to abort the driver
INFO:realtime:Aligned /tmp/tmpvAfao6/localTempDir/output.gam
I0929 00:22:16.117781 31507 sched.cpp:856] Aborting framework '20150928-184937-83886090-5050-35771-0006'
```

Is it still possible for that dictionary to change size during iteration in the current version?

**Comment by hannes-ucsc** [comment]
Did you modify anything under `src/toil/batchSystems/mesos` ?

**Comment by adamnovak** [comment]
I did indeed. I added environment serialization and deserialization, so the worker can have environment variables enabling it to connect to the job store (like the AZURE_ACCOUNT_KEY).

See here: https://github.com/adamnovak/toil/commit/bc0e05d3d1e55c19aeec13e576c349e37c409bfd
