### ISSUE TITLE
singleMachine batch system disobeys --maxCores

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#435]
I'm trying to run a job on Juggernaut. Since I got unhappy e-mails when I discovered #425 when running on Kolossus, I want to only use half the cores on the machine (32 out of 64). So I ran my job thusly, with a `--maxCores 32`:

```
time ./parallelMappingEvaluation.py ./tree_high graph_servers.tsv ./reads_high ./out_high --sample_limit=3 --batchSystem=singleMachine --maxCores 32 --kmer_size=27 --edge_max=7 2>&1 | tee log_high.txt
```

In my script, I have all my jobs set to request 16 cores. So, only two jobs should be able to run at once, right?

Wrong! What actually seems to happen is that many jobs start up, and then they run until there are only two left, and then when one of those finishes a bunch more all schedule themselves at once, and the process repeats.

I think this is by design, as described [here](https://github.com/BD2KGenomics/toil/blob/master/src/toil/batchSystems/singleMachine.py#L122-L127). In the code associated with that comment, to run a job, a worker first acquires one thread (which by default is worth 1/10 of a CPU), and then tries to grab the full number of threads needed for the requirements specified by the job. However, it collects these extra threads non-blockingly, and if it doesn't manage to collect one before the lock attempt times out, it increments an `overflow` value and continues on as if it had actually gotten use of the thread and runs the user code. The net result is that more threads worth of user code can be running at the same time than one would predict based on the --maxCores argument. Although this behavior hasn't actually caused my job to fail, it is causing it to take up more CPU on Juggernaut than I want it to, and it could potentially lead to problems ranging from thread ulimit exhaustion to angry e-mails from other system users.

Please change the single machine job system to allow a user-specified hard limit on the number of cores worth of user code that will be run at the same time.

**Comment by glennhickey** [comment]
OK, glad it's not just me!!  I've been noticing my toil jobs surpassing
--maxCores on SingleMachine too (which was never an issue on JobTree as far
as I remember).

**Comment by joelarmstrong** [comment]
Yeah, it shouldn't work this way. I can see why using the standard semaphore limits you to this type of behavior, but the correct behavior should be achievable using just a mutex & condition variable. (Or for fun/efficiency, using a custom semaphore that you can request multiple resources at a time from.)

PS: maybe the memory/cpu should somehow be acquired all at once as well, to achieve better use of resources. As it's written now, memory could be reserved for jobs that are stalled waiting for CPUs.

**Comment by joelarmstrong** [comment]
yeah, i was wondering why Glenn was running 250+ jobs at a time on kolossus... :)

**Comment by hannes-ucsc** [comment]
I'm now wondering why we did the overflow thingy. It seems silly. @jvivian, any idea?

**Comment by hannes-ucsc** [comment]
I think the intend behind overflow was that if 1 core is available and a job is to be scheduled that requires 2 cores, we would start that job anyways and utilize that core rather than let it sit idle. The problem is that we have no way of actually telling the job that it should only use 1 core initially, and no way of telling it to use the second core once it comes available.

**Comment by hannes-ucsc** [comment]
@joelarmstrong 

>PS: maybe the memory/cpu should somehow be acquired all at once as well, to achieve better use of resources. As it's written now, memory could be reserved for jobs that are stalled waiting for CPUs.

This could be done with a condition guarding two counters but I am worried about fairness, i.e. I want to avoid a stream of small jobs continually preventing a big job from being scheduled.

**Comment by hannes-ucsc** [comment]
Unless someone has a better idea, I will go with two conditions one for memory and one for cpu. This stuff if neatly isolated so it should be possible to change it later.
