### ISSUE TITLE
Test caching implementation with real world pipeline

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/toil#440]
As caching is integrated and test tests pass it is important we do some real work testing to see if it improves things.

**Comment by hannes-ucsc** [comment]
Depends on #379

**Comment by hannes-ucsc** [comment]
Depends on BD2KGenomics/toil-scripts#33

**Comment by hannes-ucsc** [comment]
@benedictpaten, @jvivian, do we still want to do this now or should this wait until @arkal's caching improvements in #586?

**Comment by hannes-ucsc** [comment]
@arkal tested caching on ProTECT pipeline and results went into Toil documentation for paper.
