### ISSUE TITLE
Implement AbstractBatchSystem.setEnv

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#441]
For details see 

https://github.com/BD2KGenomics/toil/pull/437#issuecomment-144546077

and 

https://github.com/BD2KGenomics/toil/issues/421#issuecomment-143406075

**Comment by adamnovak** [comment]
@cket how is this one going, too? I kind of need this in, so I don't have to use my own patched Mesos executor on Azure to distribute the Azure Storage credentials for the JobStore.

**Comment by hannes-ucsc** [comment]
There is no need to ask for status updates in tickets. It's a waste of time. If you want to push for certain tickets to be prioritized please feel free to join our daily scrum meetings at 11am.

**Comment by hannes-ucsc** [comment]
There should also be a toil command line option to set/export arbitrary environment variables using ``batchSystem.setEnv()``. The method signature should be ``setEnv(name,value=None)`` instead of just ``setEnv(name,value)``. If no value is provided, it will be looked up from the current environment. That way we prevent secrets from leaking out via the command line.  Optionally, the Azure job store should use ``setEnv()`` to have its credentials be communicated to the worker nodes. The latter will be complicated by the fact that the job store is instantiated before the batch system.

**Comment by hannes-ucsc** [comment]
This *must* be implemented  in single machine and Mesos, and we *should* implement it for Parasol and GridEngine.
