### ISSUE TITLE
job.fileStore.readGlobalFile() should have an option to write to a specific temp dir obtained using job.fileStore.getLocalTempDir()

### ISSUE THREAD

**Issue by arkal** [BD2KGenomics/toil#468]
if a tool requires n inputs, we need them all to be in the same dir so the dir can be mounted to /data in a docker image. We cannot assume that job.fileStore.readGlobalFile() as it is right now will read all n files into the same directory

**Comment by hannes-ucsc** [comment]
If you need the file in a different place, you should hard-link into that place.

Come to think of it: Why don't we do that in readGlobalFile() as a service. Sounds like most users will run into this problem. @benedictpaten what do you think?

**Comment by arkal** [comment]
When you use readGlobalFile you get one of 2 return values,
1. The absolute path to the cached file
2. The relative path to the file retrieved from the filestore

This means the user needs to test whether the file path is absolute before making the hard link ( I ran into this when i kept getting  OSError 18 about cross-device links).  I agree with @hannes-ucsc that it would be great if readGlobalFile did something like
```
def readGlobalFile(self, fileStoreID, outfile):
            """
            Returns a path to a local copy of the file keyed by fileStoreID. 
            The file will be read only. 
            """
            if fileStoreID in self.filesToDelete:
                raise RuntimeError("Trying to access a file in the jobStore you've deleted: %s" % fileStoreID)
            #When requesting a new file from the jobStore first check if fileStoreID
            #is a key in jobStoreFileIDToCacheLocation.
            if fileStoreID in self.jobStoreFileIDToCacheLocation:
                #IF it is, ensure it is in the temp dir

                return self.jobStoreFileIDToCacheLocation[fileStoreID]   
            else:
                #If it is not in the cache read it from the jobStore to the 
                #desired location
                localFilePath = self.getLocalTempFile()
                self.jobStore.readFile(fileStoreID, localFilePath)
                self.jobStoreFileIDToCacheLocation[fileStoreID] = localFilePath
                #Chmod to make file read only
                os.chmod(localFilePath, stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)
                return localFilePath
```

**Comment by hannes-ucsc** [comment]
Independently of whether readGlobalFile() should offer to hard-link the file, it should always return either absolute or relative paths, but not a mix. If the returned paths are relative, they should be relative to a well-known, fixed directory.

**Comment by arkal** [comment]
They are currently relative to the jobstore directory.
I'm thinking of doing something like
```
if os.path.exists(readGlobalFile_return_value):
    # Then the file was from the cache
    os.link(readGlobalFile_return_value, outfile)
else:
    # Relative path to jobstoreid
    os.link(os.path.join(jobstore_dir, readGlobalFile_return_value), outfile)
```

**Comment by benedictpaten** [comment]
The relative / absolute path is a bug. 

The path thing could be solved partially if the specified user path is always a location within a directory of subdirectory returned by getLocalTempDir(), or is a location returned by getLocalTempFile().  

I am going to proceed with adding that as an option, and fix the relative/absolute path bug.

**Comment by benedictpaten** [comment]
This is now done. I have added a few tests for it. I'd appreciate any feedback.
