### ISSUE TITLE
Link from README to Read The Docs

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#470]
Using the badge and a textual link.

**Comment by hannes-ucsc** [comment]
@cket Please don't just close issues. In a comment, link to the commit that resolves it. If there is no such commit, explain in a comment why you think the issue should be closed.

**Comment by cket** [comment]
Closed by commit 19a72a61779e80f0ad88ff5ee4ce9120ccba9309 and merged into master by commit d342cd333c0ccbc7121c4fdd7e919f92b4aa75e4
