### ISSUE TITLE
Caching logic will fault if file_size > cacheSize

### ISSUE THREAD

**Issue by arkal** [BD2KGenomics/toil#489]
Lines 680-686 in _cleanLocalTempDir 
```
            while totalCachedFileSizes > cacheSize:
                fileSize, fileStoreID =  cachedFileSizes.pop()
                filePath = self.jobStoreFileIDToCacheLocation[fileStoreID]
                self.jobStoreFileIDToCacheLocation.pop(fileStoreID)
                os.remove(filePath)
                totalCachedFileSizes -= fileSize
                assert totalCachedFileSizes >= 0
```
show that if totalCachedFileSizes > cacheSize the filePath is removed.

If a file larger than cacheSize is created, it is added to jobStoreFileIDToCacheLocation and it starts getting ```os.link```ed however the _cleanLocalTempDir will delete the file before the link is complete. If the first thing in the next job is to retrieve this file from filestore ( which it probably will be), it will attempt to get it from filestore since it is NOT in cache.

However, depending on the file size, I/O, etc, if the file is still being written asynchronously to filestore, readGlobalFile starts processing an incomplete file. 

Either _cleanLocalTempDir needs to wat for the write to complete before deleting the file (since it is the rate limiting step), of readGlobalFile should have a way of asserting the integrity of the input file before reading it (Do not read a file till it is fully in filestore)

**Comment by arkal** [comment]
#486

**Comment by benedictpaten** [comment]
Hi Arjun,

You are incorrect, I think, in thinking that this code will cause an error.
It is only run after a job is run, and before a new job is run. So it can
never occur that a file is being deleted while a link is being created. As
to the asynchronous write, it does not matter in a unix file system if the
file being read from through a file stream is deleted, as the file handle
will keep it valid until it is closed. I am not going to claim there are no
bugs, but I really need to see a working regression test (and please look
at tests/src/jobFileStoreTest.py) before you assign me an issue!

**Comment by arkal** [comment]
My code ran fine when i increased my cacheSize >> totalCachedFileSizes but kept crashing before. I tested with smaller fastqs and managed to recreate it by reducing cache size appropriately. I didn't post my code since it required a 4.5G bwa index that you don't want in a test. I'll look at the reg tests and make a new one in a similar format to yours that picks up this issue.
Sorry about that.

**Comment by benedictpaten** [comment]
Hmm, that's odd. I thought the tests were testing this case. Something is
definitely up, but not sure what. What platform were you were working on?

**Comment by arkal** [comment]
centos
```
[centos@arjun-fake-podk ~]$ uname -a
Linux arjun-fake-podk.novalocal 3.15.6-1.el6.elrepo.x86_64 #1 SMP Fri Jul 18 16:26:24 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux
[centos@arjun-fake-podk ~]$ pip show toil
---
Metadata-Version: 2.0
Name: toil
Version: 3.1.0a1.dev39
Summary: Pipeline management software for clusters.
Home-page: https://github.com/BD2KGenomics/toil
Author: Benedict Paten
Author-email: benedict@soe.usc.edu
License: UNKNOWN
Location: /usr/local/lib/python2.7/site-packages
Requires: bd2k-python-lib
[centos@arjun-fake-podk ~]$ 
```
If it helps you, I can write tests for this during my flight and get back to you later today. I just need to figure out how to catch the RuntimeError from the thread functions.

**Comment by arkal** [comment]
The Issue might be related to writing a tempfile in a localworking directory . I add this to tests/src/jobFileStoreTest.py
```
elif random.random() > 0.5:
                #Make a copy of the file in a new LocalTempDir
                tempDir = job.fileStore.getLocalTempDir()
                tempFile = '/'.join(tempDir, 'temp.txt')
                with open(tempFile, 'w') as fH:
                    fH.write(testStrings[testPrefix])
                #Write a local copy of the file using the local file
                outputFileStoreIds.append(job.fileStore.writeGlobalFile(tempFile))
```

at line 95 and everything goes wrong. I'll work on this and get back to you.
