### ISSUE TITLE
Test s3am-ing from PODK

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#509]
@arkal mentioned that PODK has an FTP server that is accessible from the outside. We should totally use that for getting data into S3 with s3am.

**Comment by jvivian** [comment]
I misunderstood Arjun's workaround to fetching files off PODK and can't really use it with S3AM.

Here are the steps I took to get S3AM up and running on PODK   (Thanks to a hotfix by Hannes that fixed an SSL issue during S3AM execution).  

1. Install python2.7 from source
2. Install Pip
    1. `https://raw.github.com/pypa/pip/master/contrib/get-pip.py && python get-pip.py --user`
3. Install virtualenv
    1. `python -m pip install virtualenv`
4.  Create virtualenv and activate
    1. `python -m virtualenv --no-site-packages venv`
    2. `source venv/bin/activate`
5. Now install S3AM
    1. `pip install --pre s3am`
6. Fix PyCurl issue
 ```
pip uninstall pycurl
export PYCURL_SSL_LIBRARY=nss
easy_install pycurl
```

7. Run S3AM!
    1. `s3am upload ...`

**Comment by jvivian** [comment]
While my test with a `touch test` file worked, when I tried to S3AM the fastq data I encountered an error: 

```
/pod/home/jvivian/venv/bin/python2.7: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by hannes-ucsc** [comment]
Try setting LD_LIBRARY_PATH to the directory containing that file.

**Comment by jvivian** [comment]
could not replicate.
