### ISSUE TITLE
Add option to prevent cleaning of work directories

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#539]

**Comment by arkal** [comment]
I'm not sure really how useful this will be. Hannes and I had a conversation about this and were talking about maybe adding a clean-temp option to toil, or maybe using a combination of --clean and --logDebug to understand that the user is debugging and would need the tempdir contents.

I, however, realized that this isn't really all that useful. Between the error logs in logDebug and the error thrown by toil, you can approximate the issue. Things I do to debug my scripts include
1. Looking at the error itself. If the error is a(n output) file not found error (the most common one i see) it means one of 2 things
      a) The tool itself failed. Add debug lines to script printing docker call to stderr, assert all files going
           into the call exist.
      b) The tool ran but the path i've provided to writeGlobalFile was wrong, chances are i've forgotten to 
          prefix the correct work directory to the filename
2. write a generic "dump-all-files-to-dir" function that will take all outputs of a job and write them to a given directory using writeGlobalFile. This way you ensure each module is creating the right input for the next step.
3. While my script is running, I keep a ```watch -d 0.5 "tree -fih /path/to/temp_dir"``` running in a window so i can monitor the activity in temp dir in my peripheral vision. Knowing the approximate size of the files before they crash can be very informative.
4. (This was specific to two tools and i got this by trial-and-error) run the command outside toil using both ```docker run -it``` and just ```docker run```. Some tools require an interactive shell to run. If the tools runs in the interactive call but not the non-interactive one, consider adding the -i option to your toil docker call.

**Comment by hannes-ucsc** [comment]
@arkal comment should form the base of a troubleshooting section in the Toil documentation.

**Comment by hannes-ucsc** [comment]
I still think there may be a valid use case for this.

**Comment by hannes-ucsc** [comment]
Dupe of #686
