### ISSUE TITLE
Mesos and single-machine treat default requirements differently

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#550]
The following user script

```
import sys
from toil.job import Job

def hello( name ):
    return "Hello, %s!" % name

if __name__ == '__main__':
    options = Job.Runner.getDefaultArgumentParser().parse_args()
    job = Job.wrapFn( hello, "world" )
    result = Job.Runner.startToil( job, options )
    assert result == 'Hello, world!'
```

passes with single machine and hangs with Mesos.

Command lines used:

```
python2.7 hello_world.py --batchSystem=mesos --mesosMaster=mesos-master:5050 aws:us-west-2:foo
python2.7 hello_world.py aws:us-west-2:foo
```

**Comment by cket** [comment]
Assuming this is on a t2.micro instance, we expect the batch system to hang/fail. Micros have 1 core while the default core value is 2. 

To communicate this behavior to the user we should keep track of the max resource offer per resource type and log a warning if we get a job with a resource requirement greater than that max offer.

**Comment by hannes-ucsc** [comment]
Sort of related to #548. That issue describes SingleMachine to actually do the right thing of hanging when a three-core workload is being run on a two-core machine. 

Also, it looks like the default defaultCores is 1, not 2 as @cket claims.

Is it possible that Mesos or the framework subtracts some fraction of a core (say .1) for itself, leaving only .9 for Toil?

**Comment by cket** [comment]
The executor and framework currently don't reserve any cores for themselves, although the executor used to reserve 0.1 cores for itself. 

Is this still running on mesos 0.22? The original reason for setting executor resource reqs was that future versions of mesos would require them, but they were so inconvenient that we removed them.

If we updated to a more recent version of mesos, its possible that the executor now automatically reserves cores for itself, causing this behavior.

**Comment by cket** [comment]
It looks like we are now using 0.25 but looking through the list of changes here:

http://mesos.apache.org/documentation/latest/upgrades/

doesn't seem to list mandatory executor resource requirements as a change. Probably still worth testing on an actual cluster, however.
