### ISSUE TITLE
Service jobs cause excessive polling on file store

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#557]
The polling loop in ServiceJob.run() polls for a file in the job store once per second and service job. I feel that this is too frequent. We should consider switching to a capped, exponential back- strategy for the polling interval. It wouldn't be too bad for a 1 hour job to be artificially extended by 30 seconds on average if the polling interval had increased to one minute.

**Comment by benedictpaten** [comment]
I'm assigning this to me, and a flag into my PR that allows this to be specified.
