### ISSUE TITLE
Azure/Mesos Failure With No Log

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#569]
Sometimes jobs on Azure with Mesos will fail without leaving any log.

Here is an example of the first job in my script, which makes a bunch of child targets, successfully making all its child targets and then failing without leaving a log.

[failNoLog.txt](https://github.com/BD2KGenomics/toil/files/41157/failNoLog.txt)

**Comment by hannes-ucsc** [comment]
Mesos redirects stderr and stdout of each task to a file of the same name. Depending how Mesos gets installed, these files could be in `/tmp`, `/var/log/mesos` or `/var/lib/mesos`.

```
sudo find / -name '*stderr*'

```

Looks like you are using Mesos 0.22.0. We're on 0.25.0 now.

**Comment by hannes-ucsc** [comment]
Feel free to provide info and reopen if needed.
