### ISSUE TITLE
Azure File Store Very Slow Download Speed

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#570]
My jobs that run on the Azure file store are hanging when downloading large files (where "large" is about 30 or 40 megabytes).

Here is a log on a singleMachine batch system with the Azure job store. It can run 2 jobs at a time (since I've set max cores to 32 and set it to use 16 cores in all my jobs), and right now those two jobs are both stuck trying to pull files out of the global file store: the cactus.tar.gz file should be 33 MB, as it was when generated using the file job store, and the snp1000g.tar.gz file should be 36 MB. It is taking far longer to download these files from the file store than it took to upload them; it's been waiting 11 minutes so far, for an overall download speed (on Kolossus, from Azure) of 0.10 MB/s or less. The line it seems to be hung in in my code is:

```
local_path = job.fileStore.readGlobalFile(index_dir_id)
```

The log from my code is here:
[logAzureStoreDebug.txt](https://github.com/BD2KGenomics/toil/files/41182/logAzureStoreDebug.txt)

It seems to work fine on the indexes for my smaller graphs, about 1-2 megabytes in size.

Unless this can get fixed quickly (or is not present in the current Toil release; I'm using master from a couple of days ago), I don't think I will be able to do my scale-up that I have planned for tomorrow.

**Comment by hannes-ucsc** [comment]
Is it just slow or outright hanging? Or is something preventing you from telling the difference? Can you see the local copy grow over time?

**Comment by hannes-ucsc** [comment]
Looks like the code path through the Azure job store branches depending on if the file is below or above 4194000 bytes in size.

**Comment by adamnovak** [comment]
I'd describe it as hanging. It didn't finish even after about an hour.

**Comment by adamnovak** [comment]
Eventually (i.e. after a few hours) it gave two message about retriable
exceptions in the job store:

NFO:realtime:Done making children
INFO:realtime:Queueing alignment of HG00096 to snp1000g lrc_kir
INFO:realtime:Uploading indexes/lrc_kir/snp1000g.tar.gz to output store...
INFO:realtime:Downloading global file c1225cca_ef85_47e0_aecb_31070889638d
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Rescued any (long) missing jobs
INFO:toil.jobStores.azureJobStore:Got a retriable exception error, trying
again
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Rescued any (long) missing jobs
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Rescued any (long) missing jobs
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Rescued any (long) missing jobs
INFO:toil.jobStores.azureJobStore:Got a retriable exception error, trying
again
INFO:toil.leader:Reissued any over long jobs
INFO:toil.leader:Rescued any (long) missing jobs

Do we have a test in the Toil tests that exercises the Azure job store's
file read and write methods?

**Comment by hannes-ucsc** [comment]
Yes

**Comment by hannes-ucsc** [comment]
I was wrong, there is no branching around the max blob size (4194000). It's a simple loop.

I ran the tests with coverage to confirm that this code is covered by tests.

Next steps: we should create a reduced example that exhibits this behavior. We need to eliminate Mesos and caching as possible causes. A stack trace would be nice too (https://wiki.python.org/moin/DebuggingWithGdb).

@benedictpaten, is there an easy way to disable caching?

**Comment by hannes-ucsc** [comment]
Running lsof on the worker process would also be helpfule.

**Comment by adamnovak** [comment]
I've managed to reproduce this with the following script:

```
#!/usr/bin/env python2.7

from toil.jobStores.azureJobStore import AzureJobStore
from toil.job import Job
import logging

def do_the_test():

    print("Starting test")

    # Set up debug logging
    logging.basicConfig(level=logging.DEBUG)

    # Make a config
    options = Job.Runner.getDefaultOptions("toilAzureTester.py")

    # Make a test job store
    # TODO: you may need different account and prefix names here
    test_store = AzureJobStore("hgvm", "teststore", config=options)

    print("Writing file")
    with test_store.writeFileStream() as (file_handle, file_id):
        # Write to a stream.
        for i in range(1024):
            for j in range(1024):
                # This should produce one megacandybar of data (~2 blocks)
                file_handle.write("Candybar\n")
                
    print("Done writing file")
    print("Reading file")
        
    # Now go and read it
    test_store.readFile(file_id, "candy.txt")

    print("Done reading file")
    

if __name__ == "__main__":
    do_the_test()
    
```

It writes the file, and then hangs reading it.

Interestingly, when the script hangs and I kill it, candy.txt exists and has 4 MB of data in it.

I think the problem is probably here: https://github.com/BD2KGenomics/toil/blob/master/src/toil/jobStores/azureJobStore.py#L189-L195

```
    def readFile(self, jobStoreFileID, localFilePath):
        try:
            with self._downloadStream(jobStoreFileID, self.files) as read_fd:
                with open(localFilePath, 'w') as write_fd:
                    write_fd.write(read_fd.read(self._maxAzureBlockBytes))
        except WindowsAzureMissingResourceError:
            raise NoSuchFileException(jobStoreFileID)
```

It looks like there's no loop in this function when there should be. It just reads one Azure block's worth of data from Azure, writes it to the local file, and then stops.

This would ordinarily just cause you to get the first 4 megs of the file instead of the whole thing, but I think it interacts with the multithreaded download logic. `_downloadStream` has a writer thread trying to dump the whole file into a stream that nobody is reading from, but which hasn't actually been closed (because the join is inside the "with" on the read end of the pipe). The main thread is waiting on `writer()` thread, which is waiting on the full pipe.

**Comment by adamnovak** [comment]
If we want to use the Azure bindings' built-in stream methods, we want `put_block_blob_from_file` which can take a ython file object to upload as described in http://azure-sdk-for-python.readthedocs.org/en/documentation/storage.html

All the get blob methods work fine on block (i.e. up to the 195 GB) blobs, and there's a `get_blob_to_file` that (presumably) can write to a Python file object.
