### ISSUE TITLE
AzureJobStore.clean() is very slow

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#584]
I'm attempting to restart a run with somewhere between several tens of thousands and hundreds of jobs in an AzureJobStore.

The first step of the restart process appears to be to "clean" the job store, which involves walking the entire job graph, in serial, before scheduling any jobs. With 100,000 jobs, and one (or more, with chunking) round-trip HTTP request to the strongly-consistent-but-slow Azure Tables system per job, all happening in serial, this could take a long time. It's already taken 25 minutes so far for me, which is time my cluster is just sitting there not doing useful work.

Ideally the cleaning process (and, if possible, all the scheduling) should be able to be done on-line, without deserializing all the jobs. It could just be implicit: if the modification timestamp on a job is earlier than the start time of the Toil run, we just fix up its retry count when we load it. At the very least the traversal should be able to be done in parallel, so we don't need to wait for the round-trip latency to the table service for every single job.

**Comment by adamnovak** [comment]
It looks like the `jobs()` method on the AzureJobStore is actually only returning the first 1000 jobs; someone didn't implement a paging loop.

**Comment by adamnovak** [comment]
It also looks like jobs may all be stored in a single partition. Since a partition may only return 500 entities per second maximum according to the Azure docs, there may be a top speed at which we can read our job store.

**Comment by hannes-ucsc** [comment]
I suggest we write a unit test that demonstrates the slowness and the incompleteness. We can skip the test on regular builds if necessary.

**Comment by adamnovak** [comment]
Alright. I'll figure out how to set up an environment that can actually run the unit tests (since they fail when they find my global user install of Toil that I use in all my scripts).
