### ISSUE TITLE
Eliminate cache requirement

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#586]
Resulting from a conversation with @arkal and @jvivian.

@arkal can explain in more detail but he's running into issues where cached files are evicted prematurely. All input, output and intermediate files involved in a single sample run of his pipeline can fit onto the disk space of a single beefy EC2 instance, yet the current caching implementation doesn't utilize that.

The cache should be shared by all concurrent workers on a machine. It should fill up the disk and evict files as late as possible. A simple heuristic for this would be to persistently track the disk requirements of the set of all concurrently running jobs on a machine and ensuring that a job's required disk space is available before it is added to that set, i.e. shortly before it is started. If not enough free space is available, files need to be evicted from the cache until it is. The persistent tracking could be done in a file with locking. The overhead of managing that file and the contention introduced by the file locking should both be negligible for the job throughput Toil currently achieves.

**Comment by arkal** [comment]
I was working on this yesterday and I was thinking of the file idea as well. Possibly, worker acquires a mutex on the file just before cleaning up the cache from a previous job (https://github.com/arkal/toil/blob/master/src/toil/worker.py#L269), it reads the last line of the file which describes the remaining usable disk space. worker then adds a new line to the file with the value of ```usable space - required disk```. When worker is done, it reaquires a mutex on the file and "returns" the space to the cache pool by writing a new line. Very hacky but i think it will work. What do you think @hannes?

**Comment by arkal** [comment]
@hannes-ucsc @benedictpaten I worked on this and I might be really close to an implementation. I hope i'm not shooting myself in the foot by showing you guys this but would you look at https://github.com/arkal/toil/commit/28518bd4b895ed45ddd055c19b792663a6542b72 and comment? I believe if  ```fileStore._jobStoreFileIDToCacheLocation``` is made global, this strategy will work.

**Comment by hannes-ucsc** [comment]
Arjun's proposal is hosted here: https://docs.google.com/document/d/1JvzZ1h3eyvoXP6gXwe6Ji9xWgUt75VR3KSoAFp9FXIA/edit#

**Comment by arkal** [comment]
If anyone is interested, you can find my working source at https://github.com/arkal/toil/tree/issues/586-eliminate-cache-requirement

**Comment by arkal** [comment]
Progress has been moved to a new branch at
https://github.com/arkal/toil/tree/issues/586a-eliminate-cache-requirement

**Comment by hannes-ucsc** [comment]
Depends on #647

**Comment by hannes-ucsc** [comment]
Depends on #649
