### ISSUE TITLE
os.sysconf('SC_PHYS_PAGES') is throwing an exception

### ISSUE THREAD

**Issue by scottfrazer** [BD2KGenomics/toil#587]
I just rebased my code on top of the latest master branch today... and I'm getting this error:

```
Traceback (most recent call last):
  File "wdltoil.py", line 1, in <module>
    from toil.job import Job
  File "/Users/sfrazer/projects/toil/src/toil/job.py", line 36, in <module>
    from toil.common import loadJobStore
  File "/Users/sfrazer/projects/toil/src/toil/common.py", line 27, in <module>
    from toil.batchSystems.singleMachine import SingleMachineBatchSystem
  File "/Users/sfrazer/projects/toil/src/toil/batchSystems/singleMachine.py", line 31, in <module>
    class SingleMachineBatchSystem(AbstractBatchSystem):
  File "/Users/sfrazer/projects/toil/src/toil/batchSystems/singleMachine.py", line 47, in SingleMachineBatchSystem
    physicalMemory = os.sysconf('SC_PAGE_SIZE') * os.sysconf('SC_PHYS_PAGES')
ValueError: unrecognized configuration name
```

It seems that for my machine SC_PHYS_PAGES is not defined:

```
Python 2.7.10 (default, Jul 13 2015, 12:05:58)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.sysconf('SC_PAGE_SIZE')
4096
>>> os.sysconf('SC_PHYS_PAGES')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: unrecognized configuration name
```

Any ideas about what I should do?

**Comment by arkal** [comment]
I saw the same error yesterday on my Macbook. I believe that variable isn't
set on osX and we should be using sysctl('HW_REALMEM') instead.. However
python os doesn't have a module for that. Ill get  ask to you if I find a
workaround.

Arjun

**Comment by scottfrazer** [comment]
Thanks @arkal, for now I just hard coded a value for `os.sysconf('SC_PHYS_PAGES')`

**Comment by arkal** [comment]
This is a good reference. What value did you give SC_PHYS_PAGES?

http://nadeausoftware.com/articles/2012/09/c_c_tip_how_get_physical_memory_size_system

**Comment by scottfrazer** [comment]
I hard-coded a value of 600,000 for SC_PHYS_PAGES.  A stop-gap, for sure, but it works

**Comment by hannes-ucsc** [comment]
Thanks to @scottfrazer for the bug report, and to @arkal for the references.
