### ISSUE TITLE
Azure job store retries forever and without delay

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#593]
Number of retries needs to be limited and there should be an exponential back-off in between. Just copy the logic from the AWS job store.

**Comment by JakeNarkizian** [comment]
check if azure already does exponential back off

**Comment by JakeNarkizian** [comment]
Azure Storage supports exponential retries, info available [`here`](https://azure.microsoft.com/en-us/documentation/articles/best-practices-retry-service-specific/#azure-storage-retry-guidelines).

**Comment by hannes-ucsc** [comment]
Find out which version this was added in. It could be that can rip out our own retry code in favor of this after we upgrade to the latest version of Python client.
