### ISSUE TITLE
Running into some resource allocation problems

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#598]
_From @dgaston on December 3, 2015 17:11_

Since there is no general help forum for Toil or Toil scripts and it is in heavy development, I thought this would be the best place to ask. I have been working on porting over my existing pipeline work to Toil due to its broad support for Mesos. I am currently running this pipeline just locally. I wanted to do something a little different because I re-use many of the same methods in different pipelines so all of the methods live in their own project and are then imported into the pipeline script where I construct the workflow and graph using wrapJobFn() to define all of the jobs and then use the addJob() method to chain them together for maximum flexibility. You can see this in this repo: https://github.com/dgaston/ddbio-ngsflow.

All of my wrapper methods are in ngsflow and the workflow-* scripts are the various pipelines. workflow-somatic-amplicon.py is the current one I am testing.

The problem I am having is that the jobs don't seem to be respecting the resource allocations. For instance I am specifying --maxCores of 4, in my configuration input I specify that BWA should use 4 cores and so that is passed to the cores keyword argument in wrapJobFn(). However when executing I have four different BWA jobs, each multithreaded to 4 threads running (4 different samples) as well as two other jobs executing. It was my understanding that in this case there should only be a single BWA job executing at a time, as each BWA job should be requesting 4 cores out of a max of 4 cores allowed to toil. I see similar issues with memory usage.

Any help would be appreciated.

_Copied from original issue: BD2KGenomics/toil-scripts#60_

**Comment by hannes-ucsc** [comment]
Hi Daniel,

If you are using Toil 3.0.7, you are probably running into #435. We just released 3.1.0 with a fix for that issue. Could you try with that version?

**Comment by dgaston** [comment]
Thanks, I was running 3.0.7. Just upgraded and something in the update gives me an error that I wasn't getting before that halts setting up the workflow (RuntimeError: Trying to pass a promise from a promising job that is not predecessor of the job receiving the promise) so I'll have to make some additional tweaks to get some values moved between jobs in a different way than I was before. I'll let you know if the update resolves the resource allocation issue.

**Comment by dgaston** [comment]
Definitely fixed the issue. I also discovered that because no additional info comes with the RuntimeError message for promises it can make it hard to debug, particularly with the way I am constructing the workflow. I made a quick local dev version of toil and printed the value of self.userFunctionName in the error message in the Job.rv() method. Definitely made it easier to debug in my case. Not sure if that is a generalizable solution or not.

**Comment by hannes-ucsc** [comment]
Could you file a PR with your improvement to Job.rv()? It sounds like a good idea.

**Comment by hannes-ucsc** [comment]
PR #610

**Comment by hannes-ucsc** [comment]
Thank you for the PR. Will take a look shortly. 

It looks like upgrading to 3.1.0 fixed this issue. Closing.
