### ISSUE TITLE
Test and scale-test support for draft-3 of the CWL 1.0 specification

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#601]
Due end of December 2015

**Comment by mr-c** [comment]
FYI, there is no "CWL 3.0" specification, but there is a "draft-3" version of the specs. We will be releasing v1.0 at BOSC/ISMB

**Comment by hannes-ucsc** [comment]
@mr-c Thanks for pointing this out. Is the title accurate now?

**Comment by mr-c** [comment]
Yep!
