### ISSUE TITLE
Documentation examples don't explain need for if name=="__main__" idiom

### ISSUE THREAD

**Issue by diekhans** [BD2KGenomics/toil#617]
very low priority

The toil examples waste mental bandwidth and continues to brainwash young minds into thinking programming means cut-n-paste instead of actually understanding what you are doing.

This is done by repeating the pointless python idiom
   if __name__=="__main__":

Which is only use when a single file is both a python module and a python command line program.  This is almost never a useful thing to do in well structured code, yet people just copy and paste this idiom without thinking.

Please, the future of humanity, or at least the part that programs, depends on leading by example.

**Comment by hannes-ucsc** [comment]
> Which is only use when a single file is both a python module and a python command line program

User scripts fall into that category. It's run by the user from the command line and imported into the worker process on each worker node.

See also #522.

**Comment by diekhans** [comment]
Ah, so in that case, it's still a documentation bug, because this isn't explained.
Since I avoid doing unnecessary things, it's wouldn't have worked.

Suggest both a paragraph explaining this and a comment in the example following
the if __main__
    # only excuted in command, not on import to worker process

protect the world from people who think they know what is going on ;-)
