### ISSUE TITLE
Indexable Promises

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#630]
I have job functions that have multiple return values (i.e. return tuples). I would like to pass one return value to one follow-on, and another return value to another follow-on. However, I can't (I don't think) take a promise for the tuple, and extract a promise for one of the elements of the tuple. I have to pass the whole promised tuple, and then extract only the item I am interested in in the consuming job.

There should be a way to index a return value promise and get a promise for that element of the value that ends up fulfilling the promise.

**Comment by hannes-ucsc** [comment]
I'm sure you have a point, but I don't completely get it. Unless @benedictpaten already knows what you mean, It'd be helpful to have sample code of what you currently have to do and what you would like to be able to do instead.

**Comment by adamnovak** [comment]
Right now I have to do something like

```
...

job.addChildJobFn(useResult1, other_job.rv())
job.addChildJobFn(useResult2, other_job.rv())

...

def useResult1(job, results1And2):
    result1 = results1And2[0]
    ...

def useResult2(job, results1And2):
    result2 = results1And2[1]
    ...

```


And I want to do:


```
...

job.addChildJobFn(useResult1, other_job.rv()[0])
job.addChildJobFn(useResult2, other_job.rv()[1])

...

def useResult1(job, result1):
    ...

def useResult2(job, result2):
    ...

```

**Comment by DailyDreaming** [comment]
This is in toil now.
