### ISSUE TITLE
Sporadic sortTest failure

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#639]
self = toil.test.sort.sortTest.SortTest testMethod=testFileMesos

src/toil/test/sort/sortTest.py:134: in _toilSort
    Job.Runner.startToil(firstJob, options)
src/toil/job.py:425: in startToil
    for jobWrapper in jobStore.jobs()}
src/toil/job.py:424: in <dictcomp>
    jobCache = {jobWrapper.jobStoreID: jobWrapper
src/toil/jobStores/fileJobStore.py:137: in jobs
    yield self.load(self._getRelativePath(os.path.join(tempDir, i)))
src/toil/jobStores/fileJobStore.py:103: in load
    self._checkJobStoreId(jobStoreID)

self = toil.jobStores.fileJobStore.FileJobStore object at 0x2b57deab1150
jobStoreID = 'l/K/jobo2Q6W5'

    def _checkJobStoreId(self, jobStoreID):
        if not self.exists(jobStoreID):
            raise NoSuchJobException(jobStoreID)
           NoSuchJobException: The job 'l/K/jobo2Q6W5' does not exist

src/toil/jobStores/fileJobStore.py:279: NoSuchJobException

**Comment by cket** [comment]
Discovered in #594. This test failed after making only documentation changes. I retested and it failed again. While looking through the changes for an explanation I found a couple typos in my comments, and when I pushed these fixes the test passed on this 3rd try. 

I didn't touch any code or even anything in the Mesos batchsystem, so it seems to me like this may be an issue in the master branch

**Comment by hannes-ucsc** [comment]
Another case?

http://jenkins.cgcloud.info/job/toil-branches/branch/releases%2F3.1.x/lastCompletedBuild/testReport/src.toil.test.sort.sortTest/SortTest/testFileSingle10000/
