### ISSUE TITLE
Parasol jobs can't find _toil_worker

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#640]
If I run a parasol job to run `_toil_worker` in the same way the Parasol batch system does, it seems like it can't find `_toil_worker` on the other end:

```
[anovak@ku toil]$ parasol add job 'env _toil_worker'
[anovak@ku toil]$ less results 
[anovak@ku toil]$ ssh ku-1-04.local cat /tmp/para556234936.err
env: _toil_worker: No such file or directory
```

This is because `_toil_worker` isn't in Parasol's PATH. I can't use the `-e PATH` option to Toil to fix this, because that makes the Toil commands longer than 256 characters, and Parasol limits the command length.

Perhaps Toil should do what Parasol recommends and put long environment variables in shell scripts that are then executed by Parasol. Alternately, perhaps it should execute _toil_worker by full path.

**Comment by hannes-ucsc** [comment]
Is Toil installed in a virtualenv on ku?

**Comment by adamnovak** [comment]
I'm not in a virtualenv when I'm running this command, nor am I in a
virtualenv when I'm trying to run the Toil script that was giving me
trouble and made me want to try this command. I have Toil installed both
with pip install --user and in a virtualenv for running the tests.

**Comment by hannes-ucsc** [comment]
If you use a virtualenv, Toil will use an absolute path to the worker entry point (`_toil_worker`).

We could always use an absolute path but then users of heterogeneous clusters will complain if their Toil is installed in different places on the cluster nodes.

You should file a bug against Parasol. 256 bytes is a joke, IMHO. There is an kernel-defined limit to command line length and Parasol should not invent arbitrary limits on top of that. A single ethernet frame can hold more bytes that that for goodness sakes.

**Comment by adamnovak** [comment]
I don't know that Parasol has a bug tracker.

**Comment by hannes-ucsc** [comment]
Closing. Feel free to reopen if the virtualenv workaround doesn't work.
