### ISSUE TITLE
Services are not stopped on Toil script failure

### ISSUE THREAD

**Issue by almussel** [BD2KGenomics/toil#644]

**Comment by hannes-ucsc** [comment]
From looking at the code I can't explain why this is happening. There's not much going on between service.start() and service.stop() in ServiceJob.run(). It would be trivial to add a `finally:` clause before service.stop() but I don't think that's it.

**Comment by benedictpaten** [comment]
I know why, it's because if the service crashes when being setup then the polling job that is waits until it sees the service established deadlocks. I'm assigning this to me.

**Comment by hannes-ucsc** [comment]
@almussel. is this still happening?

@benedictpaten, did you figure this out? The PR should target the 3.1.x branch go into a branch named issues/3.1.x/644-stop-service-on-failure.

**Comment by fnothaft** [comment]
> @almussel. is this still happening?

Yes. Running into this now, actually.

**Comment by hannes-ucsc** [comment]
This is a show-stopper for the ADAM paper.
