### ISSUE TITLE
Add support for worker clean-up to single-machine and Mesos batch systems

### ISSUE THREAD

**Issue by arkal** [BD2KGenomics/toil#651]
1. Put config.workDir and config.workflowID into a namedtuple in AbstractBatchSystem.
2. Pass this to executor
3. add a cleanup method in AbstractBatchSystem that uses this info.

**Comment by hannes-ucsc** [comment]
I modified the title a bit. Hope you don't mind. I also propose that we add a supportsWorkerCleanup() method to ABS that returns False. Mesos and SingleMachine would override it to return True. setupToil() would then ensure that CacheFileStore is only used on BSs where that method returns True. Sounds good?

**Comment by arkal** [comment]
Then it would wait till the batch system is set up to fail with an error. Can probably return sooner with an
```
if batchsystem in set(non-supported) and useSharedCache is True:
    exit with message
```
the `batchsystem in set()` can probably be a static method in abstractbatchsystem that does the same thing if you'd like to keep the logic there.
