### ISSUE TITLE
Print warning message if Mesos offers are repeatedly declined

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#669]
When offers are declined a DEBUG level log message is generated. That should be a WARNING level message. I've seen several cases where user's are dumbfounded as to why their Toil script is hanging. However, the warning needs to not be printed repeatedly, or at least not too frequently. Otherwise, it becomes noise that users ignore.

**Comment by hannes-ucsc** [comment]
The log message could be made conditional: it should only be printed if all workers are idle or if the worker being offered is idle. Something like that.

**Comment by fnothaft** [comment]
@hannes-ucsc I have a local copy with this and additional logging. I will PR it shortly.

**Comment by hannes-ucsc** [comment]
Still undecided as to whether this should also go into the 3.1.x branch.

**Comment by fnothaft** [comment]
@hannes-ucsc would you want a second pull request for that, or would you just cherrypick the commit after merge? I don't know what your workflow is for this repository.

**Comment by hannes-ucsc** [comment]
Duplicated by #679
