### ISSUE TITLE
'module' object has no attribute '__file__'

### ISSUE THREAD

**Issue by guillermo-carrasco** [BD2KGenomics/toil#673]
Hi,

I was trying to run [the first code example](http://toil.readthedocs.org/en/latest/essentials.html#scripting-quick-start) from the documentation and I got this error when creating the Job instance:

```
In [9]: j = Job.wrapFn(helloWorld, "woot")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-8c9c390cdcdc> in <module>()
----> 1 j = Job.wrapFn(helloWorld, "woot")

/Users/guillem/anaconda/envs/master/lib/python2.7/site-packages/toil/job.pyc in wrapFn(fn, *args, **kwargs)
    222         :rtype: toil.job.FunctionWrappingJob
    223         """
--> 224         return FunctionWrappingJob(fn, *args, **kwargs)
    225
    226     @staticmethod

/Users/guillem/anaconda/envs/master/lib/python2.7/site-packages/toil/job.pyc in __init__(self, userFunction, *args, **kwargs)
   1365         #TODO: Add dill support
   1366         #else use indirect method
-> 1367         self.userFunctionModule = ModuleDescriptor.forModule(userFunction.__module__).globalize()
   1368         self.userFunctionName = str(userFunction.__name__)
   1369         self._args=args

/Users/guillem/anaconda/envs/master/lib/python2.7/site-packages/toil/resource.pyc in forModule(cls, name)
    326         """
    327         module = sys.modules[name]
--> 328         filePath = os.path.abspath(module.__file__)
    329         filePath = filePath.split(os.path.sep)
    330         filePath[-1], extension = os.path.splitext(filePath[-1])
```

Any help? I did install Toil through `pip`, so its not the last development version. 

Thanks a lot!

**Comment by hannes-ucsc** [comment]
Can you post 1) the contents of your script, 2) the ouput of `ls -l` when run from the directory containing the script and 3) the command line you use to invoke the script? Also need 4) the output of `pip list`.

**Comment by guillermo-carrasco** [comment]
Oh... I'm sorry. When you said "contents of your script" something clicked in my head. I was using `IPython` interactive console to run the first example, not a separate script, thus the `__file__` error. I moved the code to a separate script and it now works. 

Thanks and sorry!

**Comment by hannes-ucsc** [comment]
No worries. I should have realized from the format of the traceback ...
