### ISSUE TITLE
Introduce concept of job name for improved diagnostic

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#677]
The task name should be logged alongside the ID whenever possible. It could default to the function name or class name but should be overridable via a keyword argument to the job factories.

**Comment by fnothaft** [comment]
+1

**Comment by hannes-ucsc** [comment]
Remove the changes introduced by #1048.

**Comment by hannes-ucsc** [comment]
Proposal: Add the ability to supply a job name with each job. This could be as a pseudo-requirement (`disk='1G', name='foo', …`) and/or as parameter to the `addChild…` and `addFollowOn…` family of methods. The job name should default to the function name. Users would typically want to add the sample UUID. At the end of a workflow invocation, Toil should print the list of failed jobs along with their name and optionally their stdout and stderr. The printout should only contain the jobs that failed during that invocation. There should also be a command line utility to produce the same listing for all failed jobs' output.

**Comment by jvivian** [comment]
@arkal and I +1 as well.   

@Jeltje — Once this is integrated, the final output of Toil will list the name of the job that failed and what UUID, which means you can quickly ascertain what subset of samples failed.
