### ISSUE TITLE
No visual indication of jobs timing out

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#68]
When a job times out the job is rerun but there is no indication as to why the job is rerun. The timeout condition is logged on the worker but the log is never displayed on the master since the job is considered a success.

**Comment by hannes-ucsc** [comment]
To reproduce, run sortTest against AwsJobStore with a jobTime of 1s, Due to the latencies of introduced by the AwsJobStore  the timeout is likely to occur.

**Comment by benedictpaten** [comment]
This is a bug in singleMachine not implementing the killJobs function. For now I will make this method properly abstract so that it fails if you attempt to use this in singleMachine mode.

**Comment by hannes-ucsc** [comment]
killJobs has since been implemented. CLosing.
