### ISSUE TITLE
A failing root job causes EOFError

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#690]
Discovered while testing #686. To replicate:
```python
options = Job.Runner.getDefaultOptions(self._getTestJobStorePath())
options.workDir = self.testDir
options.clean = "always"
options.cleanWorkDir = "onSuccess"
A = Job.wrapJobFn(tempFileTestErrorJob)
Job.Runner.startToil(A, options)
```
Where tempFileTestErrorJob is
```python
def tempFileTestErrorJob(job):
    with open(job.fileStore.getLocalTempFile(), "w") as f:
        f.write("test file retention")
    raise RuntimeError()
```
The EOF error occurs when toil tries to unpickle the root job's return value:

        #Parse out the return value from the root job
        with jobStore.readSharedFileStream("rootJobReturnValue") as fH:
            jobStoreFileID = fH.read()
        with jobStore.readFileStream(jobStoreFileID) as fH:
            rootJobReturnValue = cPickle.load(fH)  #EOF here

We should probably catch this and instead raise a toil.leader.FailedJobsException as documented

**Comment by hannes-ucsc** [comment]
+1

**Comment by jvivian** [comment]
Nice find @cket !  Does this imply that currently the root job isn't rerun via `--retryCount` ?

**Comment by jvivian** [comment]
I was getting this earlier today, and tried replace my root job with an "unfailable" job:

```
def root_start(job, input_args):
    job.addChildJobFn(parse_input_samples, input_args)
```

I'm on Toil 3.1.3 -- Any suggestions on how to figure out what it's failing on?

and I'm still getting the same error with it failing on "task 0".

**Comment by cket** [comment]
Sorry, no ideas here. It is weird that a simple job like that is failing. Is that running with --restart or on a completely new run?

**Comment by jvivian** [comment]
It happens with either.  I ended up moving to the head node I used for the Toil recompute (same version of Toil), and I _did not_ get an EOF error so I'm really puzzled now.

**Comment by hannes-ucsc** [comment]
Needs to be ported to master.

**Comment by hannes-ucsc** [comment]
Needs to be ported to master.
