### ISSUE TITLE
Revisit job tree creation and destruction

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#70]
Now that we have different storage backends, there should be a command to destroy a backend. I also think we should enforce that a --resume parameter is passed when jobTree is supposed to resume a tree. Otherwise it should fail if the persisted job tree already exists.

**Comment by cket** [comment]
The deleteJobStore callback seems to do this, but it is only used in tests so far. We could call this at the end of MainLoop if the user passes a --clean-up flag.

**Comment by hannes-ucsc** [comment]
I'd prefer a flag with an argument, e.g. with the following synopsis
`[--clean=never|onerror|always]`.

If you only do that flag, this issue wouldn't be fully taken care of. Ideally, I'd also want the `--resume` parameter mentioned above.

**Comment by hannes-ucsc** [comment]
Resolved by #190
