### ISSUE TITLE
Link fate of jobs in a service subcluster

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#706]
Depends on #703

Related to #644

1. Assume there is a Toil cluster with one or more Spark/HDFS subclusters. If one of the Spark/HDFS master processes fails, the service job representing it should also fail (#703).

2. When that service job fails, the service jobs that represent the Spark/HDFS slaves connected to that Spark/HDFS master should fail. As it is now I think the slave processes and their representative services will just keep running (this issue).

3. When the master service job fails, the driver job using it will fail.

4. On a subcluster with replication factor R, if the right combination of R Spark/HDFS workers die, a block of HDFS data is lost. This leads to driver failure but it may take a while before that situation is discovered.

5. If the driver job fails, the entire cluster should be taken down (#644).

**Comment by benedictpaten** [comment]
Working on this.. look out for the PR later today :)

**Comment by hannes-ucsc** [comment]
If this ends up being a big PR, it will probably throw a wrench in @arkal's gears and his caching PR. Unless this miraculously turns out to be a small change, I would recommend waiting with this until caching is merged, or consider this a prototype that may have to undergo large amounts of conflict resolution.

**Comment by arkal** [comment]
caching is looking so bad :( it's performing worse than regular toil and I'm looking into it.
