### ISSUE TITLE
Examples using AWS

### ISSUE THREAD

**Issue by psaffrey-illumina** [BD2KGenomics/toil#710]
Rather like the people in this thread:

https://github.com/BD2KGenomics/toil/issues/682

I'm interested in running CWL workflows through Toil with many platforms supported (SGE, LSF, AWS). The documentation mentions "Commercial clouds + Amazon Web Services (including the spot market)" but I can't find any examples of Toil workflows creating EC2 instances to use for execution. How would I do I this with a CWL workflow? If I can get a bit of help with this I'd be happy to make some recipe-style examples and make a PR to put them in the repo.

I've also tried running CWL workflows on my local SGE grid. It looks like each individual CWL job runs in a docker container invoked (I think) through cwltool sandboxjs.py:

    trynodes = (["xnodejs"], ["node"], ["docker", "run",
                                       "--attach=STDIN", "--attach=STDOUT", "--attach=STDERR",
                                       "--interactive",
                                       "--rm",
                                       "node:slim"])

this looks like there are a few constraints:

- Docker must be working and supported on each individual compute node, which means it won't work where the nodes are running operating systems that aren't fully docker compatible (like CentOS6, which has a kernel that is tool old)?
- Docker must work without needing sudo.

Is this correct?

Peter

**Comment by hannes-ucsc** [comment]
Hi Peter,

Toil currently relies on cgcloud to provision the cluster in EC2. In a nutshell, you would install and configure cgcloud-core and cgcloud-toil as described here:

https://github.com/BD2KGenomics/cgcloud/blob/master/core/README.rst
https://github.com/BD2KGenomics/cgcloud/blob/master/toil/README.rst

And then run 

`cgcloud create -IT toil-latest-box`
`cgcloud create-cluster toil ...`
`cgcloud rsync toil-leader userscript.py :`
`cgcloud ssh toil-leader`

At the moment, it is not possible to run CWL jobs on a cluster of machines. You can track our efforts on making that possible here:

https://github.com/BD2KGenomics/toil/pull/709
https://github.com/BD2KGenomics/toil/issues/711

@tetron, do you have any insight on Peter's CWL/Docker-related questions?

**Comment by tetron** [comment]
Hi @psaffrey-illumina,

You're correct that each compute node needs Docker installed and usable by the compute user (typically by putting the user it a `docker` group).  However, the code in `sandboxjs.py` you quoted is actually there to run Node.js for executing Javascript expression in the CWL document, and not running general purpose jobs.  For that, you want `job.py`.  (The `sandbox.js` code will use the node:slim docker image as a fallback if nodejs isn't installed already).

**Comment by hannes-ucsc** [comment]
@psaffrey-illumina, please reopen if you feel your question was not answered satisfactorily.
