### ISSUE TITLE
Complete draft-3 feature set for cwltoil

### ISSUE THREAD

**Issue by tetron** [BD2KGenomics/toil#712]
Implement remaining cwl draft-3 features in cwltoil:

- [x] complex scatter
- [x] multiple sources to a workflow step input
- [x] valueFrom on workflow step inputs

**Comment by tetron** [comment]
@hannes-ucsc you can assign this one to me.  I already have a branch mostly ready, so just filing the issue in order to satisfy the PR process.

**Comment by hannes-ucsc** [comment]
@tetron, that's great. Thank you!
