### ISSUE TITLE
Python3 support?

### ISSUE THREAD

**Issue by jorvis** [BD2KGenomics/toil#730]
Most of our existing code is in Python3, so I was hoping there was support for it here in Toil.  I tried installing via pip3 and everything worked fine, but when I try the Hello World example I got:

$ ./hello_world.py 
Traceback (most recent call last):
  File "./hello_world.py", line 3, in <module>
    from toil.job import Job
  File "/opt/Python-3/lib/python3.4/site-packages/toil/job.py", line 24, in <module>
    import copy_reg
ImportError: No module named 'copy_reg'

As I went through the code I see a lot of dependencies on modules like urllib2, cPickle, copy_reg and started writing conditional checks using sys.version_info to handle the little differences between them, but then realized I should probably post instead to see if there was interest or a plan already to support Python3.  I didn't want to spend the effort porting for an unsolicited pull request.

**Comment by hannes-ucsc** [comment]
Hi @jorvis, 

Support for Python 3 isn't on our immediate roadmap but that can, of course, change with more public interest in it. 

I've seen [Six](https://pythonhosted.org/six/) being used to make a codebase support both Python releases.

And we should also consider [Tox](https://tox.readthedocs.org/en/latest/) for testing.

**Comment by vsoch** [comment]
+1 for interest in this here! This would be... epic :)

**Comment by hannes-ucsc** [comment]
The Team decided to put this on the back burner so I don't think it will happen this year. But +1's indicating demand may affect our prioritization.

**Comment by vsoch** [comment]
Great! it's definitely not a deal breaker for my application - actually I've just started to use > python 3.0 for most things, and Ubuntu 14.04 still starts with (system) 2.7.6. The new LTS release has (I think) python 3.5.1. I also see a lot of issues on your board that seem much more important, so I agree with the team's decision. Anyway, thanks for the details - looking forward to python 3 support!

**Comment by humburg** [comment]
+1 I'd be interested in this as well.

**Comment by forrestzhang** [comment]
Yes, yes. Please add python3 support!

**Comment by mfiers** [comment]
+1 - this project looks very interesting - I'd love to see Py3 support!

**Comment by zero323** [comment]
If there is any interest in that I'll be he happy to give it a try.  At first glance number of required adjustments is substantial but manageable.

**Comment by vsoch** [comment]
Still interest here, +1!

**Comment by zero323** [comment]
@vsoch  #1380 - it is just a small step I guess, but at least moves this in the right direction.

**Comment by vsoch** [comment]
Awesome! I hope it's approved and merged.

**Comment by proycon** [comment]
Is there any further progress towards proper python 3 compatibility? I wanted to look into this framework but was surprised and disappointed a simple ``pip install toil`` doesn't work for Python 3.  Python 2.7 is rightfully being abandoned more and more (http://www.python3statement.org/).

**Comment by vsoch** [comment]
@proycon this thread might be a little stale - have you checked out [nextflow](https://github.com/nextflow-io/nextflow)?

**Comment by zero323** [comment]
@proycon Personally I made some further modifications to both toil (https://github.com/zero323/toil/tree/py3) and bd2k-python-lib (https://github.com/zero323/bd2k-python-lib/tree/py3) but this are mostly small things and don't touch the biggest possible obstacle which is `bytes` vs `str` (I made some attempts there, enough to execute "Hello World" but it is just poking around).

**Comment by andersgs** [comment]
+1

**Comment by stoer** [comment]
+1

**Comment by uniqueg** [comment]
+1

**Comment by fgypas** [comment]
+1

**Comment by osterrfr-crim** [comment]
+1

**Comment by JKoeb** [comment]
+1

**Comment by forrestzhang** [comment]
+1

**Comment by tinck** [comment]
+1

**Comment by genomematt** [comment]
+1

**Comment by OliverEvans96** [comment]
+1 :)

**Comment by jessebrennan** [comment]
Folks, you may be in luck. Closing in favor of #1780. Stay tuned.

**Comment by wjv** [comment]
+1 even though the work is now ongoing in #1780.

Lack of Python3 support is literally the only reason why I'm not currently evaluating Toil alongside a number of comparable-ish systems to replace our ancient in-house pipeline.

**Comment by rlim19** [comment]
+1

**Comment by RNAer** [comment]
+1 for python3 support

**Comment by xiucz** [comment]
+1 , and conda box may be a better choice than virtualenv?

**Comment by adamnovak** [comment]
We now do support Python 3, in that we expect Toil to work under it and accept bugs when running on Python 3 as very important bugs. Our CI tests now test Python 3 as well, so we can detect any breaking changes.

There are still bugs to be ironed out, but Python 3 support has overall landed.

**Comment by xiucz** [comment]
Congratulations !
