### ISSUE TITLE
Fix the API "Toil API" docs

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/toil#746]
If you build the toil docs on your local machine then the "Toil API" section of the docs does not properly populate. I think this relates to CJs recent fixes.

**Comment by hannes-ucsc** [comment]
CJ, this should be resolved by Friday. It has prio over the Google stuff.

**Comment by cket** [comment]
Can you elaborate on this issue? The docs seem to be building fine for me locally and on RTD

**Comment by jvivian** [comment]
Toil API docs build on the issues/741 branch as well.

**Comment by jvivian** [comment]
@hannes-ucsc Did you help Benedict fix this this morning? If so, @cket can close it.

**Comment by hannes-ucsc** [comment]
I'll let @benedictpaten decide.

**Comment by benedictpaten** [comment]
Yep, all fixed - sorry for false alarm.
