### ISSUE TITLE
Please add GitHub webhook to support CWL integration tests

### ISSUE THREAD

**Issue by mr-c** [BD2KGenomics/toil#762]
https://github.com/BD2KGenomics/toil/settings/hooks/new

"Payload URL" `https://ci.commonwl.org/github-webhook/`
"Content type" `application/x-www-form-urlencoded`
"Which events would you like to trigger this webhook?" `Just the push event.`

I would do it myself, but I don't have permission. Thanks!

**Comment by hannes-ucsc** [comment]
This is done. Let me know if it doesn't work.

**Comment by mr-c** [comment]
@hannes-ucsc It is working great; and the [build is now passing](http://ci.commonwl.org/job/toil-conformance/). Thanks!

**Comment by mr-c** [comment]
Feel free to use this CWL conformance badge: http://ci.commonwl.org/job/toil-conformance/badge/
