### ISSUE TITLE
Toil context manager follow-up

### ISSUE THREAD

**Issue by JakeNarkizian** [BD2KGenomics/toil#766]
remove job.FileStore from file managing heading in documentation

**Comment by JakeNarkizian** [comment]
stress that all file staging is on the leader, and make contents show file staging as a subsection

**Comment by hannes-ucsc** [comment]
In the example code, call exportFile() after run()

**Comment by hannes-ucsc** [comment]
Also add a test that tests exactly that sequence: import, run, export

**Comment by hannes-ucsc** [comment]
Have the job create an output file and return its ID such that you can export the output file rather than the input file. That would be a much more realistic scenario.

**Comment by hannes-ucsc** [comment]
Also, could you make sure in a test that staging is handled correctly when restarting workflows? We would not want to stage a file again. I suppose we need to also describe how restarts and staging interact in the documentation.
