### ISSUE TITLE
CWL Job Staging fails on clusters

### ISSUE THREAD

**Issue by dleehr** [BD2KGenomics/toil#776]
From https://github.com/BD2KGenomics/toil/blob/0951b6be6f8386da966104fb17ab9e5692fe6a6a/src/toil/cwl/cwltoil.py#L152:

class StageJob(Job):
    """File staging job to put local files into the global file store.

    This currently will break if you try and run this on a cluster because the
    main() method can't stage files before Job.Runner.startToil(), and the
    staging job could run on a compute node where it doesn't have direct access
    to the input files of the head node.

    """

Is this what #711 is for?

**Comment by hannes-ucsc** [comment]
> Is this what #711 is for?

**Comment by hannes-ucsc** [comment]
> Is this what #711 is for?

Yes
