### ISSUE TITLE
CWL conformance tests fail on PR #778

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#783]
Connected to #778

http://jenkins.cgcloud.info/job/toil-pull-requests/1068/testReport/src.toil.test.cwl.cwlTest/CWLTest/test_run_conformance/
http://jenkins.cgcloud.info/job/toil-pull-requests/1073/testReport/junit/src.toil.test.cwl.cwlTest/CWLTest/test_run_conformance/

@tetron, any idea what this could be?

**Comment by tetron** [comment]
Yes, it's pulling a docker image, and docker is printing something to stdout, which is contaminating the output of the runner (which is only supposed to print the output object JSON).  I've fixed that in cwltool and have a PR to bump the cwltool dependency.

**Comment by benedictpaten** [comment]
Thanks @tetron V. v. important to get this in soon, so we can merge the doc PR and get the paper submitted.
