### ISSUE TITLE
Error running `toil clean`

### ISSUE THREAD

**Issue by tetron** [BD2KGenomics/toil#785]
After a failed workflow, I tried toil clean, but now I'm getting this error when I try `toil clean`:

```
ubuntu@ip-172-31-24-34:~/common-workflow-language$ toil clean aws:us-west-2:peter-cwltoil-test
2016-04-13 15:36:32,632 INFO:toil.lib.bioio: Logging set at level: INFO
2016-04-13 15:36:32,632 INFO:toil.utils.toilClean: Parsed arguments
2016-04-13 15:36:32,633 INFO:toil.utils.toilClean: Checking if we have files for toil
Traceback (most recent call last):
  File "/usr/local/bin/toil", line 9, in <module>
    load_entry_point('toil==3.2.0a2.dev134', 'console_scripts', 'toil')()
  File "/usr/local/lib/python2.7/dist-packages/toil/utils/toilMain.py", line 30, in main
    module.main()
  File "/usr/local/lib/python2.7/dist-packages/toil/utils/toilClean.py", line 53, in main
    jobStore = Toil.loadOrCreateJobStore(options.jobStore)
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 501, in loadOrCreateJobStore
    return AWSJobStore.loadOrCreateJobStore(jobStoreArgs, config=config)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 117, in loadOrCreateJobStore
    return cls(region, namePrefix, config=config, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 174, in __init__
    self.filesBucket = self._getOrCreateBucket(qualify('files'), versioning=True)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 469, in _getOrCreateBucket
    bucket = self.s3.create_bucket(bucket_name, location=self.region)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 616, in create_bucket
    response.status, response.reason, body)
boto.exception.S3CreateError: S3CreateError: 409 Conflict
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>BucketAlreadyExists</Code><Message>The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.</Message><BucketName>peter-cwltoil-test--files</BucketName><RequestId>DAF5D5E6B138F1AB</RequestId><HostId>t9Fz0/fKNcxA5q7gLBuk7FMu9AxCD4AdyXMIWhWOtJVyNS8ARDxnWDQOBZdeTmpkcVtXa9brMss=</HostId></Error>
```

**Comment by hannes-ucsc** [comment]
@JakeNarkizian, I have the feeling this is caused by the Toil context manager stuff. Try to replicate it, asking @tetron for more info if necessary. Once you can replicate, create a unit tests to replicate it, commit the unit test, create PR, push the commit, then fix the issue and commit that. You can ask @cket about this procedure, he's done it before.

**Comment by JakeNarkizian** [comment]
@tetron what options did you use for running the Toil script?

**Comment by hannes-ucsc** [comment]
And, @tetron, can you try again. This really looks like an eventual inconsistency problem.

**Comment by tetron** [comment]
@hannes-ucsc it's 5 days later and `toil clean aws:us-west-2:peter-cwltoil-test` gets the same error

**Comment by tetron** [comment]
The CWL conformance tests run a series of workflows back-to-back using the same jobstore by default. This may make it more prone to eventual consistency issues, however once the jobStore gets into this state, it's impossible to clean it or otherwise recover (except by using a different jobStore) and this causes a cascade failure of subsequent CWL tests.

**Comment by tetron** [comment]
There is no S3 bucket `peter-cwltoil-test` according to the S3 management console.

**Comment by hannes-ucsc** [comment]
@tetron, the bucket name would be `peter-cwltoil-test--files`. Was the job store created using UCSC's AWS account? If so, @JakeNarkizian, could you try using boto to further narrow this down? For example, it could be that the bucket doesn't come back from ListBuckets but GetBucket might still return it. It might also be that there are unfinished multipart uploads for that bucket.

To prevent you from being blocked by this, can you change your tests to use a pseudo-random job store name? All of the existing tests in Toil append a UUID to their job store names. I also wouldn't reuse job stores for different workflows.

**Comment by tetron** [comment]
@hannes-ucsc okay, I'll try semi-random jobStore names.  I have since had a successful run where I didn't get this bug;  it passed 60/61 tests, looks like one real bug to fix in cwltoil but otherwise pretty good.

**Comment by hannes-ucsc** [comment]
Since @tetron can be unblocked by not sharing job stores  between workflows, I've removed the URGENT flag.

@JakeNarkizian and I agreed to modify AWSJobStore to not ever attempt to create anything in the `toil clean` case, which it currently does, as indicated by the call to `_getOrCreateBucket` in the backtrace, and to fix deleteJobStore to write to the registry last, not first.

`toil clean` itself should also be changed to ignore certain problems (like the absence of the shared file that stores the workflow config), just so it can get to the deleteJobStore invocation.

**Comment by hannes-ucsc** [comment]
@JakeNarkizian, our Slack convo made me think that this might require more refactoring than I feel comfortable taking on this sprint. Let's post-pone.
