### ISSUE TITLE
Make Jenkins job information public?

### ISSUE THREAD

**Issue by mr-c** [BD2KGenomics/toil#788]
Hey-o,

It would be useful for outsiders who want to be helpful to see the output of the Jenkins tests.

Here is the config I used for https://ci.commonwl.org
 
![screenshot 2016-04-13 at 17 24 06](https://cloud.githubusercontent.com/assets/1330696/14508284/04bca32c-01c7-11e6-99e5-0f6bd103081e.png)

Thanks!

**Comment by hannes-ucsc** [comment]
I know that it would be useful but the build logs may leak sensitive information, such as credentials. Our builds run on dynamically created slave VMs and interact with external cloud resources so I don't think I can make the logs public.

**Comment by hannes-ucsc** [comment]
Nice Jenkins skin, BTW.

**Comment by mr-c** [comment]
Thanks, the skin is from http://afonsof.com/jenkins-material-theme/ it was super easy to install.

Perhaps https://wiki.jenkins-ci.org/display/JENKINS/Mask+Passwords+Plugin could be used to hide the credentials?
