### ISSUE TITLE
Copy cgl-rnaseq-recompute-non-wiggle out of BD2K

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#792]

**Comment by jvivian** [comment]
To Ceph?

**Comment by hannes-ucsc** [comment]
@benedictpaten, @jvivian was not aware of this.

@jvivian A transfer to Ceph would cost too much, IMO.

**Comment by benedictpaten** [comment]
We should copy it into Jing/Melissa's AWS account. Please work with them, I know Jing is in agreement.

@hannes-ucsc : How much would a transfer to CEPH cost?

**Comment by jvivian** [comment]
>  How much would a transfer to CEPH cost?

I think only $150?

**Comment by jvivian** [comment]
I have a suspicion this ticket was made before knowing the size of the bucket, which costs ~$50 a month to host.  @benedictpaten , if you still want this moved to Melissa/Jing's account let me know.  I'll need Hannes to help Melissa give me access credentials.

**Comment by hannes-ucsc** [comment]
> I have a suspicion this ticket was made before knowing the size of the bucket

Yes. I wrongly assumed the bucket to be much bigger.

Assigning to @benedictpaten for decision. Once decision has been made, please assign back to @jvivian or close as appropriate.

**Comment by hannes-ucsc** [comment]
This issue was moved to BD2KGenomics/core-dev#3
