### ISSUE TITLE
Another wonky try: finally: in the services code

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#801]
https://github.com/BD2KGenomics/toil/commit/fb8eba9b87f4698bcd026c3f64f17338dbf0c661#diff-4eeea14b1dc6e72c2dcb9ad1471d1cf3R642

is broken, please see

https://github.com/BD2KGenomics/toil/wiki/Python-Dos-and-Don'ts#dont-piggy-back-resource-deallocation

**Comment by hannes-ucsc** [comment]
Cleared milestone prior to tomorrow's planning.

**Comment by benedictpaten** [comment]
Sorry, @hannes-ucsc , which one specifically? Line number/file would would help

**Comment by hannes-ucsc** [comment]
@benedictpaten, the line I link to in the description is the piggy-backed cleanup. It should get its own `try: except:` block or a comment explaining why the piggy-backing is ok and intended. For an explanation of what I mean by "piggy-backing" see the wiki page I link to in the description.
