### ISSUE TITLE
Logging is not being setup

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#803]
Log to master messages don't appear when running sortTest. We need a test for logToMaster functionality since we tend to keep breaking it.

**Comment by hannes-ucsc** [comment]
+1

**Comment by cket** [comment]
Regression from fb52bcedc1077077802988b43b5d3180d36c3f6b

**Comment by joelarmstrong** [comment]
Could this be affecting all logging and not just logToMaster? I'm not getting any exception tracebacks when my jobs break, except from the master failing because it detected a failed job.

**Comment by dleehr** [comment]
Also impacting cwltoil. The branch in #813 seems to fix.

**Comment by tetron** [comment]
There is a fix for setting up cwltoil logging in #806
