### ISSUE TITLE
Reorganize toil.jobStores.aws directory and add toil.jobStores.support

### ISSUE THREAD

**Issue by JakeNarkizian** [BD2KGenomics/toil#804]
All but one of the job stores (including unmarked google and ceph job stores) is represented in the `toil.jobStores` directory by a file with a title of scheme `{job store name}JobStore.py`.

AWS is represented in a subdirectory of `toil.jobStores` and the file is entitled `jobStore.py`.  Moving and renaming the AWS job store to the main jobStores directory will make it consistent with the rest of toil. 

I also propose that the contents of `toil.jobStores.aws.sdbUtils`  be moved into a new file in the jobStores directory entitled something along the lines of `support.py` As @hannes-ucsc recommended a jobStoreSupport subclass will be necessary for #722  and a support.py file is the perfect candidate.

**Comment by hannes-ucsc** [comment]
Actually, I was planning to go the other way, i.e. moving each job store into its own package such that we can split up some of the job store modules. 

@JakeNarkizian, whatever, we decide to do, don't spend time on this now. I have a giant PR going and restructuring the source tree would make it much harder. Add your `JobStoreSupport` to `abstractJobStore.py` for now. And try to keep refactorings to a minimum.

**Comment by hannes-ucsc** [comment]
… to a minimum until the big PRs have been merged.

**Comment by JakeNarkizian** [comment]
@hannes-ucsc one note: wherever the job store modules end up naming them all ```jobStore.py``` will make it more difficult to switch between job stores during development because tabs will all look the same. 
<img width="649" alt="screen shot 2016-04-29 at 2 12 52 pm" src="https://cloud.githubusercontent.com/assets/10471159/14930100/43252b6a-0e16-11e6-86d3-211500520c5f.png">

**Comment by hannes-ucsc** [comment]
PyCharm has an option to include the parent directory name in the tab if just using the file name is ambiguous.

**Comment by hannes-ucsc** [comment]
Don't think we have the time for this.
