### ISSUE TITLE
testServiceParallelRecursive hangs

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#820]
http://jenkins.cgcloud.info/job/toil-pull-requests/1148/console

This test isn't normally being run on the standard Jenkins slave instance because it only has two cores.

**Comment by benedictpaten** [comment]
Hmm, I can't repeat this error. Question: did this timeout after running the test for 90 minutes?, or was the timeout 90 minutes for running all the tests?

**Comment by benedictpaten** [comment]
PS, I assume the former, just wanted to be sure.

**Comment by hannes-ucsc** [comment]
Looking at http://jenkins.cgcloud.info/job/toil-pull-requests/buildTimeTrend, it is unlikely that testServiceParallelRecursive was crossing the cutoff simply because it was the last test to run.

**Comment by hannes-ucsc** [comment]
Will try tomorrow to replicate on my box.

**Comment by hannes-ucsc** [comment]
Can't repro.
