### ISSUE TITLE
Importing job functions does not forward descendants

### ISSUE THREAD

**Issue by almussel** [BD2KGenomics/toil#831]
If a job function is imported from a toil script module using ```from module import job_function``` syntax, the child and follow-on jobs for ```job_function``` aren't imported.

**Comment by almussel** [comment]
Using ```import module``` and ```module.job_function``` also has this problem.

**Comment by hannes-ucsc** [comment]
@almussel Do you happen to have a stack trace for this?

**Comment by almussel** [comment]
With `from toil_scripts.batch_alignment.bwa_alignment import download_shared_files` in the adam-gatk pipeline, toil gives the following error:

```
---TOIL WORKER OUTPUT LOG---
Next available file descriptor: 8
DEBUG:toil.worker:Next available file descriptor: 8
DEBUG:toil.jobStores.aws.jobStore:Loaded job 9beff25f-f9e2-4e6b-a0f3-509bacc6d9d4
Parsed jobWrapper
DEBUG:toil.worker:Parsed jobWrapper
DEBUG:toil.jobStores.aws.jobStore:Updating job 9beff25f-f9e2-4e6b-a0f3-509bacc6d9d4
Got a command to run: _toil b1d196fd-70e9-4cdb-a932-efdbe2b11da0 /home/mesosbox/toil-scripts/src toil_scripts.adam_gatk_pipeline.align_and_call
DEBUG:toil.worker:Got a command to run: _toil b1d196fd-70e9-4cdb-a932-efdbe2b11da0 /home/mesosbox/toil-scripts/src toil_scripts.adam_gatk_pipeline.align_and_call
DEBUG:toil.jobStores.aws.jobStore:Reading FileInfo(fileID=u'b1d196...e2b11da0', ownerID='d8f28a5b-9b9e-4b10-8c2c-5910389ed12a', encrypted=False, version='', previousVersion='', conte
nt='\x80\x02ctoil.jo...\x07_kwargsq"}ub.', _numContentChunks=1) bound to <toil.jobStores.aws.jobStore.AWSJobStore object at 0x7fb06721ae10> into stream.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 328, in main
    fileStore=fileStore)
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1380, in _execute
    returnValues = self._run(jobWrapper, fileStore)
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1369, in _run
    return self.run(fileStore)
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1490, in run
    userFunction = self._getUserFunction()
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1466, in _getUserFunction
    return getattr(userFunctionModule, self.userFunctionName)
AttributeError: 'module' object has no attribute 'download_url_job'
Exiting the worker because of a failed jobWrapper on host ip-172-31-25-86
ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host ip-172-31-25-86
DEBUG:toil.jobStores.aws.jobStore:Loaded job 9beff25f-f9e2-4e6b-a0f3-509bacc6d9d4
WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job 9beff25f-f9e2-4e6b-a0f3-509bacc6d9d4 to 0
```

**Comment by cket** [comment]
Thanks for the traceback @almussel ! How are you calling the script? We handle hot deployment differently depending on if you use 'python userScript.py' vs 'python module.userScript' to execute.

Also, are you installing toil-scripts on every node in the cluster?

**Comment by almussel** [comment]
I'm executing using `python -m module.userScript`, and I'm only cloning toil scripts on the leader.

**Comment by cket** [comment]
I'm trying to reproduce this with module structure based on the toil scripts module but I'm running into a separate hot deployment error. Can I see your exact traceback? I think I'm running my test slightly differently from how you are

**Comment by almussel** [comment]
I'm doing this in the adam_gatk_pipeline. Currently all the jobs are being imported as ```from module import *```. I ran into the error when I replaced them with the actual jobs called in the pipeline, like ```from batch_alignment import download_shared_files```. You could be getting something different because the imported jobs are encapsulated.

**Comment by cket** [comment]
Thanks, so are you invoking it with ```python -m toil_scripts.adam_gatk_pipeline.align_and_call```?

**Comment by almussel** [comment]
Yep, that's correct.
