### ISSUE TITLE
Updating FileInfo attributes can delete file

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#832]
When a FileInfo object is modified with non-inlined content and without rewriting the content itself, the file is mistakenly assumed to be outdated and deleted.

**Comment by hannes-ucsc** [comment]
Is there an easy way to add a test (or modify an existing test) that exposes this bug?

**Comment by cket** [comment]
There's actually a test on the google job store branch that initially accidentally exposed this bug:
http://jenkins.cgcloud.info/job/toil-pull-requests/1191
