### ISSUE TITLE
Inconsistent import/export AWS failure

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil#840]
http://jenkins.cgcloud.info/job/toil-pull-requests/1206/testReport/junit/src.toil.test.jobStores.jobStoreTest/EncryptedAWSJobStoreTest/test_importExportFile__size_Partsizeminusone__otherJobStore_Awsjobstoretest/

Maybe related to s3 consistency

**Comment by hannes-ucsc** [comment]
Yes bucket creation can take some time to populate. @JakeNarkizian, there might be issues with what S3 location (similar to EC2 region) you are hitting when you create the bucket as opposed to when you access it. Please come talk to me when you have a chance.

**Comment by hannes-ucsc** [comment]
You should probably add code in the test setup after bucket creation that loops over get_bucket() until it succeeds.
