### ISSUE TITLE
Need contributing section in docs to help people creating PRs

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/toil#849]
@jtratner opened an issue but was unaware about the rules by which PRs are formatted. Suggest we add this beneath the building & testing part of the docs.

**Comment by hannes-ucsc** [comment]
Punting for next sprint.

**Comment by natanlao** [comment]
A `CONTRIBUTING` file should be added to the project root summarizing or linking to this section in the docs. See [here](https://github.com/blog/1184-contributing-guidelines)
