### ISSUE TITLE
Job store sytax not documented

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/toil#864]
@cmarkello wanted to use the Azure job store, but the fact that to use it you need to put `azure:<account>:<container prefix>` doesn't seem to be in the documentation. I didn't find anything about the syntax for AWS either.

The syntax to invoke the different job stores, and the meaning of their configuration strings, should be prominently documented.

**Comment by hannes-ucsc** [comment]
This should be printed in the `--help` output.

Also verify that it is mentioned in the Sphinx doc.

**Comment by hannes-ucsc** [comment]
And by "this" I mean the job store syntax for every supported job store. Be sure to mention the backwards-compatibility tweak of `./foo` being equivalent to `file:./foo` and `/bar` to `file:/bar`.
