### ISSUE TITLE
Add Registry to AbstractJobStore so that uncleaned job stores can be listed

### ISSUE THREAD

**Issue by JakeNarkizian** [BD2KGenomics/toil#884]
Currently the AWS and Azure job stores maintain a registry to prevent eventual consistency issues. Beyond this concern it is a common problem where users forget to clean a job store and then run into issues later such as running out of buckets, or even incurring extra charges from a storage service.

If each job store maintains a registry we can easily implement a command line function that lists all uncleaned job stores as well as other relevant information (e.g. when the job store was created, when it was last used, etc... ).

**Comment by hannes-ucsc** [comment]
Toil needs a strongly consistent answer to the question whether a job store exists or not. The purpose of the registry domain in the AWS job store is to work around  eventual consistency of SDB domain creation.

There are simpler ways of listing existing job stores by looking for buckets, domains etc that match a certain naming pattern. No need for a registry.

I vote for closing this as won't fix.
