### ISSUE TITLE
Fix brittle and obscure assertion in jobCacheTest

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#911]
See my comments on PR #898.

https://github.com/BD2KGenomics/toil/pull/898#discussion-diff-65220948

**Comment by hannes-ucsc** [comment]
@arkal this should be very straight-forward. Any chance we can get this in soon?

**Comment by arkal** [comment]
yes, sorry that was supposed to be in an updated google job store commit. I'll get this in now
