### ISSUE TITLE
Create toil-lib project

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#922]
Move toil.lib.spark from toil into toil-lib.

Move selected functions from toil_scripts.lib from toil-scripts into toil.lib in toil-lib.

**Comment by hannes-ucsc** [comment]
@fnothaft, this is the ticket you've been asking for in today's scrum.

**Comment by fnothaft** [comment]
Thanks @hannes-ucsc! @jvivian can you link the other ticket ("generic pipelines") to this?

**Comment by jvivian** [comment]
BD2kGenomics/toil-scripts#288

**Comment by fnothaft** [comment]
@jvivian just dropped you a tome over at BD2KGenomics/toil-scripts#288.

**Comment by jvivian** [comment]
Ok, here's the plan of attack:

- I'll push 2.1 out within the next week (or so) to satiate the production team
- After that, there will be one PR where I / we refactor out **toil_scripts.lib** and **toil_scripts.tools** into its own repo, **toil-lib**, which we import from as: `from toil_lib.urls import ...` and `from toil_lib.tools.aligners import ...`. 
- After that, individual pipelines will move to their own repo (assuming no lingering PRs are touching them) as individual PRs / tickets. Toil-scripts will become a graveyard where the README redirects people to individual repos . 

The goal is to give us development flexibility — Pipelines can specify a version of **toil_lib** which will always work if `pip` installed regardless of development to **Toil** or **toil_lib**.  This means only PRs against **toil_lib** will impact people if they want the newest **toil_lib** or version of **Toil**.

Thoughts @fnothaft ?

**Comment by hannes-ucsc** [comment]
BTW: The reason we can't do `toil.lib` as we planned is that `toil` would then have to be a namespace package such that two distributions can contain it without conflict (Python is different there compared to, say, Java). This would mean that we could not have any modules in the `toil` package (only a special __init__.py) which in turn would require a largish refactor to Toil. I went that route before and its not worth it.

**Comment by fnothaft** [comment]
Overall, that sounds reasonable to me. I'm -0 on:

> * After that, individual pipelines will move to their own repo (assuming no lingering PRs are touching them) as individual PRs / tickets. Toil-scripts will become a graveyard where the README redirects people to individual repos.

But I don't have well articulated reasons for being -0. Since there's at least two big steps that we have to get through before we get to the third bullet, let me think on that bullet a bit more and see if either my discomfort goes away, or if I can articulate what doesn't sit right with me.

**Comment by hannes-ucsc** [comment]
The advantage of separating each pipeline into each project would be that each could have a different version of toil-lib and therefore toil that it depends on.

**Comment by fnothaft** [comment]
Sure, and being able to release pipelines disparately. I think my discomfort stems from how "related" workflows would be treated here. E.g., the ADAM k-mer and ADAM germline pipelines. This might be more of a discussion topic, actually: how do we define a pipeline? Is a pipeline of pipelines (like the ADAM/GATK germline pipeline, which pulls in 4 sub-pipelines) packaged separately from its constituent pipelines?

**Comment by hannes-ucsc** [comment]
The ADAM pipelines should probably stay together in one project/repo.

**Comment by fnothaft** [comment]
> The ADAM pipelines should probably stay together in one project/repo.

Sure, but the ADAM variant calling pipeline is hierarchically built out of:

* The überscript
** The core multi-sample ADAM pipeline
*** The batch alignment (bwakit) pipeline
*** The ADAM preprocessing pipeline
**** The Spark services bit (toil_lib, tho)
*** The GATK preprocessing pipeline
*** The GATK germline variant calling pipeline

So, where do the lines get drawn?

**Comment by hannes-ucsc** [comment]
Do the GATK pipelines have merrit on their own? Do you find yourself frequently having to touch a GATK bit and followed by dependent ADAM bit?

**Comment by fnothaft** [comment]
> Do the GATK pipelines have merrit on their own?

The somatic variant calling pipeline will also depend on the GATK preprocessing bit.

> Do you find yourself frequently having to touch a GATK bit and followed by dependent ADAM bit?

As in, modifying them? No, ideally that's well separated. However, if doing a bugfix in the end-to-end pipeline means that I do a bugfix in the GATK pipeline repository and then update the ADAM pipeline repository, that's a bit clunky.

**Comment by jvivian** [comment]
@hannes-ucsc and I discussed this and we think this is the way to go wrt version dependencies and conflicts.

Toil-lib will pin a specific version of Toil.  This will get updated roughly every time a new stable release of Toil comes out, complemented by a version bump in Toil-lib. 

Pipelines relying on Toil-lib as a dependency should pin a specific Toil version as well as a version of toil-lib that has the same Toil dependency.  

Pipelines `version.py` will contain a dictionary of all dependencies and tool versions:
```
required_versions = { 'Toil' : '==3.3.1' ... }
```
`setup.py` will use this dictionary for the `install_requires` section of `setup()` and print a message letting the user know they have the option to install Toil with extras, and list the specific `pip install... ` command necessary. 

Pipelines will make use of a new common lib function: `check_versions` which accepts a dictionary (from `versions.py`), in `main()` so execution of the pipeline entrypoint will validate versions.  

Reasoning:
- New users will be able to install  a pipeline into a venv and get everything necessary to run a Toil pipeline w/out running into a message telling them to deal with BPL / Toil first. One pip command in a venv and they're g2g. 
- If the user misunderstands the help message about extras and installs a wrong version of toil, or just messes up their venv in some other way, the pipeline will fail at the `check_versions` stage.
- We were hoping that the entrypoint had a version component associated with them, but we checked a couple different `virtualenv` and `pip` versions and found that pipelines relying on a specific dependency raised no exception or error if there was a version conflict (seems rather stupid). 

Appreciate any feedback or comments @fnothaft @arkal @jpfeil

**Comment by fnothaft** [comment]
At a quick glance, this SGTM.

> Pipelines `version.py` will contain a dictionary of all dependencies and tool versions:

Is this just pip dependencies? Or, when you refer to tool versions, are you saying docker container tags?

**Comment by jvivian** [comment]
Just pip dependencies, container tags should be hardcoded in the pipelines.

**Comment by fnothaft** [comment]
> Just pip dependencies, container tags should be hardcoded in the pipelines.

OK, that's what I thought. Just wanted to clarify I wasn't misreading.
