### ISSUE TITLE
Slurm currently does not support shared caching

### ISSUE THREAD

**Issue by chapmanb** [BD2KGenomics/toil#928]
Hi all -- this extracts the caching discussion from #918 (cc'ing @arkal) and provides more details so that PR can focus on Slurm.

Running cwltoil with Slurm using:
```
cwltoil --batchSystem slurm --jobStore $JOBSTORE --logFile $LOGFILE --workDir $WORKDIR --preserve-environment PATH HOME --no-container run_info-cwl-workflow/main-run_info-cwl.cwl run_info-cwl-workflow/main-run_info-cwl-samples.json
```
(The CWL is from https://s3.amazonaws.com/bcbio/cwl/test_bcbio_cwl.tar.gz but not sure this has anything to do with CWL versus toil cache usage).

After applying the fix from #910 (which masks the real error), we see:
```
node04: 2016-06-03 10:43:16,323 INFO: toil.lib.bioio: Logging set at level: INFO
node04: 2016-06-03 10:43:16,323 INFO: toil.lib.bioio: Logging to file: cwltoil.log
node04: 2016-06-03 10:43:57,411 INFO: toil.lib.bioio: Logging set at level: INFO
node04: 2016-06-03 10:43:57,412 INFO: toil.lib.bioio: Logging to file: cwltoil.log
node04: 2016-06-03 10:43:57,476 INFO: toil.jobStores.fileJobStore: Jobstore directory is: /scratch/bchapman/cwl_testing/test_bcbio_cwl/cwltoil_jobstore
node04: 2016-06-03 10:43:57,477 INFO: toil.jobStores.abstractJobStore: The workflow ID is: 'e93d192a-a3ab-4027-9902-44db0f0837ad'
node04: 2016-06-03 10:43:57,685 INFO: toil.jobStores.abstractJobStore: Unable to import 'toil.jobStores.azureJobStore'
Traceback (most recent call last):
  File "/scratch/bchapman/cwl_testing/test_bcbio_cwl/../anaconda/bin/cwltoil", line 9, in <module>
    load_entry_point('toil==3.2.0a2', 'console_scripts', 'cwltoil')()
  File "/scratch/bchapman/cwl_testing/anaconda/lib/python2.7/site-packages/toil-3.2.0a2-py2.7.egg/toil/cwl/cwltoil.py", line 595, in main
    outobj = toil.start(wf1)
  File "/scratch/bchapman/cwl_testing/anaconda/lib/python2.7/site-packages/toil-3.2.0a2-py2.7.egg/toil/common.py", line 527, in start
    userScript=rootJob.getUserScript())
  File "/scratch/bchapman/cwl_testing/anaconda/lib/python2.7/site-packages/toil-3.2.0a2-py2.7.egg/toil/common.py", line 664, in createBatchSystem
    raise RuntimeError('%s currently does not support shared caching.' % config.batchSystem)
RuntimeError: slurm currently does not support shared caching.
```
I used `--disableSharedCache` to work around the problem, but don't know if that's the best fix or what the underlying incompatibility with caching it. Happy for any suggestions. Thanks much.

**Comment by arkal** [comment]
so i'm not too familiar with slurm but looking at this, i can tell you why it's failing. With caching, what happens is Toil creates a directory toil-<workfole id> under --workDir or in the $TMPDIR and that contains the job wrapper temp dirs, and the cache. If you don't have a way of cleaning up the directory on each node,  in your batch system shutdown method, you might need to set one up since that's the only way the cache dir will get cleaned up.

To overcome the caching issue, add this to the SlurmBatchSystem Class
```
    @classmethod
    def supportsWorkerCleanup(cls):
        return True```

**Comment by chapmanb** [comment]
Arjun;
Thanks for the details, this helps a lot. It looks like supportsWorkerCleanup is also set to false on the SGE integration as well, which is likely the origin of this in the SLURM implementation so we're going to run into this with other batch systems. If workDir (or tempDir, I'm not sure which it uses) is on a shared filesystem, then we should be able to use caching -- is that right? If so, is there any flag or method to tell Toil that we're good to go with a shared cache because it can cleanup on the shared filesystem? It sounds like using shared cache is a good idea, so this seems like the best approach to support it. Thanks again for the discussion.

**Comment by hannes-ucsc** [comment]
@arkal, we might need to disable caching automatically if the batch system does not support worker clean-up. I thought we had that already implemented?

**Comment by hannes-ucsc** [comment]
Either we automatically disable caching on those batch systems, or we mention in the exception message to rerun with --disableSharedCaching.

**Comment by hannes-ucsc** [comment]
@chapmanb 

> After applying the fix from #910 (which masks the real error), we see:

Please file a ticket about that specific issue. I agree that there is problem but disagree with your fix (I think the `try:` needs to be moved down one line).

**Comment by arkal** [comment]
Hey Brad,

Really, shared caching works on all batch systems. The reason we've set supportsWorkerCleanup to False on SGE is because we couldn't think of a way to cleanup node-specific local work dirs in the SGE environment (because Toil doesn't track which nodes were touched during the run). You can see how we handled single machine and Mesos in their shutdown methods.

@hannes-ucsc , I remember a discussion where we decided not to directly disable caching. I'll add the "please use the --disableSharedCaching flag to run toil" line to the error message

**Comment by hannes-ucsc** [comment]
> Really, shared caching works on all batch systems

Then why do we raise the exception?

**Comment by chapmanb** [comment]
Arjun and Hannes;
Thanks for the discussion. From reading the code, it seems like we could use the standard worker cleanup:

https://github.com/BD2KGenomics/toil/blob/616aade0da9754011ac98bc8c493a988a369cf4f/src/toil/batchSystems/abstractBatchSystem.py#L283

as long as workDir is on a shared filesystem since all the nodes will write there. Do you have any thoughts how to best specify if we're using a shared filesystem (and can use cleanup) versus local (and we don't know how to cleanup)? That seems like the cleanest way to go, rather than turning off caching entirely for all SLURM runs.

**Comment by hannes-ucsc** [comment]
I don't think we can assume that SLURM is used in conjunction with a shared file system. More importantly, the work dir should reside on fast, locally attached storage.

The best solution I can think of is to track inside the batchsystem which nodes commands were sent to, and then at shutdown schedule individual clean-up commands to those nodes.

**Comment by chapmanb** [comment]
Hannes;
That makes sense, although seems like a lot to implement and is probably non-ideal on busy shared cluster systems where users are likely to be unhappy with having to wait for more queued jobs to start up for cluster cleanup.

Can you describe what shared caching does and why it's useful? I don't mind disabling it, but trying to understand the tradeoffs. All I got from the code was:`A cache-enabled version of Filestore. Basically FileStore on Adderall(R)` I guess it's avoiding copying files multiple times to the same machine if used more than once?

**Comment by hannes-ucsc** [comment]
http://toil.readthedocs.io/en/latest/architecture.html#caching

**Comment by chapmanb** [comment]
Hannes;
Thanks for the pointer -- sorry I missed this. What do you think about having http://toil.readthedocs.io point to http://toil.readthedocs.io/en/latest/ instead of 3.1.x? I missed a lot of useful documentation not realizing that wasn't the latest.

I'll close this now and use `--disableSharedCaching` for SLURM/SGE/local scheduler jobs. It seems like the value of caching is not as high on shared batch systems where your per-node re-use may not be great and they won't be fans of keeping around large files cached into local temporary storage. I can definitely see the value on Amazon to avoid transferring from S3 multiple times. Thanks again for the help.
