### ISSUE TITLE
AssertionError in testMultipleJobsReadSameCacheHitGlobalFile

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#960]
http://jenkins.cgcloud.info/job/toil-pull-requests/1410/

**Comment by hannes-ucsc** [comment]
It just occurred to me that toil-jenkins-slave slaves are shared by toil-scripts and toil. It is possible that toil-scripts pollutes the slave.

**Comment by arkal** [comment]
To the order of 70G? I find that a little hard to believe

**Comment by hannes-ucsc** [comment]
This is caused by running on a slave were for some reason ephemeral wasn't mounted. I'm leaving this open because I don't know why ephemeral is only mounted sometimes. The AMI has a suitable block device mapping. The useEphemeralDevices for the slave was set to false in config.xml. I changed that to true for all slaves. We'll have to keep an eye out for it.

See also https://github.com/BD2KGenomics/cgcloud/issues/184

**Comment by hannes-ucsc** [comment]
We should also talk about detecting lack of temporary space in jenkins.sh, the Makefile, or in a special unit test.

**Comment by arkal** [comment]
Wow! How did you find this?! Awesome. Can we have a line in jenkins.sh that checks for (say) 20G of space on ephemeral before starting any tests?

**Comment by hannes-ucsc** [comment]
Yes, we should.
