### ISSUE TITLE
AssertionError: Attempting to delete a global file that is in use by another job

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#963]
http://jenkins.cgcloud.info/job/toil-branches/branch/master/181/testReport/junit/src.toil.test.src.jobFileStoreTest/JobFileStoreTest/testJobFileStoreWithMediumCacheAndBadWorker/

**Comment by hannes-ucsc** [comment]
http://jenkins.cgcloud.info/job/toil-pull-requests/1446/testReport/junit/src.toil.test.utils.utilsTest/UtilsTest/testUtilsStatsSort/

**Comment by arkal** [comment]
This was resolved in #974. Closing

**Comment by hannes-ucsc** [comment]
https://github.com/BD2KGenomics/toil/pull/974/commits/3b3a8e0ed81ac2a32555908d4be6b3791d640dc9
