### ISSUE TITLE
Remove registry from Azure job store

### ISSUE THREAD

**Issue by JakeNarkizian** [BD2KGenomics/toil#975]
The AWS job store maintains a registry due to eventual consistency issues. @joelarmstrong do you recall why Azure also maintains a registry? If there does not exist a compelling reason it may be worth forgoing the cost of writing to a reading from an extra table in Azure. 

Instead the existence of a job store can be determined by probing for some component of it that is eventually consistent.

**Comment by joelarmstrong** [comment]
No compelling reason at all, I kept the registry only for symmetry with the AWS jobStore, in case there was a use case for querying the registry to see what jobStores existed. The same functionality could be achieved by checking for the existence of the config pickle or something.

**Comment by JakeNarkizian** [comment]
Thanks for the info @joelarmstrong. @hannes-ucsc with this in mind would you feel more comfortable removing the registry in #916 while I'm already touching that part of the code? Or shall we contend with it in a different PR?

**Comment by hannes-ucsc** [comment]
I'm ok with removing it in #916.

Just make sure that the last storage component you remove is the one that you detect job store existence with. This applies to all job stores.
