### ISSUE TITLE
SSLError during SDB requests

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#978]
http://jenkins.cgcloud.info/job/toil-pull-requests/1462/testReport/junit/src.toil.test.sort.sortTest/SortTest/testAwsMesos/

Needs retry.

**Comment by arkal** [comment]
This has exactly the same stacktrace
http://jenkins.cgcloud.info/job/toil-pull-requests/1465/testReport/junit/src.toil.test.sort.sortTest/SortTest/testAwsMesos/

and this one is similar, but crashes with the same SSLError
http://jenkins.cgcloud.info/job/toil-pull-requests/1465/testReport/junit/src.toil.test.src.jobCacheTest/AwsJobStoreCacheTest/testWriteNonLocalFileToJobStore/

**Comment by hannes-ucsc** [comment]
I fear SDB is going bonkers.
