### ISSUE TITLE
retry_azure is broken

### ISSUE THREAD

**Issue by JakeNarkizian** [BD2KGenomics/toil#979]
There is a missing return statement. [See](https://github.com/BD2KGenomics/toil/blob/master/src/toil/jobStores/azureJobStore.py#L789)

**Comment by hannes-ucsc** [comment]
Good catch. Feel free to fix that in one of your ongoing PRs.

**Comment by JakeNarkizian** [comment]
I already opened #980, but I can add it to #916 if you'd like.
