### ISSUE TITLE
compatibility between toil and pbs torque

### ISSUE THREAD

**Issue by aurelBZH** [BD2KGenomics/toil#986]
Hello
in your documentation you show the compatibility between toil and gridengine but is it possible to install and run toil in a pbs torque cluster ?

thanks for your help
Aurélien Béliard

**Comment by hannes-ucsc** [comment]
Currently there is no support for PBS Torque Cluster and no plans for adding it. We welcome external contributions to Toil in the form of pull requests. Toil is extensible in that respect and adding support would not be difficult, provided that all nodes in such a cluster share a file system. If they don't, then you also need to worry about implementing a job store, or use one of the existing cloud-based ones. The latter is probably undesirable, assuming that we are talking about a bare-metal HPC cluster in a data center, not in the cloud.
