### ISSUE TITLE
Copyright header should refer to `Regents of the University of California`

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#989]
… because we have multiple UCs contributingt to Toil.

See also https://github.com/BD2KGenomics/toil-scripts/pull/311

**Comment by hannes-ucsc** [comment]
@benedictpaten, do you agree?

**Comment by fnothaft** [comment]
+1

**Comment by fnothaft** [comment]
In case you're wondering what this looks like, see #990.

**Comment by fnothaft** [comment]
Don't think it is a huge deal one way or the other, but [UC Copyright policy](http://policy.ucop.edu/doc/2100003/CopyrightOwnership) states that copyright for works produced at the UC is owned by the University of California, and the [UC Copyright FAQ](http://copyright.universityofcalifornia.edu/ownership/faq.html#how-do) notes that the proper copyright attribution is to `the Regents of the University of California`.

**Comment by fnothaft** [comment]
I mean, one might note that the `UCSC Computational Genomics Lab` is organizationally under the purview of the `Regents of the University of California`, but it'd be more by-the-books correct to attribute copyright to the latter.
