### ISSUE TITLE
Conflict error on AWS cache test

### ISSUE THREAD

**Issue by JakeNarkizian** [BD2KGenomics/toil#995]
http://jenkins.cgcloud.info/job/toil-pull-requests/1514/testReport/src.toil.test.src.jobCacheTest/AwsJobStoreCacheTest/testRemoveLocalImmutablyReadFile/

**Comment by hannes-ucsc** [comment]
@JakeNarkizian, I edited the description. Please don't use 'see' as the anchor for all your links. That's unorthodox and not very readable.

**Comment by hannes-ucsc** [comment]
I think this can be fixed with a retry during bucket creation.
